import type { DbCalculatorTemplate, CalculatorType } from '@/types/database';

/**
 * Static fallback templates used when Supabase is not configured.
 * Mirrors the seeded data from migrations:
 *   20260820095000_calculator_templates.sql (16 templates)
 *   20260820210000_phase22_additional_templates.sql (24 templates)
 * Total: 40 curated public templates.
 */

function t(
  id: string,
  type: CalculatorType,
  name: string,
  description: string,
  inputData: Record<string, unknown>,
  featured: boolean,
  order: number,
  slug: string,
  seoTitle: string,
  seoDescription: string,
): DbCalculatorTemplate {
  return {
    id,
    user_id: null,
    calculator_type: type,
    name,
    description,
    input_data: inputData,
    schema_version: 1,
    visibility: 'public',
    is_favorite: false,
    is_featured: featured,
    is_published: true,
    display_order: order,
    slug,
    seo_title: seoTitle,
    seo_description: seoDescription,
    created_at: '2026-08-20T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
  };
}

export const FALLBACK_TEMPLATES: DbCalculatorTemplate[] = [
  // ── Painting (12 total: 4 original + 8 new) ──
  t('fb-paint-1', 'paint', 'Standard Living Room',
    'Typical Nigerian living room: 4m x 5m, 3m ceiling, 2 coats, 1 door, 2 windows.',
    { length: 4, width: 5, wallHeight: 3, coats: 2, doors: 1, windows: 2, projectType: 'interior', includeCeiling: true, wasteMargin: 10, unit: 'meters' },
    true, 1, 'standard-living-room-painting',
    'Paint Calculator Template: Standard Living Room | FRELUX',
    'Calculate paint needed for a standard living room with this FRELUX template.'),
  t('fb-paint-2', 'paint', 'Master Bedroom',
    'Master bedroom: 4m x 4m, 2.7m ceiling, 2 coats, 1 door, 2 windows.',
    { length: 4, width: 4, wallHeight: 2.7, coats: 2, doors: 1, windows: 2, projectType: 'interior', includeCeiling: false, wasteMargin: 10, unit: 'meters' },
    false, 2, 'master-bedroom-painting',
    'Paint Calculator Template: Master Bedroom | FRELUX',
    'Calculate paint needed for a master bedroom with this FRELUX template.'),
  t('fb-paint-3', 'paint', 'Single Accent Wall',
    'One accent wall: 3.5m wide, 2.7m high, 2 coats.',
    { length: 3.5, width: 0, wallHeight: 2.7, coats: 2, projectType: 'interior', includeCeiling: false, wasteMargin: 10, unit: 'meters' },
    false, 3, 'single-accent-wall-painting',
    'Paint Calculator Template: Single Accent Wall | FRELUX',
    'Calculate paint for a single accent wall with this FRELUX template.'),
  t('fb-paint-4', 'paint', 'Exterior Bungalow',
    'Exterior bungalow: 15m perimeter, 4m height, 2 coats.',
    { length: 15, width: 0, wallHeight: 4, coats: 2, projectType: 'exterior', includeCeiling: false, wasteMargin: 15, unit: 'meters' },
    false, 4, 'exterior-bungalow-painting',
    'Paint Calculator Template: Exterior Bungalow | FRELUX',
    'Calculate paint for exterior bungalow walls with this FRELUX template.'),
  t('fb-paint-5', 'paint', 'Dining Room',
    'Dining room: 3.5m x 4.5m, 2.8m ceiling, 2 coats, 1 door, 2 windows.',
    { length: 3.5, width: 4.5, wallHeight: 2.8, coats: 2, doors: 1, windows: 2, projectType: 'interior', includeCeiling: true, wasteMargin: 10, unit: 'meters' },
    false, 101, 'dining-room-painting',
    'Paint Calculator Template: Dining Room | FRELUX',
    'Calculate paint needed for a dining room with this FRELUX template.'),
  t('fb-paint-6', 'paint', "Children's Room",
    "Children's room: 3m x 3m, 2.7m ceiling, 2 coats, 1 door, 1 window.",
    { length: 3, width: 3, wallHeight: 2.7, coats: 2, doors: 1, windows: 1, projectType: 'interior', includeCeiling: true, wasteMargin: 10, unit: 'meters' },
    false, 102, 'childrens-room-painting',
    "Paint Calculator Template: Children's Room | FRELUX",
    "Calculate paint needed for a children's room with this FRELUX template."),
  t('fb-paint-7', 'paint', 'Kitchen Walls',
    'Kitchen walls: 3m x 4m, 2.7m ceiling, 2 coats, 1 door, 1 window, ceiling excluded.',
    { length: 3, width: 4, wallHeight: 2.7, coats: 2, doors: 1, windows: 1, projectType: 'interior', includeCeiling: false, wasteMargin: 10, unit: 'meters' },
    false, 103, 'kitchen-walls-painting',
    'Paint Calculator Template: Kitchen Walls | FRELUX',
    'Calculate paint needed for kitchen walls with this FRELUX template.'),
  t('fb-paint-8', 'paint', 'Corridor & Stairwell',
    'Corridor and stairwell: 8m long, 1.5m wide, 3.5m height, 2 coats, 3 doors.',
    { length: 8, width: 1.5, wallHeight: 3.5, coats: 2, doors: 3, windows: 0, projectType: 'interior', includeCeiling: false, wasteMargin: 10, unit: 'meters' },
    false, 104, 'corridor-stairwell-painting',
    'Paint Calculator Template: Corridor & Stairwell | FRELUX',
    'Calculate paint for corridors and stairwells with this FRELUX template.'),
  t('fb-paint-9', 'paint', '2-Bedroom Flat (Full)',
    'Full 2-bedroom flat: 10m x 8m total, 2.8m ceiling, 2 coats, 6 doors, 8 windows.',
    { length: 10, width: 8, wallHeight: 2.8, coats: 2, doors: 6, windows: 8, projectType: 'interior', includeCeiling: true, wasteMargin: 10, unit: 'meters' },
    true, 105, '2-bedroom-flat-full-painting',
    'Paint Calculator Template: 2-Bedroom Flat | FRELUX',
    'Calculate paint for a complete 2-bedroom flat with this FRELUX template.'),
  t('fb-paint-10', 'paint', 'Office Space',
    'Office space: 6m x 8m, 3m ceiling, 2 coats, 2 doors, 4 windows.',
    { length: 6, width: 8, wallHeight: 3, coats: 2, doors: 2, windows: 4, projectType: 'interior', includeCeiling: true, wasteMargin: 10, unit: 'meters' },
    false, 106, 'office-space-painting',
    'Paint Calculator Template: Office Space | FRELUX',
    'Calculate paint needed for office space with this FRELUX template.'),
  t('fb-paint-11', 'paint', 'Exterior Duplex',
    'Exterior duplex: 20m perimeter, 6m height (2 floors), 2 coats.',
    { length: 20, width: 0, wallHeight: 6, coats: 2, projectType: 'exterior', includeCeiling: false, wasteMargin: 15, unit: 'meters' },
    true, 107, 'exterior-duplex-painting',
    'Paint Calculator Template: Exterior Duplex | FRELUX',
    'Calculate paint for exterior duplex walls with this FRELUX template.'),
  t('fb-paint-12', 'paint', 'Shop / Retail Front',
    'Shop front: 5m wide, 4m high, 2 coats, 1 large entrance.',
    { length: 5, width: 0, wallHeight: 4, coats: 2, doors: 1, windows: 0, projectType: 'exterior', includeCeiling: false, wasteMargin: 10, unit: 'meters' },
    false, 108, 'shop-retail-front-painting',
    'Paint Calculator Template: Shop / Retail Front | FRELUX',
    'Calculate paint for shop and retail fronts with this FRELUX template.'),

  // ── Tiling (10 total: 4 original + 6 new) ──
  t('fb-tile-1', 'tile', 'Standard Floor Tiling',
    '4m x 5m floor, 400x400mm tiles, adhesive method.',
    { surfaceType: 'floor', method: 'adhesive', length: 4, width: 5, tileWidthMm: 400, tileHeightMm: 400, wasteMargin: 10, unit: 'meters' },
    true, 5, 'standard-floor-tiling',
    'Tile Calculator Template: Standard Floor Tiling | FRELUX',
    'Calculate tiles, adhesive, and grout for a standard floor with this FRELUX template.'),
  t('fb-tile-2', 'tile', 'Bathroom Wall Tiles',
    '3m x 2.5m walls, 300x600mm tiles, adhesive method.',
    { surfaceType: 'wall', method: 'adhesive', length: 3, width: 2.5, tileWidthMm: 300, tileHeightMm: 600, wasteMargin: 10, unit: 'meters' },
    false, 6, 'bathroom-wall-tiling',
    'Tile Calculator Template: Bathroom Wall Tiles | FRELUX',
    'Calculate tiles for bathroom walls with this FRELUX template.'),
  t('fb-tile-3', 'tile', 'Large Hall Floor',
    '8m x 10m hall, 600x600mm tiles, cement method.',
    { surfaceType: 'floor', method: 'traditional', length: 8, width: 10, tileWidthMm: 600, tileHeightMm: 600, wasteMargin: 10, unit: 'meters' },
    false, 7, 'large-hall-floor-tiling',
    'Tile Calculator Template: Large Hall Floor | FRELUX',
    'Calculate tiles for a large hall floor with this FRELUX template.'),
  t('fb-tile-4', 'tile', 'Kitchen Backsplash',
    'Kitchen backsplash: 3m x 0.6m, 100x100mm mosaic tiles, adhesive method.',
    { surfaceType: 'wall', method: 'adhesive', length: 3, width: 0.6, tileWidthMm: 100, tileHeightMm: 100, wasteMargin: 15, unit: 'meters' },
    false, 8, 'kitchen-backsplash-tiling',
    'Tile Calculator Template: Kitchen Backsplash | FRELUX',
    'Calculate tiles for a kitchen backsplash with this FRELUX template.'),
  t('fb-tile-5', 'tile', 'Balcony Floor Tiling',
    'Balcony floor: 2m x 4m, 300x300mm tiles, cement method.',
    { surfaceType: 'floor', method: 'traditional', length: 2, width: 4, tileWidthMm: 300, tileHeightMm: 300, wasteMargin: 10, unit: 'meters' },
    false, 109, 'balcony-floor-tiling',
    'Tile Calculator Template: Balcony Floor Tiling | FRELUX',
    'Calculate tiles for balcony floors with this FRELUX template.'),
  t('fb-tile-6', 'tile', 'Kitchen Floor Tiles',
    'Kitchen floor: 3m x 4m, 600x600mm tiles, adhesive method.',
    { surfaceType: 'floor', method: 'adhesive', length: 3, width: 4, tileWidthMm: 600, tileHeightMm: 600, wasteMargin: 10, unit: 'meters' },
    false, 110, 'kitchen-floor-tiling',
    'Tile Calculator Template: Kitchen Floor Tiles | FRELUX',
    'Calculate tiles for kitchen floors with this FRELUX template.'),
  t('fb-tile-7', 'tile', 'Guest Toilet Wall Tiles',
    'Guest toilet walls: 1.5m x 1m, 200x400mm tiles, adhesive method.',
    { surfaceType: 'wall', method: 'adhesive', length: 1.5, width: 1, tileWidthMm: 200, tileHeightMm: 400, wasteMargin: 10, unit: 'meters' },
    false, 111, 'guest-toilet-wall-tiling',
    'Tile Calculator Template: Guest Toilet Wall Tiles | FRELUX',
    'Calculate tiles for guest toilet walls with this FRELUX template.'),
  t('fb-tile-8', 'tile', 'Staircase Tiling',
    'Staircase: 1m wide x 3m run, 300x300mm tiles, adhesive method.',
    { surfaceType: 'floor', method: 'adhesive', length: 1, width: 3, tileWidthMm: 300, tileHeightMm: 300, wasteMargin: 15, unit: 'meters' },
    false, 112, 'staircase-tiling',
    'Tile Calculator Template: Staircase Tiling | FRELUX',
    'Calculate tiles for staircases with this FRELUX template.'),
  t('fb-tile-9', 'tile', 'Terrazzo-Style Porcelain Floor',
    'Large hall: 12m x 8m, 800x800mm porcelain tiles, adhesive method.',
    { surfaceType: 'floor', method: 'adhesive', length: 12, width: 8, tileWidthMm: 800, tileHeightMm: 800, wasteMargin: 10, unit: 'meters' },
    true, 113, 'terrazzo-porcelain-floor-tiling',
    'Tile Calculator Template: Large Format Porcelain Floor | FRELUX',
    'Calculate tiles for large format porcelain floors with this FRELUX template.'),
  t('fb-tile-10', 'tile', 'Wall Feature Strip',
    'Decorative wall strip: 4m wide x 1m high, 100x200mm mosaic tiles, adhesive method.',
    { surfaceType: 'wall', method: 'adhesive', length: 4, width: 1, tileWidthMm: 100, tileHeightMm: 200, wasteMargin: 15, unit: 'meters' },
    false, 114, 'wall-feature-strip-tiling',
    'Tile Calculator Template: Wall Feature Strip | FRELUX',
    'Calculate tiles for decorative wall feature strips with this FRELUX template.'),

  // ── Screeding (9 total: 4 original + 5 new) ──
  t('fb-screed-1', 'screeding', 'Standard Room Screeding',
    'Full room screeding: 4m x 5m, 3m ceiling, 1 door, 2 windows.',
    { method: 'full_room', roomLength: 4, roomWidth: 5, wallHeight: 3, doors: 1, windows: 2, unit: 'meters' },
    true, 9, 'standard-room-screeding',
    'Screeding Calculator Template: Standard Room | FRELUX',
    'Calculate screeding materials for a standard room with this FRELUX template.'),
  t('fb-screed-2', 'screeding', 'Single Wall Screeding',
    'Single wall screeding: 4m wide, 2.8m high.',
    { method: 'individual_wall', wallWidth: 4, wallCount: 1, wallHeight: 2.8, doors: 0, windows: 0, unit: 'meters' },
    false, 10, 'single-wall-screeding',
    'Screeding Calculator Template: Single Wall | FRELUX',
    'Calculate screeding materials for a single wall with this FRELUX template.'),
  t('fb-screed-3', 'screeding', 'Living Room + Ceiling',
    'Full living room screeding with ceiling: 5m x 6m, 3m ceiling, 2 doors, 3 windows.',
    { method: 'full_room', roomLength: 5, roomWidth: 6, wallHeight: 3, doors: 2, windows: 3, unit: 'meters' },
    true, 11, 'living-room-ceiling-screeding',
    'Screeding Calculator Template: Living Room + Ceiling | FRELUX',
    'Calculate screeding for living room walls and ceiling with this FRELUX template.'),
  t('fb-screed-4', 'screeding', 'Corridor Walls',
    'Corridor screeding: 6m x 1.5m, 2.8m ceiling, 2 doors.',
    { method: 'full_room', roomLength: 6, roomWidth: 1.5, wallHeight: 2.8, doors: 2, windows: 0, unit: 'meters' },
    false, 12, 'corridor-walls-screeding',
    'Screeding Calculator Template: Corridor Walls | FRELUX',
    'Calculate screeding materials for corridor walls with this FRELUX template.'),
  t('fb-screed-5', 'screeding', 'Dining Room Screeding',
    'Full room screeding: 3.5m x 4.5m, 2.8m ceiling, 1 door, 2 windows.',
    { method: 'full_room', roomLength: 3.5, roomWidth: 4.5, wallHeight: 2.8, doors: 1, windows: 2, unit: 'meters' },
    false, 115, 'dining-room-screeding',
    'Screeding Calculator Template: Dining Room | FRELUX',
    'Calculate screeding materials for a dining room with this FRELUX template.'),
  t('fb-screed-6', 'screeding', 'Office Screeding',
    'Full office screeding: 6m x 8m, 3m ceiling, 2 doors, 4 windows.',
    { method: 'full_room', roomLength: 6, roomWidth: 8, wallHeight: 3, doors: 2, windows: 4, unit: 'meters' },
    false, 116, 'office-screeding',
    'Screeding Calculator Template: Office | FRELUX',
    'Calculate screeding materials for office walls with this FRELUX template.'),
  t('fb-screed-7', 'screeding', 'Corridor Screeding',
    'Corridor screeding: 8m x 1.5m, 3m ceiling, 3 doors.',
    { method: 'full_room', roomLength: 8, roomWidth: 1.5, wallHeight: 3, doors: 3, windows: 0, unit: 'meters' },
    false, 117, 'corridor-screeding',
    'Screeding Calculator Template: Corridor | FRELUX',
    'Calculate screeding materials for corridors with this FRELUX template.'),
  t('fb-screed-8', 'screeding', 'Single Feature Wall',
    'Single feature wall screeding: 4m wide, 2.8m high, 1 wall.',
    { method: 'individual_wall', wallWidth: 4, wallCount: 1, wallHeight: 2.8, doors: 0, windows: 0, unit: 'meters' },
    false, 118, 'single-feature-wall-screeding',
    'Screeding Calculator Template: Single Feature Wall | FRELUX',
    'Calculate screeding materials for a single feature wall with this FRELUX template.'),
  t('fb-screed-9', 'screeding', 'Shop Front Screeding',
    'Shop front screeding: 5m wide, 4m high, 1 large opening.',
    { method: 'individual_wall', wallWidth: 5, wallCount: 1, wallHeight: 4, doors: 1, windows: 0, unit: 'meters' },
    false, 119, 'shop-front-screeding',
    'Screeding Calculator Template: Shop Front | FRELUX',
    'Calculate screeding materials for shop front walls with this FRELUX template.'),

  // ── POP Ceiling (9 total: 4 original + 5 new) ──
  t('fb-pop-1', 'pop', 'Standard Bedroom Ceiling',
    'Standard bedroom POP ceiling: 4m x 4m.',
    { workflow: 'nigeria', roomLength: 4, roomWidth: 4, wasteMargin: 10, includeDecorative: false, includeOptional: false, unit: 'meters' },
    true, 13, 'standard-bedroom-pop-ceiling',
    'POP Ceiling Calculator Template: Standard Bedroom | FRELUX',
    'Calculate POP ceiling materials for a standard bedroom with this FRELUX template.'),
  t('fb-pop-2', 'pop', 'Large Living Room Ceiling',
    'Large living room POP ceiling: 5m x 6m, with decorative elements.',
    { workflow: 'nigeria', roomLength: 5, roomWidth: 6, wasteMargin: 10, includeDecorative: true, includeOptional: false, unit: 'meters' },
    true, 14, 'large-living-room-pop-ceiling',
    'POP Ceiling Calculator Template: Large Living Room | FRELUX',
    'Calculate POP ceiling materials for a large living room with this FRELUX template.'),
  t('fb-pop-3', 'pop', 'Small Office Ceiling',
    'Small office POP ceiling: 3m x 3m, basic design.',
    { workflow: 'nigeria', roomLength: 3, roomWidth: 3, wasteMargin: 10, includeDecorative: false, includeOptional: false, unit: 'meters' },
    false, 15, 'small-office-pop-ceiling',
    'POP Ceiling Calculator Template: Small Office | FRELUX',
    'Calculate POP ceiling materials for a small office with this FRELUX template.'),
  t('fb-pop-4', 'pop', 'Hall Ceiling with Cornice',
    'Hall POP ceiling: 8m x 10m, with cornice and decorative elements.',
    { workflow: 'nigeria', roomLength: 8, roomWidth: 10, wasteMargin: 10, includeDecorative: true, includeOptional: true, unit: 'meters' },
    true, 16, 'hall-cornice-pop-ceiling',
    'POP Ceiling Calculator Template: Hall Ceiling with Cornice | FRELUX',
    'Calculate POP ceiling materials for a large hall with cornice with this FRELUX template.'),
  t('fb-pop-5', 'pop', 'Dining Room POP Ceiling',
    'Dining room POP ceiling: 3.5m x 4.5m, with decorative elements.',
    { workflow: 'nigeria', roomLength: 3.5, roomWidth: 4.5, wasteMargin: 10, includeDecorative: true, includeOptional: false, unit: 'meters' },
    false, 120, 'dining-room-pop-ceiling',
    'POP Ceiling Calculator Template: Dining Room | FRELUX',
    'Calculate POP ceiling materials for a dining room with this FRELUX template.'),
  t('fb-pop-6', 'pop', 'Kitchen POP Ceiling',
    'Kitchen POP ceiling: 3m x 4m, basic design without decorative elements.',
    { workflow: 'nigeria', roomLength: 3, roomWidth: 4, wasteMargin: 10, includeDecorative: false, includeOptional: false, unit: 'meters' },
    false, 121, 'kitchen-pop-ceiling',
    'POP Ceiling Calculator Template: Kitchen | FRELUX',
    'Calculate POP ceiling materials for a kitchen with this FRELUX template.'),
  t('fb-pop-7', 'pop', 'Corridor POP Ceiling',
    'Corridor POP ceiling: 8m x 1.5m, with cornice.',
    { workflow: 'nigeria', roomLength: 8, roomWidth: 1.5, wasteMargin: 10, includeDecorative: true, includeOptional: false, unit: 'meters' },
    false, 122, 'corridor-pop-ceiling',
    'POP Ceiling Calculator Template: Corridor | FRELUX',
    'Calculate POP ceiling materials for a corridor with this FRELUX template.'),
  t('fb-pop-8', 'pop', 'Master Bedroom POP Ceiling',
    'Master bedroom POP ceiling: 4m x 4m, with decorative rose.',
    { workflow: 'nigeria', roomLength: 4, roomWidth: 4, wasteMargin: 10, includeDecorative: true, includeOptional: true, unit: 'meters' },
    true, 123, 'master-bedroom-pop-ceiling',
    'POP Ceiling Calculator Template: Master Bedroom | FRELUX',
    'Calculate POP ceiling materials for a master bedroom with this FRELUX template.'),
  t('fb-pop-9', 'pop', 'Conference Room POP Ceiling',
    'Large conference room POP ceiling: 8m x 10m, decorative design.',
    { workflow: 'nigeria', roomLength: 8, roomWidth: 10, wasteMargin: 10, includeDecorative: true, includeOptional: true, unit: 'meters' },
    false, 124, 'conference-room-pop-ceiling',
    'POP Ceiling Calculator Template: Conference Room | FRELUX',
    'Calculate POP ceiling materials for a large conference room with this FRELUX template.'),
];
