// =========================================================
// FRELUX Wall Finishing — assembly templates (layer sequences).
//
// Each country's typical finishing sequence, from the verified
// worldwide research table (Oct 2026). Coverage rates below are
// documented engineering defaults — overridable per layer, and
// always shown in the transparency breakdown.
//
// Verified sources behind the defaults (live scans, Oct 2026):
// - US: USG Sheetrock 4.5 gal pail $24.09; FibaTape 500 ft $17.59
//   (Home Depot). Behr Premium Plus ~$33.98/gal.
// - CA: CGC Sheetrock All-Purpose 12 L pail $37.78 (Home Depot.ca).
// - GB: Thistle MultiFinish 25 kg from £7.93 (BuildBuddy), covers
//   ~10-12 m² at 2-3 mm; Dulux Easycare 10 L £58 (B&Q).
// - DE: Alpina Weiß 10 L ~55 m² per 2 coats (Amazon.de datasheet).
// - IN: Birla White WallCare Putty 40 kg ₹660-730 (IndiaMART);
//   Asian Paints TruCare primer 20 L ~₹2,650-2,900; Tractor
//   Emulsion 20 L ~₹1,900.
// - AU: CSR Gyprock Base Coat 45 20 kg $69.50; Taubmans 3-in-1
//   10 L $99; Taubmans low sheen 10 L ~$65.
// - NG: emulsion 20 L ₦15,000-20,000 (market survey).
// =========================================================

import type { WallAssemblyTemplate } from "@/types/wallfinishing";

/** Per-area sandpaper allowance: one sheet covers ~20 m². */
const SANDPAPER_PER_M2 = 0.05;
/** One 500 ft (150 m) tape roll per ~93 m² of drywall (US practice). */
const TAPE_ROLLS_PER_M2 = 0.0108;

export const WALLFIN_ASSEMBLIES: WallAssemblyTemplate[] = [
  // ── Nigeria ───────────────────────────────
  {
    id: "ng-interior-block-paint",
    name: "Block → render → screeding putty → primer → emulsion",
    description:
      "The classic Nigerian interior finish: cement-sand render, screeding putty skim, sand, primer and two coats of emulsion.",
    surface: "interior",
    substrates: ["block", "masonry", "concrete"],
    layerCountNote: null,
    layers: [
      {
        id: "ng-int-render",
        name: "Cement-sand render (1:4)",
        category: "base",
        materialRole: "concrete-mix",
        quantityMode: "volume",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: { min: 10, max: 20, default: 15 },
        mix: [
          { role: "concrete-mix", parts: 1 },
          { role: "sand", parts: 4 },
        ],
        unitsPerM2: null,
        unit: "m² at 15 mm",
        applicationMethod:
          "Trowel-applied in two passes; rule off and rub up flat",
        dryingInfo: "Cure at least 7 days before applying putty",
        wastePercent: 15,
        labourTask: "wallfin_rendering",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "ng-int-putty",
        name: "Screeding putty skim",
        category: "skim",
        materialRole: "joint-filler",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 20,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "20 kg bag",
        applicationMethod: "Trowel/blade skim in two thin coats",
        dryingInfo: "4-6 hours between coats; fully dry before sanding",
        wastePercent: 10,
        labourTask: "wallfin_putty",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "ng-int-sand",
        name: "Sanding",
        category: "sand",
        materialRole: "sandpaper",
        quantityMode: "per-area",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: SANDPAPER_PER_M2,
        unit: "sheets",
        applicationMethod: "Fine sand smooth, dust off before primer",
        dryingInfo: "None",
        wastePercent: 5,
        labourTask: "wallfin_sanding",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "ng-int-primer",
        name: "Undercoat primer",
        category: "primer",
        materialRole: "primer",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 10,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Brush or roller, one sealing coat",
        dryingInfo: "Dry 2-4 hours before paint",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "ng-int-paint",
        name: "Interior emulsion",
        category: "finish",
        materialRole: "interior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 10,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "interior",
        optional: false,
        note: null,
      },
    ],
  },
  {
    id: "ng-exterior-block-render-paint",
    name: "Block → render → exterior acrylic",
    description:
      "Nigerian exterior finish: cement-sand render finished with weatherproof exterior emulsion.",
    surface: "exterior",
    substrates: ["block", "masonry", "concrete"],
    layerCountNote: null,
    layers: [
      {
        id: "ng-ext-render",
        name: "Cement-sand render (1:4)",
        category: "base",
        materialRole: "concrete-mix",
        quantityMode: "volume",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: { min: 12, max: 20, default: 15 },
        mix: [
          { role: "concrete-mix", parts: 1 },
          { role: "sand", parts: 4 },
        ],
        unitsPerM2: null,
        unit: "m² at 15 mm",
        applicationMethod: "Two-pass render, wood-float finish",
        dryingInfo: "Cure 7+ days before painting",
        wastePercent: 15,
        labourTask: "wallfin_rendering",
        surface: "exterior",
        optional: false,
        note: null,
      },
      {
        id: "ng-ext-paint",
        name: "Exterior acrylic emulsion",
        category: "finish",
        materialRole: "exterior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 8,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller or spray, two coats",
        dryingInfo: "Recoat after 4-6 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "exterior",
        optional: false,
        note: null,
      },
    ],
  },

  // ── United States ────────────────────────
  {
    id: "us-interior-drywall-paint",
    name: "Drywall → tape → joint compound → sand → primer → paint",
    description:
      "The standard US drywall finish: joint tape bedded in all-purpose compound, two more coats, sanded, primed and painted.",
    surface: "interior",
    substrates: ["drywall", "timber", "steel"],
    layerCountNote: null,
    layers: [
      {
        id: "us-int-tape",
        name: "Joint tape",
        category: "prep",
        materialRole: "joint-tape",
        quantityMode: "per-area",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: TAPE_ROLLS_PER_M2,
        unit: "roll (150 m / 500 ft)",
        applicationMethod: "Paper or mesh tape over all board joints",
        dryingInfo: "N/A",
        wastePercent: 5,
        labourTask: "wallfin_taping",
        surface: "interior",
        optional: false,
        note: "One 500 ft roll per ~93 m² (1000 sq ft) of drywall.",
      },
      {
        id: "us-int-compound",
        name: "All-purpose joint compound",
        category: "skim",
        materialRole: "joint-filler",
        quantityMode: "area-coverage",
        // 4.5 gal (17 L) pail covers ~46 m² (500 sq ft) per coat.
        coverageRateM2PerUnit: 46,
        coats: 3,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "17 L (4.5 gal) pail",
        applicationMethod: "Tape coat + two finishing coats",
        dryingInfo: "24 hours between coats",
        wastePercent: 10,
        labourTask: "wallfin_taping",
        surface: "interior",
        optional: false,
        note: "USG Sheetrock All-Purpose: verified $24.09 per pail (Home Depot, Oct 2026).",
      },
      {
        id: "us-int-sand",
        name: "Sanding",
        category: "sand",
        materialRole: "sandpaper",
        quantityMode: "per-area",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: SANDPAPER_PER_M2,
        unit: "sheets",
        applicationMethod: "Fine sand joints smooth, dust off",
        dryingInfo: "None",
        wastePercent: 5,
        labourTask: "wallfin_sanding",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "us-int-primer",
        name: "Drywall primer",
        category: "primer",
        materialRole: "primer",
        quantityMode: "area-coverage",
        // 350-400 sq ft per gallon.
        coverageRateM2PerUnit: 37,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "gallon",
        applicationMethod: "Roller, one uniform sealing coat",
        dryingInfo: "Dry 3-4 hours before paint",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "us-int-paint",
        name: "Interior paint",
        category: "finish",
        materialRole: "interior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 37,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "gallon",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "interior",
        optional: false,
        note: "Behr Premium Plus: verified ~$33.98/gal (Home Depot, Oct 2026).",
      },
    ],
  },
  {
    id: "us-exterior-masonry-paint",
    name: "Exterior masonry → primer → exterior acrylic",
    description:
      "US exterior finish for masonry/concrete: optional self-priming exterior acrylic in two coats.",
    surface: "exterior",
    substrates: ["brick", "block", "masonry", "concrete"],
    layerCountNote: null,
    layers: [
      {
        id: "us-ext-primer",
        name: "Bonding/masonry primer",
        category: "primer",
        materialRole: "primer",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 30,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "gallon",
        applicationMethod: "Roller on clean, dry masonry",
        dryingInfo: "Dry 4 hours before topcoat",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "exterior",
        optional: true,
        note: "Skip when using a self-priming exterior paint (e.g. Behr Premium Plus Exterior).",
      },
      {
        id: "us-ext-paint",
        name: "Exterior acrylic",
        category: "finish",
        materialRole: "exterior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 30,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "gallon",
        applicationMethod: "Roller or spray, two coats",
        dryingInfo: "Recoat after 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "exterior",
        optional: false,
        note: null,
      },
    ],
  },

  // ── United Kingdom ───────────────────────
  {
    id: "gb-interior-block-skim-paint",
    name: "Block/brick → undercoat where required → skim plaster → mist coat → emulsion",
    description:
      "UK masonry finish: bonding/undercoat plaster where required, then a Thistle MultiFinish skim, a mist coat and two coats of emulsion.",
    surface: "interior",
    substrates: ["block", "brick", "masonry"],
    layerCountNote: null,
    layers: [
      {
        id: "gb-int-undercoat",
        name: "Bonding/undercoat plaster",
        category: "base",
        materialRole: "bonding-plaster",
        quantityMode: "area-coverage",
        // 25 kg undercoat bag covers ~8.9 m² at 3 mm.
        coverageRateM2PerUnit: 8.9,
        coats: 1,
        thickness: { min: 3, max: 8, default: 3 },
        mix: null,
        unitsPerM2: null,
        unit: "25 kg bag",
        applicationMethod:
          "Trowel-applied undercoat where the background requires it",
        dryingInfo: "Key the surface; follow manufacturer's setting times",
        wastePercent: 12,
        labourTask: "wallfin_plastering",
        surface: "interior",
        optional: true,
        note: "Only where the background is uneven or suction is high — your plasterer decides.",
      },
      {
        id: "gb-int-skim",
        name: "Skim plaster (MultiFinish)",
        category: "skim",
        materialRole: "skim-plaster",
        quantityMode: "area-coverage",
        // Thistle MultiFinish: 25 kg bag covers ~10-12 m² at 2 mm.
        coverageRateM2PerUnit: 10.5,
        coats: 1,
        thickness: { min: 2, max: 3, default: 2 },
        mix: null,
        unitsPerM2: null,
        unit: "25 kg bag",
        applicationMethod: "Two-coat skim trowelled to a polished finish",
        dryingInfo: "Dry 2-7 days before mist coating",
        wastePercent: 12,
        labourTask: "wallfin_plastering",
        surface: "interior",
        optional: false,
        note: "Verified from £7.93 per 25 kg (BuildBuddy, Oct 2026).",
      },
      {
        id: "gb-int-mist",
        name: "Mist coat",
        category: "primer",
        materialRole: "mist-coat",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 12,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Emulsion thinned ~10% with water, roller",
        dryingInfo: "Dry overnight before topcoats",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "interior",
        optional: false,
        note: "A mist coat is diluted emulsion — the UK standard seal on fresh skim.",
      },
      {
        id: "gb-int-paint",
        name: "Emulsion",
        category: "finish",
        materialRole: "interior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 13,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "interior",
        optional: false,
        note: "Dulux Easycare 10 L verified £58 (B&Q, Oct 2026).",
      },
    ],
  },
  {
    id: "gb-interior-plasterboard-paint",
    name: "Plasterboard → jointing → optional skim → mist → emulsion",
    description:
      "UK drylining finish: joint tape and Easi-Fill, optional skim, mist coat and emulsion.",
    surface: "interior",
    substrates: ["drywall", "timber"],
    layerCountNote: null,
    layers: [
      {
        id: "gb-pb-tape",
        name: "Joint tape",
        category: "prep",
        materialRole: "joint-tape",
        quantityMode: "per-area",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: TAPE_ROLLS_PER_M2,
        unit: "roll (150 m)",
        applicationMethod: "Paper tape over board joints",
        dryingInfo: "N/A",
        wastePercent: 5,
        labourTask: "wallfin_taping",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "gb-pb-joint",
        name: "Jointing compound (Easi-Fill)",
        category: "skim",
        materialRole: "joint-filler",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 40,
        coats: 3,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "10 kg bag",
        applicationMethod: "Tape coat + two finishing coats",
        dryingInfo: "Setting compound — coat-by-coat per pack instructions",
        wastePercent: 10,
        labourTask: "wallfin_taping",
        surface: "interior",
        optional: false,
        note: "Gyproc Easi-Fill 10 kg verified £34.74.",
      },
      {
        id: "gb-pb-skim",
        name: "Skim plaster (optional)",
        category: "skim",
        materialRole: "skim-plaster",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 10.5,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "25 kg bag",
        applicationMethod: "Skim over jointed board for a plastered finish",
        dryingInfo: "Dry 2-7 days before painting",
        wastePercent: 12,
        labourTask: "wallfin_plastering",
        surface: "interior",
        optional: true,
        note: "Skip when jointing is finished to paint standard.",
      },
      {
        id: "gb-pb-mist",
        name: "Mist coat",
        category: "primer",
        materialRole: "mist-coat",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 12,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Thinned emulsion, roller",
        dryingInfo: "Dry overnight",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "gb-pb-paint",
        name: "Emulsion",
        category: "finish",
        materialRole: "interior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 13,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "interior",
        optional: false,
        note: null,
      },
    ],
  },
  {
    id: "gb-exterior-render-paint",
    name: "Exterior render (optional) → masonry paint",
    description:
      "UK exterior: optional cement-lime render on exposed masonry, then two coats of masonry paint.",
    surface: "exterior",
    substrates: ["brick", "block", "masonry"],
    layerCountNote: null,
    layers: [
      {
        id: "gb-ext-render",
        name: "Cement-lime render (1:5)",
        category: "base",
        materialRole: "concrete-mix",
        quantityMode: "volume",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: { min: 12, max: 20, default: 16 },
        mix: [
          { role: "concrete-mix", parts: 1 },
          { role: "sand", parts: 5 },
        ],
        unitsPerM2: null,
        unit: "m² at 16 mm",
        applicationMethod: "Two-coat render, scraped or sponge finish",
        dryingInfo: "Cure 7+ days; allow weathering before painting",
        wastePercent: 12,
        labourTask: "wallfin_rendering",
        surface: "exterior",
        optional: true,
        note: "Many UK exteriors are fair-faced brick — skip render and paint only.",
      },
      {
        id: "gb-ext-paint",
        name: "Exterior masonry paint",
        category: "finish",
        materialRole: "exterior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 12,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller or brush, two coats on sound render",
        dryingInfo: "Recoat 4-16 hours per manufacturer",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "exterior",
        optional: false,
        note: null,
      },
    ],
  },

  // ── Germany ───────────────────────────────
  {
    id: "de-interior-masonry-paint",
    name: "Masonry → gypsum base plaster → fine filler → Tiefgrund → interior paint",
    description:
      "German interior finish: machine-applied gypsum base plaster, fine filler skim, deep-penetration primer and dispersion paint.",
    surface: "interior",
    substrates: ["masonry", "block", "brick"],
    layerCountNote: null,
    layers: [
      {
        id: "de-int-base",
        name: "Gypsum base plaster (Maschinenputz)",
        category: "base",
        materialRole: "gypsum-plaster",
        quantityMode: "area-coverage",
        // Knauf MP75: ~1 kg/m² per mm → 30 kg sack ≈ 3 m² at 10 mm.
        coverageRateM2PerUnit: 3,
        coats: 1,
        thickness: { min: 8, max: 15, default: 10 },
        mix: null,
        unitsPerM2: null,
        unit: "30 kg sack",
        applicationMethod: "Machine-sprayed, rule off and felt",
        dryingInfo: "Dry several days; fine filler only on fully dry plaster",
        wastePercent: 10,
        labourTask: "wallfin_plastering",
        surface: "interior",
        optional: false,
        note: "Knauf MP75: ~10 kg/m² at 10 mm per datasheet.",
      },
      {
        id: "de-int-fine",
        name: "Fine filler (Feinspachtel)",
        category: "skim",
        materialRole: "fine-filler",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 30,
        coats: 1,
        thickness: { min: 0, max: 2, default: 1 },
        mix: null,
        unitsPerM2: null,
        unit: "25 kg container",
        applicationMethod: "Thin spatula skim, sand smooth",
        dryingInfo: "Dry 24 hours per coat",
        wastePercent: 8,
        labourTask: "wallfin_skimming",
        surface: "interior",
        optional: true,
        note: "Only needed for Q3/Q4 paint-ready surfaces.",
      },
      {
        id: "de-int-tiefgrund",
        name: "Deep primer (Tiefgrund)",
        category: "primer",
        materialRole: "primer",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 10,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, one penetrating coat",
        dryingInfo: "Dry 2-3 hours",
        wastePercent: 8,
        labourTask: "wallfin_priming",
        surface: "interior",
        optional: false,
        note: "Caparol Tiefgrund TB 10 L seeded in the DE book.",
      },
      {
        id: "de-int-paint",
        name: "Interior dispersion paint",
        category: "finish",
        materialRole: "interior-paint",
        quantityMode: "area-coverage",
        // Alpina Weiß: 10 L covers ~55 m² (2 coats) → ~11 m²/L per coat.
        coverageRateM2PerUnit: 11,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 4-6 hours",
        wastePercent: 8,
        labourTask: "wallfin_painting",
        surface: "interior",
        optional: false,
        note: "Alpina Weiß 10 L verified €39.95 (Hornbach).",
      },
    ],
  },
  {
    id: "de-exterior-render-paint",
    name: "Masonry → mineral base render → facade paint",
    description:
      "German exterior: mineral base render finished with silicone-resin facade paint.",
    surface: "exterior",
    substrates: ["masonry", "block", "brick"],
    layerCountNote: null,
    layers: [
      {
        id: "de-ext-render",
        name: "Mineral base render",
        category: "base",
        materialRole: "concrete-mix",
        quantityMode: "volume",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: { min: 10, max: 20, default: 15 },
        mix: [
          { role: "concrete-mix", parts: 1 },
          { role: "sand", parts: 4 },
        ],
        unitsPerM2: null,
        unit: "m² at 15 mm",
        applicationMethod: "Machine or hand-applied, rubbed finish",
        dryingInfo: "Cure 7+ days before coating",
        wastePercent: 10,
        labourTask: "wallfin_rendering",
        surface: "exterior",
        optional: false,
        note: null,
      },
      {
        id: "de-ext-paint",
        name: "Silicone-resin facade paint",
        category: "finish",
        materialRole: "exterior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 6.5,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller or spray, two coats",
        dryingInfo: "Recoat after 12-24 hours",
        wastePercent: 8,
        labourTask: "wallfin_painting",
        surface: "exterior",
        optional: false,
        note: "Alpina Fassadenfarbe 10 L ~€55-65 (hagebau).",
      },
    ],
  },

  // ── India ────────────────────────────────
  {
    id: "in-interior-brick-paint",
    name: "Brick/block → cement-sand plaster → wall putty → primer → paint",
    description:
      "The standard Indian interior: 12 mm cement-sand plaster, white-cement wall putty, primer and emulsion.",
    surface: "interior",
    substrates: ["brick", "block", "masonry", "concrete"],
    layerCountNote: null,
    layers: [
      {
        id: "in-int-plaster",
        name: "Cement-sand plaster (1:4, 12 mm)",
        category: "base",
        materialRole: "concrete-mix",
        quantityMode: "volume",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: { min: 10, max: 15, default: 12 },
        mix: [
          { role: "concrete-mix", parts: 1 },
          { role: "sand", parts: 4 },
        ],
        unitsPerM2: null,
        unit: "m² at 12 mm",
        applicationMethod: "Two-coat plaster, roded and wood-float finish",
        dryingInfo: "Cure 7 days before putty",
        wastePercent: 15,
        labourTask: "wallfin_rendering",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "in-int-putty",
        name: "White cement wall putty",
        category: "skim",
        materialRole: "joint-filler",
        quantityMode: "area-coverage",
        // Birla White WallCare: ~1 kg/m² per coat → 40 kg ≈ 35 m² per coat.
        coverageRateM2PerUnit: 35,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "40 kg bag",
        applicationMethod: "Blade-apply two thin coats, sand between",
        dryingInfo: "4-6 hours between coats",
        wastePercent: 10,
        labourTask: "wallfin_putty",
        surface: "interior",
        optional: false,
        note: "Birla White WallCare 40 kg verified ₹660-730 (IndiaMART, Oct 2026).",
      },
      {
        id: "in-int-primer",
        name: "Interior wall primer",
        category: "primer",
        materialRole: "primer",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 12,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, one sealing coat",
        dryingInfo: "Dry 4-6 hours",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "interior",
        optional: false,
        note: "Asian Paints TruCare 20 L verified ₹2,650-2,900.",
      },
      {
        id: "in-int-paint",
        name: "Interior emulsion",
        category: "finish",
        materialRole: "interior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 12,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 4-6 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "interior",
        optional: false,
        note: "Tractor Emulsion 20 L ~₹1,900 (market survey).",
      },
    ],
  },
  {
    id: "in-exterior-render-paint",
    name: "Brick/block → plaster → exterior emulsion",
    description:
      "Indian exterior: cement-sand plaster finished with weatherproof exterior emulsion.",
    surface: "exterior",
    substrates: ["brick", "block", "masonry", "concrete"],
    layerCountNote: null,
    layers: [
      {
        id: "in-ext-plaster",
        name: "Cement-sand plaster (1:4, 15 mm)",
        category: "base",
        materialRole: "concrete-mix",
        quantityMode: "volume",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: { min: 12, max: 20, default: 15 },
        mix: [
          { role: "concrete-mix", parts: 1 },
          { role: "sand", parts: 4 },
        ],
        unitsPerM2: null,
        unit: "m² at 15 mm",
        applicationMethod: "Two-coat exterior plaster",
        dryingInfo: "Cure 7+ days",
        wastePercent: 15,
        labourTask: "wallfin_rendering",
        surface: "exterior",
        optional: false,
        note: null,
      },
      {
        id: "in-ext-paint",
        name: "Exterior emulsion",
        category: "finish",
        materialRole: "exterior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 8,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 6 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "exterior",
        optional: false,
        note: "Asian Paints Apex Ultima 10 L seeded ₹5,960.",
      },
    ],
  },

  // ── Canada ────────────────────────────────
  {
    id: "ca-interior-drywall-paint",
    name: "Drywall → tape → joint compound → sand → primer → paint",
    description:
      "Canadian drywall finish: tape and CGC compound, sand, prime and paint — same system as the US with Canadian products.",
    surface: "interior",
    substrates: ["drywall", "timber", "steel"],
    layerCountNote: null,
    layers: [
      {
        id: "ca-int-tape",
        name: "Joint tape",
        category: "prep",
        materialRole: "joint-tape",
        quantityMode: "per-area",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: TAPE_ROLLS_PER_M2,
        unit: "roll (150 m / 500 ft)",
        applicationMethod: "CGC Synko paper tape over board joints",
        dryingInfo: "N/A",
        wastePercent: 5,
        labourTask: "wallfin_taping",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "ca-int-compound",
        name: "All-purpose joint compound",
        category: "skim",
        materialRole: "joint-filler",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 46,
        coats: 3,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "17 L (12 L in stores) pail",
        applicationMethod: "Tape coat + two finishing coats",
        dryingInfo: "24 hours between coats",
        wastePercent: 10,
        labourTask: "wallfin_taping",
        surface: "interior",
        optional: false,
        note: "CGC Sheetrock All-Purpose 12 L pail verified $37.78 (Home Depot.ca, Oct 2026).",
      },
      {
        id: "ca-int-sand",
        name: "Sanding",
        category: "sand",
        materialRole: "sandpaper",
        quantityMode: "per-area",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: SANDPAPER_PER_M2,
        unit: "sheets",
        applicationMethod: "Fine sand joints, dust off",
        dryingInfo: "None",
        wastePercent: 5,
        labourTask: "wallfin_sanding",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "ca-int-primer",
        name: "Drywall primer",
        category: "primer",
        materialRole: "primer",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 35,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, one sealing coat",
        dryingInfo: "Dry 3-4 hours",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "ca-int-paint",
        name: "Interior paint",
        category: "finish",
        materialRole: "interior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 35,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "interior",
        optional: false,
        note: null,
      },
    ],
  },
  {
    id: "ca-exterior-masonry-paint",
    name: "Exterior masonry → primer → exterior acrylic",
    description:
      "Canadian exterior: optional bonding primer plus two coats of exterior acrylic on masonry.",
    surface: "exterior",
    substrates: ["brick", "block", "masonry", "concrete"],
    layerCountNote: null,
    layers: [
      {
        id: "ca-ext-primer",
        name: "Masonry primer",
        category: "primer",
        materialRole: "primer",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 30,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller on clean masonry",
        dryingInfo: "Dry 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "exterior",
        optional: true,
        note: "Skip when using self-priming exterior paint.",
      },
      {
        id: "ca-ext-paint",
        name: "Exterior acrylic",
        category: "finish",
        materialRole: "exterior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 30,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller or spray, two coats",
        dryingInfo: "Recoat after 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "exterior",
        optional: false,
        note: null,
      },
    ],
  },

  // ── Australia ─────────────────────────────
  {
    id: "au-interior-plasterboard-paint",
    name: "Plasterboard → tape + base/topping compound → sand → sealer → low sheen",
    description:
      "Australian plasterboard finish: joint tape bedded in base coat, topped, sanded, sealed and painted.",
    surface: "interior",
    substrates: ["drywall", "timber", "steel"],
    layerCountNote: null,
    layers: [
      {
        id: "au-int-tape",
        name: "Joint tape",
        category: "prep",
        materialRole: "joint-tape",
        quantityMode: "per-area",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: TAPE_ROLLS_PER_M2,
        unit: "roll (150 m)",
        applicationMethod: "Paper tape over plasterboard joints",
        dryingInfo: "N/A",
        wastePercent: 5,
        labourTask: "wallfin_taping",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "au-int-compound",
        name: "Base + topping compound",
        category: "skim",
        materialRole: "joint-filler",
        quantityMode: "area-coverage",
        // CSR Gyprock Base Coat 45, 20 kg — estimated wall coverage for
        // the 3-coat joint system; verify against the pack.
        coverageRateM2PerUnit: 45,
        coats: 3,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "20 kg bag",
        applicationMethod: "Base coat over tape + two top coats",
        dryingInfo: "Setting compound — follow pack times",
        wastePercent: 10,
        labourTask: "wallfin_taping",
        surface: "interior",
        optional: false,
        note: "CSR Gyprock Base Coat 45 20 kg verified $69.50 (Mahoneys Timber, Oct 2026).",
      },
      {
        id: "au-int-sand",
        name: "Sanding",
        category: "sand",
        materialRole: "sandpaper",
        quantityMode: "per-area",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: SANDPAPER_PER_M2,
        unit: "sheets",
        applicationMethod: "Fine sand, dust off",
        dryingInfo: "None",
        wastePercent: 5,
        labourTask: "wallfin_sanding",
        surface: "interior",
        optional: false,
        note: null,
      },
      {
        id: "au-int-sealer",
        name: "Sealer / primer (3-in-1 prep)",
        category: "primer",
        materialRole: "primer",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 12,
        coats: 1,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, one sealing coat",
        dryingInfo: "Dry 2-3 hours",
        wastePercent: 10,
        labourTask: "wallfin_priming",
        surface: "interior",
        optional: false,
        note: "Taubmans 3-in-1 10 L verified $99 (paintmate, Oct 2026).",
      },
      {
        id: "au-int-paint",
        name: "Low-sheen acrylic",
        category: "finish",
        materialRole: "interior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 15,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 2-4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "interior",
        optional: false,
        note: "Taubmans low sheen 10 L ~$65-99 (market survey).",
      },
    ],
  },
  {
    id: "au-exterior-render-paint",
    name: "Masonry → render (optional) → exterior acrylic",
    description:
      "Australian exterior: optional cement render on face brick/masonry, two coats of exterior acrylic.",
    surface: "exterior",
    substrates: ["brick", "block", "masonry", "concrete"],
    layerCountNote: null,
    layers: [
      {
        id: "au-ext-render",
        name: "Cement render (1:4, 12 mm)",
        category: "base",
        materialRole: "concrete-mix",
        quantityMode: "volume",
        coverageRateM2PerUnit: null,
        coats: 1,
        thickness: { min: 10, max: 15, default: 12 },
        mix: [
          { role: "concrete-mix", parts: 1 },
          { role: "sand", parts: 4 },
        ],
        unitsPerM2: null,
        unit: "m² at 12 mm",
        applicationMethod: "Two-coat render on prepared masonry",
        dryingInfo: "Cure 7+ days",
        wastePercent: 12,
        labourTask: "wallfin_rendering",
        surface: "exterior",
        optional: true,
        note: "Face-brick exteriors usually stay unpainted or painted directly.",
      },
      {
        id: "au-ext-paint",
        name: "Exterior acrylic",
        category: "finish",
        materialRole: "exterior-paint",
        quantityMode: "area-coverage",
        coverageRateM2PerUnit: 12,
        coats: 2,
        thickness: null,
        mix: null,
        unitsPerM2: null,
        unit: "litre",
        applicationMethod: "Roller, two coats",
        dryingInfo: "Recoat after 4 hours",
        wastePercent: 10,
        labourTask: "wallfin_painting",
        surface: "exterior",
        optional: false,
        note: null,
      },
    ],
  },
];

export const WALLFIN_ASSEMBLY_MAP: Record<string, WallAssemblyTemplate> =
  Object.fromEntries(WALLFIN_ASSEMBLIES.map((a) => [a.id, a]));

export function getAssembly(id: string): WallAssemblyTemplate | null {
  return WALLFIN_ASSEMBLY_MAP[id] ?? null;
}

export function getAssembliesForCountry(code: string): WallAssemblyTemplate[] {
  return WALLFIN_ASSEMBLIES.filter((a) =>
    a.id.startsWith(`${code.toLowerCase()}-`),
  );
}
