/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // shadcn/ui semantic tokens — hsl(var(--token) / <alpha>)
        background: 'hsl(var(--background) / <alpha-value>)',
        foreground: 'hsl(var(--foreground) / <alpha-value>)',
        card: {
          DEFAULT: 'hsl(var(--card) / <alpha-value>)',
          foreground: 'hsl(var(--card-foreground) / <alpha-value>)',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover) / <alpha-value>)',
          foreground: 'hsl(var(--popover-foreground) / <alpha-value>)',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary) / <alpha-value>)',
          foreground: 'hsl(var(--primary-foreground) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary) / <alpha-value>)',
          foreground: 'hsl(var(--secondary-foreground) / <alpha-value>)',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted) / <alpha-value>)',
          foreground: 'hsl(var(--muted-foreground) / <alpha-value>)',
        },
        // Merged: shadcn semantic tokens + custom accent colors
        accent: {
          DEFAULT: 'hsl(var(--accent) / <alpha-value>)',
          foreground: 'hsl(var(--accent-foreground) / <alpha-value>)',
          orange: 'rgb(var(--brand-accent) / <alpha-value>)',
          yellow: '#EAB308',
          green: '#10B981',
          'green-light': '#34D399',
          cyan: '#06B6D4',
          'cyan-light': '#22D3EE',
          rose: '#F43F5E',
          amber: '#F59E0B',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive) / <alpha-value>)',
          foreground: 'hsl(var(--destructive-foreground) / <alpha-value>)',
        },
        border: 'hsl(var(--border) / <alpha-value>)',
        input: 'hsl(var(--input) / <alpha-value>)',
        ring: 'hsl(var(--ring) / <alpha-value>)',

        brand: {
          purple: 'rgb(var(--brand-primary) / <alpha-value>)',
          'purple-light': '#8B5CF6',
          'purple-lighter': '#A78BFA',
          'purple-dark': '#5B21B6',
          'purple-deep': '#4C1D95',
          navy: 'rgb(var(--brand-secondary) / <alpha-value>)',
          'navy-mid': '#12122A',
          'navy-light': '#1E1E3A',
          'navy-soft': '#2A2A4A',
        },
        neutral: {
          50: '#FAFAFA',
          100: '#F5F5F7',
          200: '#E5E5EA',
          300: '#D1D1D6',
          400: '#A1A1AA',
          500: '#71717A',
          600: '#52525B',
          700: '#3F3F46',
          800: '#27272A',
          900: '#18181B',
          950: '#09090B',
        },
      },
      fontFamily: {
        sans: ['var(--font-body)', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['var(--font-headings)', 'system-ui', 'sans-serif'],
        nav: ['var(--font-nav)', 'system-ui', 'sans-serif'],
        btn: ['var(--font-btn)', 'system-ui', 'sans-serif'],
        calcTitle: ['var(--font-calc-title)', 'system-ui', 'sans-serif'],
        calcResult: ['var(--font-calc-result)', 'system-ui', 'sans-serif'],
        admin: ['var(--font-admin)', 'system-ui', 'sans-serif'],
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'xl-lg': '0.875rem',
        '2xl-lg': '1.25rem',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0, 0, 0, 0.04), 0 1px 2px rgba(0, 0, 0, 0.02)',
        'card-hover': '0 8px 24px rgba(0, 0, 0, 0.06), 0 2px 8px rgba(0, 0, 0, 0.03)',
        'elevated': '0 12px 40px rgba(0, 0, 0, 0.08), 0 4px 12px rgba(0, 0, 0, 0.04)',
        'premium': '0 2px 8px rgba(0, 0, 0, 0.03), 0 12px 32px rgba(0, 0, 0, 0.05)',
        'premium-lg': '0 4px 12px rgba(0, 0, 0, 0.04), 0 24px 64px rgba(0, 0, 0, 0.08)',
        'glow': '0 0 0 1px rgb(var(--brand-primary) / 0.08), 0 8px 32px rgb(var(--brand-primary) / 0.06)',
        'glow-purple': '0 0 0 1px rgb(var(--brand-primary) / 0.1), 0 8px 32px rgb(var(--brand-primary) / 0.1)',
        'inner-glow': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)',
        'dark-card': '0 1px 3px rgba(0, 0, 0, 0.3), 0 1px 2px rgba(0, 0, 0, 0.2)',
        'dark-card-hover': '0 8px 32px rgba(0, 0, 0, 0.4), 0 2px 8px rgba(0, 0, 0, 0.3)',
      },
      animation: {
        'animate-in': 'animate-in 0.15s ease-out',
        'animate-out': 'animate-out 0.15s ease-out',
        'fade-in': 'fade-in 0.5s ease-out both',
        'fade-out': 'fade-out 0.15s ease-out both',
        'fade-in-0': 'fade-in-0 0.15s ease-out both',
        'fade-out-0': 'fade-out-0 0.15s ease-out both',
        'zoom-in-95': 'zoom-in-95 0.15s ease-out both',
        'zoom-out-95': 'zoom-out-95 0.15s ease-out both',
        'fade-in-up': 'fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) both',
        'fade-in-down': 'fade-in-down 0.6s cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in': 'scale-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
        'shimmer': 'shimmer 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'float-smooth': 'float-smooth 8s ease-in-out infinite',
        'mesh-shift': 'mesh-shift 12s ease-in-out infinite',
        'pulse-ring': 'pulse-ring 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'gradient-pulse': 'gradient-pulse 4s ease-in-out infinite',
        'slide-in-right': 'slide-in-right 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
      },
      keyframes: {
        'animate-in': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'animate-out': {
          from: { opacity: '1', transform: 'translateY(0)' },
          to: { opacity: '0', transform: 'translateY(4px)' },
        },
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'fade-out': { '0%': { opacity: '1' }, '100%': { opacity: '0' } },
        'fade-in-0': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-out-0': { from: { opacity: '1' }, to: { opacity: '0' } },
        'zoom-in-95': { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'zoom-out-95': { from: { opacity: '1', transform: 'scale(1)' }, to: { opacity: '0', transform: 'scale(0.95)' } },
        'fade-in-up': { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-in-down': { '0%': { opacity: '0', transform: 'translateY(-12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'scale-in': { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'shimmer': { '0%, 100%': { opacity: '0.5' }, '50%': { opacity: '1' } },
        'float': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        'float-smooth': { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '33%': { transform: 'translateY(-10px) rotate(0.5deg)' }, '66%': { transform: 'translateY(-5px) rotate(-0.5deg)' } },
        'mesh-shift': { '0%, 100%': { 'background-position': '0% 0%' }, '25%': { 'background-position': '100% 50%' }, '50%': { 'background-position': '50% 100%' }, '75%': { 'background-position': '0% 50%' } },
        'pulse-ring': { '0%': { 'box-shadow': '0 0 0 0 rgb(var(--brand-primary) / 0.3)' }, '70%': { 'box-shadow': '0 0 0 12px rgb(var(--brand-primary) / 0)' }, '100%': { 'box-shadow': '0 0 0 0 rgb(var(--brand-primary) / 0)' } },
        'gradient-pulse': { '0%, 100%': { opacity: '0.3' }, '50%': { opacity: '0.6' } },
        'slide-in-right': { 'from': { opacity: '0', transform: 'translateX(100%)' }, 'to': { opacity: '1', transform: 'translateX(0)' } },
      },
      backgroundImage: {
        'mesh-purple': 'radial-gradient(at 20% 20%, rgb(var(--brand-primary) / 0.15) 0px, transparent 50%), radial-gradient(at 80% 80%, rgb(var(--brand-primary) / 0.1) 0px, transparent 50%)',
      },
    },
  },
  plugins: [],
};
