import LegalLayout from '@/components/legal/LegalLayout';

export default function AiDisclaimer() {
  return (
    <LegalLayout
      slug="ai-disclaimer"
      title="AI Disclaimer"
      updated="2026-07-27"
      intro={
        <p>
          The FRELUX PAINT CALC Smart Color Assistant provides color suggestions generated by an artificial intelligence
          service. Please read this disclaimer carefully before using the feature.
        </p>
      }
      sections={[
        {
          heading: 'Not professional advice',
          body: (
            <p>
              AI recommendations are suggestions for inspiration only. They are not professional interior design,
              architectural, construction, structural, electrical, or safety advice. Always consult a qualified professional
              for decisions that affect the structure, safety, or compliance of your property.
            </p>
          ),
        },
        {
          heading: 'Accuracy and suitability',
          body: (
            <p>
              AI color suggestions may be imperfect, incomplete, or unsuitable for your specific space. Colors
              appear differently depending on lighting, surface texture, screen calibration, and surrounding decor. Always
              test a physical paint sample on your wall before making a final decision.
            </p>
          ),
        },
        {
          heading: 'How your data is used',
          body: (
            <p>
              When you use the Smart Color Assistant, your text description and any uploaded image are sent to our secure
              backend and then to a third-party AI provider (Google AI) to generate recommendations. Image data is used only
              to produce your recommendation and is not stored long-term. We do not store your full description or image in
              our analytics, only anonymous event counts (for example, that a text consultation was submitted).
            </p>
          ),
        },
        {
          heading: 'Usage limits',
          body: (
            <p>
              To keep the service available to everyone, we limit the number of AI requests you can make within a given
              time window. If you reach the limit, please try again later.
            </p>
          ),
        },
        {
          heading: 'Color codes',
          body: (
            <p>
              Where the AI provides hexadecimal color codes, we validate them before displaying. Invalid or malformed color
              values are replaced with a safe fallback so the app remains usable. Always confirm the final color with a
              physical sample.
            </p>
          ),
        },
      ]}
    />
  );
}
