// ============================================================
// ARCHIE SCHEDULED MAINTENANCE (gap audit F-1, 2026-09-16)
// ============================================================
// ARCHIE's consolidation (C-3) only fired when an engine
// instance booted with traffic, and saved cognitive traces
// were never re-examined as learning material (C-2). This
// endpoint is the background heartbeat the pg_cron scheduler
// invokes — it is NEVER callable by users:
//
//   1. AUTH: a per-installation random token, generated by
//      the scheduler migration, stored in
//      archie_scheduler_tokens, and compared IN THE DATABASE
//      (the value never travels in code). No token, no run —
//      and a security event records the attempt.
//   2. consolidate: hydrates the native engine with
//      persistence — the same hydrate path chat uses — which
//      runs the system-wide, hour-gated consolidateIfDue.
//      Nothing new is invented; this is the identical pass
//      that used to need traffic.
//   3. reflect: reads cognitive traces since the last
//      watermark, selects the WEAK ones (epistemic not
//      VERIFIED, or confidence < 0.5), and records honest
//      FAILURE outcomes for them — kind "failure",
//      contributing [] (citing is not credit, and a weak
//      trace names no contributing facts — no false
//      reinforcement is possible). These outcomes hydrate
//      into every isolate's learner: they are the honest
//      "what did I get wrong" material the IMPROVE phase
//      and diagnostics consume.
//   4. Every run appends an archie_scheduler_runs row —
//      the scheduler is observable, not a black box.
//
// Deno Deploy target: supabase/functions/archie-maintenance.
// Deployed with --no-verify-jwt (like all archie-* functions);
// the token header is the gate, the anon key grants nothing.
// ============================================================

import { createClient } from "npm:@supabase/supabase-js@2.45.4";
import { serveWithCors } from "../_shared/serve.ts";
import {
  configureNativeEnginePersistence,
  getNativeEngine,
} from "../_shared/archie-ai/native-engine/engine.ts";
import type { SupabaseLike } from "../_shared/archie-ai/native-engine/persistence.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const service = createClient(SUPABASE_URL, SERVICE_ROLE);

const REFLECTION_WATERMARK_KEY = "reflection_watermark";
const WEAK_CONFIDENCE_FLOOR = 0.5;
const REFLECT_BATCH_LIMIT = 100;

type Mode = "consolidate" | "reflect" | "all";

function json(status: number, body: Record<string, unknown>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

/** Deterministic cause taxonomy for weak traces —
 *  classification by recorded evidence, never generated. */
function causeOf(trace: { epistemic: string; confidence: number }): string {
  if (trace.epistemic === "REFUSED" || trace.confidence <= 0.1) {
    return "refused-or-unanswerable";
  }
  if (trace.epistemic === "UNKNOWN" || trace.epistemic === "PARTIAL") {
    return "unverified-knowledge";
  }
  if (trace.confidence < WEAK_CONFIDENCE_FLOOR) {
    return "low-confidence-answer";
  }
  return "weak-trace";
}

async function requireSchedulerToken(req: Request): Promise<boolean> {
  const token = req.headers.get("x-maintenance-token") ?? "";
  if (token.length < 32) return false; // generated tokens are 64 hex
  const { data } = await service
    .from("archie_scheduler_tokens")
    .select("token")
    .eq("token", token)
    .maybeSingle();
  return Boolean(data);
}

async function logRun(mode: string, ok: boolean, note: string): Promise<void> {
  try {
    await service.from("archie_scheduler_runs").insert([
      {
        mode,
        ok,
        note: note.slice(0, 500),
      },
    ]);
  } catch {
    // The run already happened — logging is best-effort and
    // never changes the reported result.
  }
}

/** C-3: the hour-gated, system-wide consolidation pass. */
async function runConsolidate(): Promise<Record<string, unknown>> {
  configureNativeEnginePersistence(service as unknown as SupabaseLike);
  const engine = getNativeEngine();
  const diagnostics = engine.diagnostics();
  const { data: counters } = await service
    .from("frelux_archie_engine_counters")
    .select("key, value")
    .in("key", ["last_consolidation_ts", "cycles"]);
  return {
    engine_operational: engine.isOperational(),
    capabilities: diagnostics.capabilities?.length ?? 0,
    counters: counters ?? [],
    note: "native engine hydrated with persistence — the hour-gated consolidation pass runs inside hydrate (identical to chat-path behavior)",
  };
}

/** C-2: honest reflection over weak traces. */
async function runReflect(): Promise<Record<string, unknown>> {
  // 1. Watermark: reflect each trace at most once, ever.
  const { data: stateRow } = await service
    .from("archie_scheduler_state")
    .select("value")
    .eq("key", REFLECTION_WATERMARK_KEY)
    .maybeSingle();
  const watermark =
    (stateRow?.value as { ts?: string } | null)?.ts ?? "1970-01-01T00:00:00Z";

  // 2. Weak traces since the watermark — the recorded evidence.
  const { data: traces, error } = await service
    .from("frelux_archie_cognitive_traces")
    .select("id, task, epistemic, confidence, created_at")
    .gt("created_at", watermark)
    .limit(REFLECT_BATCH_LIMIT);
  if (error) {
    return { reflected: 0, note: `trace read failed: ${error.message}` };
  }
  const weak = (traces ?? []).filter(
    (t: { epistemic: string; confidence: number }) =>
      t.epistemic !== "VERIFIED" || t.confidence < WEAK_CONFIDENCE_FLOOR,
  );

  // 3. Record honest failure outcomes. contributing is ALWAYS
  //    []: a weak trace credits no knowledge — citing is not
  //    credit, so no false reinforcement is even possible.
  const causes: Record<string, number> = {};
  if (weak.length > 0) {
    const rows = weak.map(
      (t: {
        id: string;
        task: string;
        epistemic: string;
        confidence: number;
      }) => {
        const cause = causeOf(t);
        causes[cause] = (causes[cause] ?? 0) + 1;
        return {
          id: `reflection-${t.id}`,
          kind: "failure",
          task: `reflection: ${t.task.slice(0, 200)}`,
          contributing: [],
          timestamp: new Date().toISOString(),
        };
      },
    );
    // Idempotent per trace id (primary key): a re-reflected
    // batch cannot double-count (insert or ignore duplicates).
    const { error: insertErr } = await service
      .from("frelux_archie_native_outcomes")
      .upsert(rows, { onConflict: "id", ignoreDuplicates: true });
    if (insertErr) {
      return {
        reflected: 0,
        causes,
        note: `outcome write failed: ${insertErr.message}`,
      };
    }
  }

  // 4. Advance the watermark to the newest trace examined —
  //    only when the batch was fully processed.
  const newest = (traces ?? []).reduce<string>(
    (max, t: { created_at: string }) =>
      t.created_at > max ? t.created_at : max,
    watermark,
  );
  if (newest > watermark) {
    await service
      .from("archie_scheduler_state")
      .upsert([{ key: REFLECTION_WATERMARK_KEY, value: { ts: newest } }], {
        onConflict: "key",
      });
  }

  return {
    traces_in_window: (traces ?? []).length,
    weak_traces: weak.length,
    reflected: weak.length,
    causes,
    watermark_before: watermark,
    watermark_after: newest,
  };
}

serveWithCors(async (req: Request) => {
  if (req.method !== "POST") {
    return json(405, { error: "POST only." });
  }
  const allowed = await requireSchedulerToken(req);
  if (!allowed) {
    // user_id on frelux_security_events is NOT NULL and there
    // is no user on a scheduler call — the honest record is a
    // scheduler run row, not a fabricated security event.
    await logRun(
      "gate-stop",
      false,
      "call without a valid scheduler token — refused",
    );
    return json(401, { error: "Valid scheduler token required." });
  }

  let body: { mode?: string };
  try {
    body = await req.json();
  } catch {
    return json(400, { error: "Body must be JSON." });
  }
  const mode = (body.mode ?? "all") as Mode;
  if (!["consolidate", "reflect", "all"].includes(mode)) {
    return json(400, { error: `Unknown mode: ${mode}` });
  }

  const result: Record<string, unknown> = { mode };
  let ok = true;
  try {
    if (mode === "consolidate" || mode === "all") {
      result.consolidate = await runConsolidate();
    }
    if (mode === "reflect" || mode === "all") {
      result.reflect = await runReflect();
    }
  } catch (err) {
    ok = false;
    result.error = `maintenance pass failed honestly: ${(err as Error).message}`;
  }
  await logRun(mode, ok, JSON.stringify(result).slice(0, 500));
  return json(ok ? 200 : 500, { ok, ...result });
});
