// =========================================================
// ARCHIE CONVERSATIONAL ENGLISH EXPANSION CORPUS
//
// Versioned conversational training data for the native
// NLU intent classifier. The corpus is DATA, never code:
// every example teaches the underlying PATTERN of a
// conversational exchange so the trained Naive Bayes
// classifier can GENERALIZE to unseen variations. No
// response is hardcoded against any example.
//
// CONSTRAINTS (enforced by conversational-expansion.test.ts):
//   * no hyphens in any example sentence (owner directive)
//   * no duplicate utterance inside this corpus or against
//     the base NLU corpus (duplicates bias the classifier)
//   * no held-out phrase appears verbatim in training data
//     (memorization is not generalization)
//   * every intent in this corpus is handled honestly by
//     the engine's conversational route (no fake responses)
//
// Integration (owner directive, 2026-09-11):
//   * nlu.ts concatenates CONVERSATION_CORPUS into CORPUS
//     at train time, so all surfaces (ARCHIE Core, chat,
//     Studio, WhatsApp) learn the same patterns
//   * conversational outcomes flow through the existing
//     learning pipeline: politeness and social exchange are
//     ACKNOWLEDGEMENT, never verification evidence. User
//     feedback never becomes truth automatically
//   * emoji understanding lives in emoji.ts; this corpus
//     includes emoji enhanced examples so the classifier
//     is robust to emoji decorated messages, while pure
//     emoji messages route deterministically by tone
// =========================================================

import type { Intent } from "./nlu.ts";

/** Bumped when the conversational corpus changes so
 *  deployments can detect stale training data. */
export const CONVERSATION_CORPUS_VERSION = 2;

// ---------------------------------------------------------
// TRAINING CORPUS
//
// Categories covered (owner directive list, mapped onto
// classifier intents): greetings, introductions, good
// morning afternoon evening, goodbye good night, how are
// you conversations, names and identity, what ARCHIE is,
// what ARCHIE can do, asking for help, offering help,
// thanking, apologizing, acknowledging, confirming,
// agreeing, disagreeing politely, yes and no responses,
// okay and alright, please and you are welcome, excitement,
// happiness, sadness, frustration, confusion, surprise,
// encouragement, congratulations, celebrations, good
// wishes, small talk, weather conversation, time and date
// conversation, daily activities, simple questions,
// clarification requests, requests for repetition,
// requests for explanation, uncertainty, i do not know
// situations, i understand situations, i do not understand
// situations, waiting, starting a task, finishing a task,
// checking availability, asking what ARCHIE is doing,
// conversational follow ups, polite interruptions,
// corrections, user feedback positive and negative, casual
// conversation, natural variations, Nigerian English,
// international English, contractions, short messages,
// incomplete messages, informal spelling, repeated words,
// simple emoji usage.
// ---------------------------------------------------------
export const CONVERSATION_CORPUS: Array<[Intent, string[]]> = [
  [
    "greeting",
    [
      // greetings, time of day greetings, how are you
      "hi",
      "hello",
      "hey",
      "heyyy",
      "hello there archie",
      "hey archie, good to see you",
      "good morning to you",
      "good afternoon to you",
      "good evening to you",
      "morning",
      "afternoon",
      "evening archie, how far",
      "how far archie",
      "wetin dey happen",
      "how body",
      "how body, i hope you dey kampe",
      "hola archie",
      "bonjour",
      "yo yo yo",
      "sup",
      "hey buddy",
      "hello friend",
      "hi, is this a good time",
      "good day archie",
      "greetings my good friend",
      "hi archie, how you dey",
      "how you dey",
      "how now",
      "hey there, how is everything",
      "hello, hope your day is going well",
      "hi, long time",
      "how have you been lately",
      "how is everything with you",
      "how is life archie",
      "hope you are good",
      "i hope you are doing fine",
      "you good?",
      "all good over there?",
      "hey, how you doing today",
      "archie, how far na",
      "oya, good morning",
      "good morning my friend 😊",
      "hi archie 😊",
      "hey archie 😄",
      "top of the morning to you",
      "how are you archie",
      "how are you doing my friend",
      "hey hey hey",
      "hello again",
      "hi again archie",
      "we meet again",
      "greetings and good wishes to you",
      "hey, i just came to say hi",
      "just checking in on you",
      "wetin dey happen for your side",
      "howdy partner",
      "hi, you are the first person i talk to today",
      "good morning ☀️",
      "wat of today my guy",
      "how is everything with you today",
    ],
  ],
  [
    "farewell",
    [
      // goodbye, good night, parting good wishes
      "bye",
      "goodbye",
      "bye bye",
      "see you",
      "see ya",
      "talk to you later",
      "see you later archie",
      "see you tomorrow",
      "good night archie",
      "goodnight archie",
      "good night, sleep well",
      "sweet dreams",
      "have a good night",
      "im off now",
      "im leaving now, bye",
      "i dey go",
      "i dey go now, later",
      "we go talk later",
      "make we talk later",
      "safe journey, see you when i return",
      "have a nice day archie",
      "have a great day",
      "have a good one",
      "have a lovely evening",
      "enjoy your day",
      "im done for now",
      "thats all for now archie",
      "out for now, bye",
      "im logging off",
      "im shutting down for today",
      "let me run, talk later",
      "i will be back",
      "i will catch you later",
      "gone for the day",
      "bye for now, take care",
      "take care of yourself archie",
      "goodbye and thank you",
      "later",
      "good night, talk tomorrow 🌙",
      "goodbye and thanks for everything",
      "i appreciate you, goodbye for now",
      "thats all for now, cheers",
    ],
  ],
  [
    "gratitude",
    [
      // thanking, praise, encouragement toward ARCHIE,
      // positive user feedback
      "thanks",
      "thank you archie",
      "thank you very much",
      "thanks a lot archie",
      "thanks a million",
      "many thanks",
      "much appreciated",
      "i appreciate you",
      "i appreciate your help",
      "grateful for you archie",
      "you are a lifesaver",
      "you are amazing",
      "you are too much",
      "you do too much",
      "god bless you",
      "bless you archie",
      "well done o",
      "well done archie, keep it up",
      "keep it up",
      "keep doing what you are doing",
      "you are doing well",
      "you are doing great work",
      "good work",
      "fine job",
      "splendid work",
      "im impressed",
      "im really impressed archie",
      "bravo",
      "kudos to you",
      "hats off to you",
      "you nailed it",
      "nailed it",
      "correct guy",
      "you sabi well well",
      "sharp sharp, well done",
      "thumbs up to you",
      "big thanks",
      "thanks a bunch",
      "tanx bro",
      "tanx so much",
      "thanks archie 🙏",
      "thank you so very much 🙏",
      "great job 👍",
      "youre the best ❤️",
      "youre one in a million",
      "archie you too much, thank you",
      "this is great",
      "this is amazing",
      "this is awesome",
      "that was a great answer",
      "cheers!",
      "your help means a lot to me",
      "i appreciate what you did",
      "grateful for your assistance always",
      "what you did means so much to me",
      "thank you for your service",
      "your support means the world to me",
    ],
  ],
  [
    "identity_query",
    [
      // what ARCHIE is, who is behind it
      "hi, who are you again",
      "remind me who you are",
      "what exactly are you",
      "are you the archie assistant",
      "you are archie right",
      "so what are you called",
      "what do i call you",
      "is your name archie",
      "your name is archie right",
      "what should i know about you",
      "tell me who you are again",
      "are you the one they call archie",
      "na who you be",
      "abeg, who you be",
      "introduce yourself again",
    ],
  ],
  [
    "capability_query",
    [
      // what ARCHIE can do
      "what can you do for me today",
      "what are you good at",
      "what do you know how to do",
      "list what you can do for me",
      "what are your skills",
      "wetin you sabi do",
      "wetin you fit do",
      "is there something you can do for me now",
      "what services can you render",
      "what works can you handle for me",
      "tell me about your powers",
    ],
  ],
  [
    "system_status",
    [
      // checking engine health conversationally
      "how are your systems today",
      "is your engine running fine",
      "everything good on your side",
      "any system problems today",
      "are you fully functional",
      "how is your brain today",
      "are you strong today",
      "status check please",
    ],
  ],
  [
    "teaching",
    [
      // introductions, names and identity of the user
      "my name is andrew",
      "i am andrew",
      "my friends call me andy",
      "you can call me andy",
      "call me tunde",
      "i go by the name ada",
      "i am ada from lagos",
      "this is chidi speaking",
      "remember my name is amaka",
      "my full name is ngozi okonkwo",
      "i am a civil engineer",
      "i am a site engineer at gcon",
      "i work as a quantity surveyor",
      "i run a small construction firm",
      "i am a contractor in abuja",
      "remember that i am the owner",
      "i am the owner of this system",
      "my company name is tubin constructions",
      "i am from port harcourt",
      "i live in yaba, lagos",
      "i am 34 years old",
      "i speak english and yoruba",
      "i prefer to be called boss",
      "my nickname is oga at the top",
      "i am a family man with two kids",
    ],
  ],
  [
    "correction",
    [
      // negative user feedback, corrections
      "that answer was not helpful",
      "that is not what i asked for",
      "you are wrong there",
      "wrong answer",
      "no, try again",
      "thats off point",
      "you missed it",
      "not correct archie",
      "that does not answer my question",
      "that is not accurate at all",
      "hmm, that is not right",
      "no o, that is wrong",
      "that one no correct",
      "wetin you talk no correct",
      "i am not happy with that answer",
      "that is not right to me",
      "e no correct",
    ],
  ],
  [
    "help_request",
    [
      // asking for help, please and you are welcome flows
      "can you help me",
      "can you help me please",
      "please help me",
      "please i need help",
      "i need your help",
      "i need your help please",
      "help me please archie",
      "help me out",
      "i need a favor from you",
      "do me a favor",
      "abeg help me",
      "abeg i need your help",
      "i beg you, help me",
      "assist me please",
      "kindly assist",
      "can you assist me with something",
      "i could use your help now",
      "i could use some help",
      "i need a hand",
      "give me a hand",
      "lend a hand please",
      "sos, i need help",
      "emergency, help me",
      "i am stuck, help me",
      "i dont know what to do, help me",
      "any chance you can help",
      "will you help me with something",
      "would you help me out",
      "i require your assistance",
      "wetin i suppose do",
      "abeg assist me small",
      "please help me figure this out",
      "assist me with this problem please",
      "i need a hand with this",
      "please walk me through it",
    ],
  ],
  [
    "apology",
    [
      // apologizing, polite interruptions
      "sorry",
      "im sorry",
      "i am sorry",
      "i am so sorry",
      "sorry archie",
      "my bad",
      "my mistake",
      "my apologies",
      "i apologize",
      "please forgive me",
      "forgive me archie",
      "pardon me",
      "excuse my manners",
      "sorry about that",
      "sorry for the delay",
      "sorry for disturbing you",
      "sorry to bother you",
      "sorry to interrupt",
      "no vex",
      "abeg no vex",
      "i didnt mean that, sorry",
      "that was my fault, sorry",
      "oops, my bad",
      "my fault entirely",
      "sorry, i forgot",
      "pardon the interruption",
      "forgive my late reply",
      "soory about that",
      "soory my mistake",
      "pardon me for disturbing you",
      "forgive the disturbance please",
    ],
  ],
  [
    "acknowledgment",
    [
      // okay and alright, got it, i understand, confirming,
      // uncertainty, i do not know situations, waiting,
      // conversational follow ups
      "okay",
      "ok",
      "okey",
      "alright",
      "alright then",
      "ight",
      "aiit",
      "aiight",
      "got it",
      "gotcha",
      "noted",
      "understood",
      "i understand",
      "i understand now",
      "clear",
      "crystal clear",
      "makes sense",
      "that makes sense",
      "sounds good",
      "sounds fine",
      "fine",
      "fine by me",
      "very well",
      "very good",
      "roger that",
      "roger",
      "copy that",
      "affirmative",
      "word",
      "cool",
      "cool cool",
      "nice",
      "great",
      "perfect",
      "perfect, lets do it",
      "good to know",
      "i hear you",
      "i get it",
      "i get it now",
      "i see",
      "i see what you mean",
      "fair enough",
      "indeed",
      "true",
      "right",
      "point taken",
      "take your time",
      "no rush",
      "take it easy",
      "go on",
      "continue",
      "keep going",
      "carry on",
      "go ahead",
      "proceed",
      "okay noted 👍",
      "alright 👌",
      "okay 👍",
      "got it, understood",
      "i do not know",
      "i dont know",
      "i have no idea",
      "beats me",
      "your guess is as good as mine",
      "i am not sure",
      "honestly i dont know",
      "no idea at all",
      "message received and understood",
      "i get the picture now",
      "i follow you completely",
      "crystal clear to me now",
      "good to know about that",
    ],
  ],
  [
    "agreement",
    [
      // agreeing, yes responses, confirming
      "yes",
      "yeah",
      "yep",
      "yup",
      "ya",
      "yes yes",
      "yes of course",
      "of course",
      "sure",
      "sure thing",
      "absolutely",
      "definitely",
      "certainly",
      "exactly",
      "correct",
      "right on",
      "well said",
      "i agree",
      "i agree with you",
      "agreed",
      "you are right",
      "you are absolutely right",
      "thats right",
      "that is right",
      "thats correct",
      "that is exactly it",
      "no wahala",
      "no problem at all",
      "no problem",
      "true talk",
      "you talk true",
      "sharp",
      "na so",
      "i buy that idea",
      "deal",
      "yes 👍",
    ],
  ],
  [
    "disagreement",
    [
      // disagreeing politely, no responses
      "no",
      "nah",
      "nope",
      "not really",
      "not quite",
      "i disagree",
      "i do not agree",
      "i dont agree with that",
      "i beg to differ",
      "i think otherwise",
      "i do not think so",
      "i dont think so",
      "thats not it",
      "i am not sure about that",
      "i see it differently",
      "we do not see it the same way",
      "fair point but i disagree",
      "hmm, i do not buy that",
      "i no gree",
      "i no buy that idea",
      "no o, i no gree",
      "i have to disagree there",
      "that is debatable",
      "not entirely",
      "not exactly",
      "i do not agree with that view",
      "i cannot accept that view",
      "my opinion differs on this matter",
      "i beg to differ on this one",
      "that position i cannot accept",
    ],
  ],
  [
    "emotional_expression",
    [
      // excitement, happiness, sadness, frustration,
      // confusion, surprise, tiredness
      "i am excited",
      "i am so excited",
      "im excited about today",
      "i cant wait",
      "i can not wait for tomorrow",
      "this is exciting",
      "wow this is exciting",
      "finally!",
      "yes! at last",
      "omg yes",
      "yay",
      "yayy",
      "hurray",
      "wheew, this is exciting",
      "i am happy",
      "i am happy today",
      "im so happy right now",
      "i feel great",
      "i feel good today",
      "today is a good day",
      "i am in a good mood",
      "life is good",
      "im delighted",
      "i am over the moon",
      "this made my day 😊",
      "i am sad",
      "im feeling down",
      "i feel sad today",
      "i am not happy at all",
      "im heartbroken",
      "today is a bad day",
      "im having a rough day",
      "i feel low",
      "i feel like crying 😢",
      "im so sad right now 😭",
      "i am frustrated",
      "im frustrated right now",
      "this is frustrating",
      "this is so annoying",
      "i am tired of this problem",
      "im angry right now",
      "i am not happy with this",
      "so annoying!",
      "ugh",
      "argh",
      "im stressed out",
      "im stressed today",
      "wahala dey",
      "this thing dey pain me",
      "this is terrible",
      "i am confused",
      "im confused right now",
      "i am lost",
      "im puzzled",
      "this is confusing",
      "everything is so confusing today",
      "my head is spinning",
      "wow",
      "really?",
      "no way",
      "youre kidding",
      "are you serious",
      "thats surprising",
      "omg",
      "what?!",
      "thats shocking 😮",
      "im surprised",
      "i am tired",
      "im tired today",
      "i am exhausted",
      "im worn out",
      "i need rest 😴",
      "im sleepy",
      "i want to sleep",
      "im so tired 😴",
      "chai, this thing sweet no be small",
      "wahala plenty today, i no lie",
      "this wahala too much for me",
      "wahala wan finish me today",
      "chai i am so tired today",
      "my heart is full today",
      "from the bottom of my heart i am happy",
      "i am overjoyed today",
    ],
  ],
  [
    "celebration",
    [
      // congratulations, celebrations, good wishes,
      // finishing a task wins
      "congratulations",
      "congrats",
      "congrats archie",
      "congratulations to you",
      "well done, congrats",
      "i got the job",
      "i got the contract",
      "we won the contract",
      "we won!",
      "we did it!",
      "i passed my exam",
      "i passed the test!",
      "my project was approved",
      "the client approved the design",
      "i graduated today",
      "its my birthday",
      "today is my birthday",
      "happy birthday to me",
      "happy new year archie",
      "happy new month",
      "merry christmas",
      "happy easter",
      "happy independence day",
      "happy sunday archie",
      "i am getting married",
      "my wife just put to bed",
      "we welcome a new baby",
      "i bought a new car",
      "we moved into our new house",
      "promotion! i got promoted today",
      "we nailed the presentation 🎉",
      "congrats to us 🎉",
      "lets celebrate 🎉",
      "i just finished the project, we completed it",
      "job done and dusted today",
    ],
  ],
  [
    "social_talk",
    [
      // small talk, weather conversation, daily activities,
      // offering help, starting a task, casual conversation
      "the rain is heavy today",
      "it is raining here",
      "raining cats and dogs here",
      "the sun is hot today",
      "today is very hot",
      "the weather is nice today",
      "harmattan is here",
      "harmattan season don start",
      "it is so cold this morning",
      "clouds are gathering, rain is coming",
      "how is the weather on your side",
      "the skies are clear today",
      "the skies look grey over here today",
      "rain spoiled my site work today",
      "i just got back from site",
      "i am on my way to work",
      "im heading to the site now",
      "i just woke up",
      "i just finished eating",
      "i am about to start cooking",
      "i am starting the job now",
      "work has been busy today",
      "today was hectic",
      "i did a lot of work today",
      "site work has kept me busy",
      "traffic was crazy today",
      "lagos traffic held me up today",
      "can i help you with anything",
      "do you need my help",
      "is there anything i can do for you",
      "tell me about your day",
      "how was your day today",
      "life in lagos is not easy",
      "i love this country despite everything",
      "do you like your job",
      "you seem quiet today",
      "i am just here passing time",
      "nothing much, just vibing",
      "just chilling with my phone",
      "its been a long week",
      "weekend is finally here",
      "today is friday, we move 🚀",
      "lets go 🚀",
      "i dey kampe",
      "small small, we dey manage",
      "e go better",
      "no be small thing",
      "can i help you with anything today",
      "how may i be of assistance to you",
      "shall i help you with something",
    ],
  ],
  [
    "time_query",
    [
      // time and date conversation
      "what time is it",
      "what is the time now",
      "what time do we have",
      "whats todays date",
      "what is todays date",
      "what day is it today",
      "what day of the week is it",
      "what month are we in",
      "what year is this",
      "what is the date today",
      "time check please",
      "abeg, whats the time",
      "wat time do we close today",
      "wetin be the time for break",
      "you sabi the time for the meeting",
      "what time of day is it now",
    ],
  ],
  [
    "availability_check",
    [
      // checking whether ARCHIE is available
      "are you there",
      "are you there archie",
      "are you with me",
      "archie are you there",
      "hello, anyone there",
      "is anyone there",
      "anybody home",
      "anybody there",
      "are you around",
      "you around archie",
      "are you available",
      "are you online",
      "archie, are you awake",
      "are you listening",
      "you dey there?",
      "shey you dey there",
      "archie you dey?",
      "are you still with me",
      "are you still there",
      "can you hear me",
      "is this thing on",
      "ping",
      "you dey hear me so",
      "shey you dey follow my talk",
      "abeg you dey around",
      "i hope say you dey active",
      "my guy you dey there",
      "abeg make sure you dey about, i need you",
    ],
  ],
  [
    "activity_query",
    [
      // asking ARCHIE what it is doing
      "what are you doing",
      "what are you doing now",
      "what are you up to",
      "whats up with you",
      "what have you been doing",
      "what are you working on",
      "are you busy",
      "are you doing anything now",
      "what do you do all day",
      "wetin you dey do",
      "how is work on your side",
      "are you idle",
      "what were you doing before i came",
      "busy or free?",
    ],
  ],
  [
    "clarification_request",
    [
      // clarification requests, requests for repetition,
      // requests for explanation, i do not understand
      // situations
      "what do you mean",
      "what do you mean by that",
      "what does that mean",
      "what does that even mean",
      "i do not understand",
      "i dont understand",
      "i dont get it",
      "i do not get you",
      "i do not get you at all",
      "i am lost here",
      "you lost me there",
      "can you clarify",
      "can you clarify that for me",
      "please clarify",
      "clarify that please",
      "can you explain more",
      "explain more please",
      "explain further",
      "explain that part again",
      "can you break it down",
      "break it down for me",
      "simplify that for me",
      "say it in simple english",
      "say that again",
      "say it again please",
      "repeat that please",
      "please repeat",
      "come again",
      "come again please",
      "pardon?",
      "sorry, what did you say",
      "sorry, what did you mean",
      "what was that again",
      "run that by me again",
      "go over that again",
      "wait, what?",
      "hold on, what do you mean",
      "abeg explain am again",
      "i dont understand wetin you talk",
      "which one do you mean",
      "i did not follow that",
      "sorry i did not follow you",
      "i could not follow that",
      "can you shed more light on that",
      "hmm?",
    ],
  ],
];

// ---------------------------------------------------------
// HELD-OUT EVALUATION SET
//
// NONE of these phrases appear in the training corpus
// (enforced by test). Every entry was written AFTER the
// training corpus was frozen, as unseen variations to
// measure GENERALIZATION, not memorization. Test types
// mirror the owner quality gate:
//   paraphrase  — same meaning, different words
//   short       — clipped forms and abbreviations
//   typo        — misspelled input
//   informal    — casual slang
//   structure   — unusual sentence structures
//   emoji       — emoji enhanced and emoji only messages
//   unknown     — ambiguous or off corpus input that must
//                  fall back to the honest knowledge or
//                  howto routes, never a fake social reply
//   multiturn   — evaluated with conversation history
// ---------------------------------------------------------
export type HeldOutType =
  | "paraphrase"
  | "short"
  | "typo"
  | "informal"
  | "structure"
  | "emoji"
  | "unknown"
  | "multiturn";

export interface HeldOutExample {
  input: string;
  /** Expected intent, or "FALLBACK" for unknown input
   *  (acceptable: knowledge_query, howto_guidance or
   *  teaching — the honest routes), or "ANY:a|b|c" when
   *  several intents are genuinely acceptable. */
  expect: string;
  type: HeldOutType;
  /** For multiturn entries: conversation history before the
   *  input (owner and archie turns). */
  history?: Array<{ role: "owner" | "archie"; text: string }>;
}

export const CONVERSATION_HELD_OUT: HeldOutExample[] = [
  // --- paraphrases: greetings and social entry ---
  { input: "well met, archie", expect: "ANY:greeting|availability_check", type: "paraphrase" },
  { input: "salutations my friend", expect: "greeting", type: "paraphrase" },
  { input: "hey, how is the family of systems treating you", expect: "ANY:greeting|system_status", type: "paraphrase" },
  { input: "wishing you a pleasant morning", expect: "greeting", type: "paraphrase" },
  { input: "sorry to disturb, are you around", expect: "availability_check", type: "paraphrase" },
  { input: "it is a beautiful evening, hello archie", expect: "ANY:greeting|social_talk", type: "paraphrase" },
  // --- paraphrases: parting ---
  { input: "i must be going now, farewell", expect: "farewell", type: "paraphrase" },
  { input: "time to retire for the night, good night", expect: "farewell", type: "paraphrase" },
  { input: "until tomorrow then", expect: "farewell", type: "paraphrase" },
  { input: "i wish you a pleasant rest of your day", expect: "farewell", type: "paraphrase" },
  // --- paraphrases: gratitude and praise ---
  { input: "you have my sincere gratitude", expect: "gratitude", type: "paraphrase" },
  { input: "archie, that was a fine piece of work", expect: "gratitude", type: "paraphrase" },
  { input: "i do not take your help for granted", expect: "ANY:gratitude|help_request", type: "paraphrase" },
  { input: "well and truly appreciated", expect: "gratitude", type: "paraphrase" },
  { input: "you continue to impress me", expect: "gratitude", type: "paraphrase" },
  // --- paraphrases: help, apology, clarification ---
  { input: "i require assistance with a matter", expect: "help_request", type: "paraphrase" },
  { input: "would you mind giving me a hand with something", expect: "help_request", type: "paraphrase" },
  { input: "do accept my sincere apologies", expect: "apology", type: "paraphrase" },
  { input: "i owe you an apology for that", expect: "apology", type: "paraphrase" },
  { input: "could you go over that once more", expect: "clarification_request", type: "paraphrase" },
  { input: "i am afraid i did not follow that", expect: "clarification_request", type: "paraphrase" },
  { input: "what exactly are you getting at", expect: "clarification_request", type: "paraphrase" },
  // --- paraphrases: agreement and disagreement ---
  { input: "that settles it, i am with you", expect: "agreement", type: "paraphrase" },
  { input: "on that point we are in accord", expect: "agreement", type: "paraphrase" },
  { input: "i cannot bring myself to agree", expect: "disagreement", type: "paraphrase" },
  { input: "with respect, i hold a different view", expect: "disagreement", type: "paraphrase" },
  { input: "that position is hard for me to accept", expect: "disagreement", type: "paraphrase" },
  // --- paraphrases: emotions ---
  { input: "my heart is full of joy today", expect: "emotional_expression", type: "paraphrase" },
  { input: "i am on top of the world", expect: "emotional_expression", type: "paraphrase" },
  { input: "today drained every bit of my energy", expect: "emotional_expression", type: "paraphrase" },
  { input: "i feel like the walls are closing in", expect: "emotional_expression", type: "paraphrase" },
  { input: "this whole thing has me wound up", expect: "emotional_expression", type: "paraphrase" },
  { input: "i never expected this at all", expect: "emotional_expression", type: "paraphrase" },
  { input: "words cannot describe how i feel right now", expect: "emotional_expression", type: "paraphrase" },
  // --- paraphrases: celebration and good wishes ---
  { input: "pop the champagne, the deal is signed", expect: "celebration", type: "paraphrase" },
  { input: "what a day, the university gave me admission", expect: "celebration", type: "paraphrase" },
  { input: "may the new year bring you plenty of work", expect: "ANY:celebration|farewell", type: "paraphrase" },
  { input: "a toast to the completed bridge", expect: "celebration", type: "paraphrase" },
  // --- paraphrases: availability, activity, time ---
  { input: "is the engine currently at my service", expect: "ANY:availability_check|system_status", type: "paraphrase" },
  { input: "what occupies you at the moment", expect: "activity_query", type: "paraphrase" },
  { input: "how goes it behind the scenes", expect: "activity_query", type: "paraphrase" },
  { input: "kindly tell me the hour", expect: "time_query", type: "paraphrase" },
  { input: "which day of the month have we reached", expect: "time_query", type: "paraphrase" },
  // --- paraphrases: social talk and weather ---
  { input: "the skies are clear over my area today", expect: "social_talk", type: "paraphrase" },
  { input: "it has been pouring since dawn here", expect: "social_talk", type: "paraphrase" },
  { input: "just got in from a long day of labor", expect: "social_talk", type: "paraphrase" },
  { input: "i was at the site all day", expect: "social_talk", type: "paraphrase" },
  { input: "shall i be of service to you today", expect: "social_talk", type: "paraphrase" },
  // --- short forms ---
  { input: "pls", expect: "help_request", type: "short" },
  { input: "pls help", expect: "help_request", type: "short" },
  { input: "hlp me", expect: "help_request", type: "short" },
  { input: "thx", expect: "gratitude", type: "short" },
  { input: "tnx", expect: "gratitude", type: "short" },
  { input: "ty", expect: "gratitude", type: "short" },
  { input: "okk", expect: "acknowledgment", type: "short" },
  { input: "k", expect: "acknowledgment", type: "short" },
  { input: "kk", expect: "acknowledgment", type: "short" },
  { input: "np", expect: "ANY:agreement|acknowledgment", type: "short" },
  { input: "gn", expect: "farewell", type: "short" },
  { input: "cu", expect: "farewell", type: "short" },
  { input: "brb", expect: "farewell", type: "short" },
  { input: "gtg", expect: "farewell", type: "short" },
  { input: "sry", expect: "apology", type: "short" },
  { input: "srsly?", expect: "emotional_expression", type: "short" },
  { input: "idk", expect: "acknowledgment", type: "short" },
  { input: "wym", expect: "clarification_request", type: "short" },
  { input: "wdym", expect: "clarification_request", type: "short" },
  { input: "sup?", expect: "greeting", type: "short" },
  { input: "yo", expect: "greeting", type: "short" },
  { input: "nite", expect: "farewell", type: "short" },
  { input: "tmrw then", expect: "farewell", type: "short" },
  // --- typos and informal spelling ---
  { input: "helo archie", expect: "greeting", type: "typo" },
  { input: "helo", expect: "greeting", type: "typo" },
  { input: "god morning to you", expect: "greeting", type: "typo" },
  { input: "goodnight archie, sleep tite", expect: "farewell", type: "typo" },
  { input: "tanx a lot", expect: "gratitude", type: "typo" },
  { input: "thank u very muchh", expect: "gratitude", type: "typo" },
  { input: "srry archie", expect: "apology", type: "typo" },
  { input: "soory for disturbing", expect: "apology", type: "typo" },
  { input: "plese help me", expect: "help_request", type: "typo" },
  { input: "i ned your help", expect: "help_request", type: "typo" },
  { input: "wat do you mean", expect: "clarification_request", type: "typo" },
  { input: "i dnt understand", expect: "clarification_request", type: "typo" },
  { input: "can you hear mee", expect: "availability_check", type: "typo" },
  { input: "are you theer", expect: "availability_check", type: "typo" },
  { input: "wat time is it", expect: "time_query", type: "typo" },
  { input: "wats todays date", expect: "time_query", type: "typo" },
  { input: "congartulations", expect: "celebration", type: "typo" },
  { input: "we wond the contract", expect: "celebration", type: "typo" },
  { input: "i am exausted", expect: "emotional_expression", type: "typo" },
  { input: "im so happpy today", expect: "emotional_expression", type: "typo" },
  { input: "okau understood", expect: "acknowledgment", type: "typo" },
  { input: "alrght then", expect: "acknowledgment", type: "typo" },
  { input: "yess i agree", expect: "agreement", type: "typo" },
  { input: "nah i dont tink so", expect: "disagreement", type: "typo" },
  // --- informal and slang ---
  { input: "yo wassup archie", expect: "greeting", type: "informal" },
  { input: "hola amigo", expect: "greeting", type: "informal" },
  { input: "imma head out, later dude", expect: "farewell", type: "informal" },
  { input: "big ups to you archie", expect: "gratitude", type: "informal" },
  { input: "you rock archie", expect: "gratitude", type: "informal" },
  { input: "my bad b", expect: "apology", type: "informal" },
  { input: "my guy abeg help me", expect: "help_request", type: "informal" },
  { input: "abeg wetin you dey do", expect: "activity_query", type: "informal" },
  { input: "guy you too much", expect: "gratitude", type: "informal" },
  { input: "shey you dey hear me", expect: "availability_check", type: "informal" },
  { input: "abeg repeat wetin you talk", expect: "clarification_request", type: "informal" },
  { input: "no wahala at all", expect: "agreement", type: "informal" },
  { input: "i no buy am", expect: "disagreement", type: "informal" },
  { input: "chai, today was tough", expect: "emotional_expression", type: "informal" },
  { input: "wahala no dey finish", expect: "emotional_expression", type: "informal" },
  { input: "we dey celebrate o", expect: "celebration", type: "informal" },
  { input: "make we vibe small", expect: "social_talk", type: "informal" },
  { input: "sun dey shine well well today", expect: "social_talk", type: "informal" },
  // --- unusual sentence structures ---
  { input: "to you i say good morning", expect: "greeting", type: "structure" },
  { input: "gone i am, farewell", expect: "farewell", type: "structure" },
  { input: "your help is what i need urgently", expect: "help_request", type: "structure" },
  { input: "help, of it i stand in need", expect: "help_request", type: "structure" },
  { input: "grateful to you i remain", expect: "gratitude", type: "structure" },
  { input: "an apology you are owed from me", expect: "apology", type: "structure" },
  { input: "agree with you i do completely", expect: "agreement", type: "structure" },
  { input: "disagree with that position i must", expect: "disagreement", type: "structure" },
  { input: "understanding of that i have not", expect: "clarification_request", type: "structure" },
  { input: "the time, tell me it", expect: "ANY:time_query|knowledge_query", type: "structure" },
  { input: "there, are you still", expect: "availability_check", type: "structure" },
  { input: "doing what are you", expect: "activity_query", type: "structure" },
  { input: "happy beyond words i am", expect: "emotional_expression", type: "structure" },
  { input: "birthday it is, mine", expect: "celebration", type: "structure" },
  { input: "you there being present matters to me", expect: "availability_check", type: "structure" },
  // --- emoji enhanced and emoji only ---
  { input: "thanks 🙏🙏", expect: "gratitude", type: "emoji" },
  { input: "thank you so much 🙏", expect: "gratitude", type: "emoji" },
  { input: "ok 👍", expect: "ANY:agreement|acknowledgment", type: "emoji" },
  { input: "alright 👌👌", expect: "agreement", type: "emoji" },
  { input: "congrats 🎉🎉🎉", expect: "celebration", type: "emoji" },
  { input: "we won 🔥", expect: "celebration", type: "emoji" },
  { input: "well done 💯", expect: "gratitude", type: "emoji" },
  { input: "good morning 😊", expect: "greeting", type: "emoji" },
  { input: "hey 😄", expect: "greeting", type: "emoji" },
  { input: "im so happy ❤️", expect: "emotional_expression", type: "emoji" },
  { input: "today is rough 😞", expect: "emotional_expression", type: "emoji" },
  { input: "why 😡", expect: "emotional_expression", type: "emoji" },
  { input: "what?! 😮", expect: "emotional_expression", type: "emoji" },
  { input: "so sleepy 😴", expect: "emotional_expression", type: "emoji" },
  { input: "hmm 🤔", expect: "ANY:clarification_request|acknowledgment", type: "emoji" },
  { input: "we move 🚀", expect: "ANY:celebration|social_talk", type: "emoji" },
  { input: "🙏", expect: "gratitude", type: "emoji" },
  { input: "👍", expect: "agreement", type: "emoji" },
  { input: "👌", expect: "agreement", type: "emoji" },
  { input: "🎉", expect: "celebration", type: "emoji" },
  { input: "💯", expect: "ANY:agreement|gratitude", type: "emoji" },
  { input: "❤️", expect: "emotional_expression", type: "emoji" },
  { input: "😢", expect: "emotional_expression", type: "emoji" },
  { input: "😂", expect: "ANY:emotional_expression|gratitude", type: "emoji" },
  { input: "😴", expect: "emotional_expression", type: "emoji" },
  { input: "🤔", expect: "clarification_request", type: "emoji" },
  { input: "🙂", expect: "acknowledgment", type: "emoji" },
  { input: "🚀", expect: "celebration", type: "emoji" },
  // --- unknown and ambiguous: honest fallback only ---
  { input: "the sky is blue", expect: "FALLBACK", type: "unknown" },
  { input: "potatoes", expect: "FALLBACK", type: "unknown" },
  { input: "my uncle sells yam in the village", expect: "FALLBACK", type: "unknown" },
  { input: "tortoises live for centuries", expect: "FALLBACK", type: "unknown" },
  { input: "jupiter has many moons", expect: "FALLBACK", type: "unknown" },
  { input: "kjsdhfkjhsdf", expect: "FALLBACK", type: "unknown" },
  { input: "blorp florp snorp", expect: "FALLBACK", type: "unknown" },
  { input: "4444 555", expect: "FALLBACK", type: "unknown" },
  { input: "the capital of france is paris", expect: "FALLBACK", type: "unknown" },
  { input: "water freezes when it is cold enough", expect: "FALLBACK", type: "unknown" },
  { input: "my favorite color is purple", expect: "FALLBACK", type: "unknown" },
  // --- multiturn: context dependent follow ups ---
  {
    input: "and what about the price",
    expect: "ANY:knowledge_query|price_query",
    type: "multiturn",
    history: [
      { role: "owner", text: "tell me about granite for the driveway" },
      { role: "archie", text: "granite is a coarse aggregate used for concrete and compaction" },
    ],
  },
  {
    input: "ok and how do i apply it",
    expect: "ANY:knowledge_query|howto_guidance|acknowledgment",
    type: "multiturn",
    history: [
      { role: "owner", text: "what is screeding" },
      { role: "archie", text: "screeding is applying a smooth cement layer to a floor" },
    ],
  },
  {
    input: "great, so when is the meeting",
    expect: "ANY:knowledge_query|gratitude|acknowledgment",
    type: "multiturn",
    history: [
      { role: "owner", text: "remember the delivery is on friday" },
      { role: "archie", text: "noted, the delivery is on friday" },
    ],
  },
  {
    input: "understood, thanks and goodbye",
    expect: "ANY:farewell|acknowledgment|gratitude",
    type: "multiturn",
    history: [
      { role: "owner", text: "explain the primer coat one more time" },
      { role: "archie", text: "the primer coat seals the surface before paint" },
    ],
  },
  {
    input: "you too, take care",
    expect: "ANY:farewell|social_talk",
    type: "multiturn",
    history: [
      { role: "owner", text: "i am heading home now" },
      { role: "archie", text: "safe journey home, talk tomorrow" },
    ],
  },
  {
    input: "sorry i meant the kitchen not the bedroom",
    expect: "correction",
    type: "multiturn",
    history: [
      { role: "owner", text: "estimate paint for my bedroom" },
      { role: "archie", text: "sure, give me the bedroom dimensions" },
    ],
  },
];

/** Total count of conversational training examples. */
export function conversationCorpusCount(): number {
  return CONVERSATION_CORPUS.reduce((n, [, ex]) => n + ex.length, 0);
}
