/*
# Phase 8b: Seed 300+ additional paint colors to reach 500+ total
# Extends the existing 220 colors across all 12 families
*/

do $$
begin
  perform public.add_paint_color('Lily White','lily-white','#E9E3E3','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Emulsion,Satin}',true,false,47,false,false,221);
  perform public.add_paint_color('Porcelain','porcelain','#E4DEDE','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin}',true,false,41,false,false,222);
  perform public.add_paint_color('Cotton','cotton','#F3F1F1','white','ceiling-colors','{Ceiling,Trim,Doors}','{Emulsion,Satin}',true,false,83,false,false,223);
  perform public.add_paint_color('Dove White','dove-white','#E7E1E1','white','trim-colors','{Bedroom,Bathroom}','{Emulsion,Satin}',true,false,84,false,false,224);
  perform public.add_paint_color('Wedding White','wedding-white','#EAE9E9','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Satin}',true,true,75,true,false,225);
  perform public.add_paint_color('Antique White','antique-white','#F0ECEC','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin}',true,false,78,false,false,226);
  perform public.add_paint_color('Chiffon','chiffon','#F3F1F1','white','ceiling-colors','{Ceiling,Trim,Doors}','{Satin}',true,false,35,false,false,227);
  perform public.add_paint_color('Swan White','swan-white','#F7F5F5','white','trim-colors','{Bedroom,Bathroom}','{Emulsion,Satin}',true,false,78,false,false,228);
  perform public.add_paint_color('Frost','frost','#F2F0F0','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Satin}',true,false,39,false,false,229);
  perform public.add_paint_color('Cloud White','cloud-white','#EAE9E9','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin,Gloss}',true,false,58,false,false,230);
  perform public.add_paint_color('Moonlight','moonlight','#E2E0DF','white','ceiling-colors','{Ceiling,Trim,Doors}','{Emulsion,Satin}',true,false,70,false,false,231);
  perform public.add_paint_color('Opal','opal','#EDECEC','white','trim-colors','{Bedroom,Bathroom}','{Satin}',true,false,88,false,false,232);
  perform public.add_paint_color('Rice Paper','rice-paper','#EDEAE9','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Satin}',true,true,81,false,true,233);
  perform public.add_paint_color('Sea Salt White','sea-salt-white','#E5E2E0','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin,Gloss}',true,false,36,true,false,234);
  perform public.add_paint_color('Tissue White','tissue-white','#EDEAE8','white','ceiling-colors','{Ceiling,Trim,Doors}','{Emulsion,Satin,Gloss}',true,false,38,false,false,235);
  perform public.add_paint_color('Whisper White','whisper-white','#F9F9F8','white','trim-colors','{Bedroom,Bathroom}','{Emulsion}',true,false,31,false,false,236);
  perform public.add_paint_color('Wimbledon White','wimbledon-white','#EBE8E6','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Satin}',true,true,67,false,false,237);
  perform public.add_paint_color('Winter White','winter-white','#F5F3F2','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Satin}',true,false,94,true,true,238);
  perform public.add_paint_color('Bone White','bone-white','#EFEDEB','white','ceiling-colors','{Ceiling,Trim,Doors}','{Satin}',true,false,55,false,false,239);
  perform public.add_paint_color('Chalk White','chalk-white','#EEECEB','white','trim-colors','{Bedroom,Bathroom}','{Emulsion,Satin}',true,false,44,true,true,240);
  perform public.add_paint_color('Hail White','hail-white','#E7E6E5','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Satin}',true,true,40,false,false,241);
  perform public.add_paint_color('Icelandic White','icelandic-white','#F0EEEB','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin}',true,false,46,false,false,242);
  perform public.add_paint_color('Milky White','milky-white','#F7F6F6','white','ceiling-colors','{Ceiling,Trim,Doors}','{Emulsion,Satin,Gloss}',true,false,84,true,true,243);
  perform public.add_paint_color('Pearl','pearl','#ECEBE8','white','trim-colors','{Bedroom,Bathroom}','{Emulsion,Satin,Gloss}',true,false,77,false,false,244);
  perform public.add_paint_color('Platinum White','platinum-white','#E1E1E0','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Emulsion,Satin,Gloss}',true,false,59,false,false,245);
  perform public.add_paint_color('Polar White','polar-white','#F7F7F7','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin}',true,false,72,false,false,246);
  perform public.add_paint_color('Shore White','shore-white','#E5E4E2','white','ceiling-colors','{Ceiling,Trim,Doors}','{Emulsion}',true,false,90,false,false,247);
  perform public.add_paint_color('Silver Birch White','silver-birch-white','#E4E3E1','white','trim-colors','{Bedroom,Bathroom}','{Emulsion}',true,false,85,false,false,248);
  perform public.add_paint_color('Snowdrift','snowdrift','#FAF9F8','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Emulsion,Satin}',true,true,42,false,false,249);
  perform public.add_paint_color('Vapor White','vapor-white','#E6E6E3','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin}',true,false,87,false,false,250);
  perform public.add_paint_color('Wheat White','wheat-white','#F8F8F7','white','ceiling-colors','{Ceiling,Trim,Doors}','{Emulsion}',true,false,86,true,true,251);
  perform public.add_paint_color('Almond White','almond-white','#FAF9F9','white','trim-colors','{Bedroom,Bathroom}','{Emulsion,Satin}',true,false,31,true,true,252);
  perform public.add_paint_color('Biscuit','biscuit','#EEEDEB','white','white-collection','{Living Room,Bedroom,Kitchen,Hallway}','{Emulsion,Satin,Gloss}',true,true,81,true,false,253);
  perform public.add_paint_color('Blossom White','blossom-white','#EAEAE3','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin}',true,false,88,false,false,254);
  perform public.add_paint_color('Bridal White','bridal-white','#E8E8E7','white','ceiling-colors','{Ceiling,Trim,Doors}','{Emulsion}',true,false,37,false,false,255);
  perform public.add_paint_color('Camellia White','camellia-white','#EFEFEE','white','trim-colors','{Bedroom,Bathroom}','{Satin}',true,false,94,true,false,256);
  perform public.add_paint_color('Jet Black','jet-black','#070606','black','black-collection','{Accent,Doors,Trim}','{Emulsion,Satin}',true,false,38,false,false,257);
  perform public.add_paint_color('Lamp Black','lamp-black','#151211','black','exterior-wall-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,35,false,false,258);
  perform public.add_paint_color('Raven','raven','#0D0D0C','black','door-colors','{Accent,Furniture}','{Gloss}',false,true,63,false,false,259);
  perform public.add_paint_color('Velvet Black','velvet-black','#151515','black','accent-colors','{Doors,Trim}','{Emulsion}',true,false,88,false,false,260);
  perform public.add_paint_color('Obsidian','obsidian','#141412','black','black-collection','{Accent,Doors,Trim}','{Emulsion}',true,false,42,false,false,261);
  perform public.add_paint_color('Black Pearl','black-pearl','#0D0E0D','black','exterior-wall-colors','{Exterior,Doors}','{Emulsion,Enamel}',false,true,38,true,false,262);
  perform public.add_paint_color('Cosmic Black','cosmic-black','#121312','black','door-colors','{Accent,Furniture}','{Enamel,Gloss}',false,true,68,false,true,263);
  perform public.add_paint_color('Piano Black','piano-black','#111412','black','accent-colors','{Doors,Trim}','{Emulsion,Satin}',true,false,43,true,false,264);
  perform public.add_paint_color('Soot','soot','#080908','black','black-collection','{Accent,Doors,Trim}','{Emulsion,Satin}',true,false,66,false,false,265);
  perform public.add_paint_color('Vantablack','vantablack','#191C1B','black','exterior-wall-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,94,false,true,266);
  perform public.add_paint_color('Black Coffee','black-coffee','#0F1010','black','door-colors','{Accent,Furniture}','{Enamel,Gloss}',false,true,65,false,false,267);
  perform public.add_paint_color('Black Olive','black-olive','#101010','black','accent-colors','{Doors,Trim}','{Satin}',true,false,84,false,false,268);
  perform public.add_paint_color('Ink Black','ink-black','#181A1B','black','black-collection','{Accent,Doors,Trim}','{Emulsion,Satin,Gloss}',true,true,48,false,false,269);
  perform public.add_paint_color('Licorice','licorice','#17171B','black','exterior-wall-colors','{Exterior,Doors}','{Emulsion,Enamel}',false,true,35,true,false,270);
  perform public.add_paint_color('Midnight Oil','midnight-oil','#0D0D0F','black','door-colors','{Accent,Furniture}','{Enamel,Gloss}',false,true,82,true,false,271);
  perform public.add_paint_color('Onyx Black','onyx-black','#1D1B20','black','accent-colors','{Doors,Trim}','{Emulsion,Satin,Gloss}',true,true,52,true,false,272);
  perform public.add_paint_color('Panther','panther','#100E10','black','black-collection','{Accent,Doors,Trim}','{Satin}',true,true,61,false,false,273);
  perform public.add_paint_color('Phantom','phantom','#060506','black','exterior-wall-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,90,false,false,274);
  perform public.add_paint_color('Pitch Black','pitch-black','#1A191A','black','door-colors','{Accent,Furniture}','{Emulsion,Enamel}',false,true,59,false,false,275);
  perform public.add_paint_color('Eclipse Black','eclipse-black','#201B1C','black','accent-colors','{Doors,Trim}','{Satin}',true,false,65,false,false,276);
  perform public.add_paint_color('Pigeon Gray','pigeon-gray','#544848','gray','gray-collection','{Living Room,Office,Bedroom}','{Satin}',true,false,63,false,true,277);
  perform public.add_paint_color('Dove Gray','dove-gray','#8C8B8B','gray','interior-wall-colors','{Exterior,Office}','{Satin}',true,false,74,false,false,278);
  perform public.add_paint_color('Silver Lake','silver-lake','#544C48','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Gloss}',false,true,54,false,false,279);
  perform public.add_paint_color('Manatee Gray','manatee-gray','#4A4846','gray','office-colors','{Bedroom,Bathroom,Office}','{Emulsion,Satin,Gloss}',true,false,72,false,false,280);
  perform public.add_paint_color('French Gray','french-gray','#999590','gray','gray-collection','{Living Room,Office,Bedroom}','{Satin}',true,false,71,false,false,281);
  perform public.add_paint_color('London Gray','london-gray','#969592','gray','interior-wall-colors','{Exterior,Office}','{Emulsion,Satin,Gloss}',true,false,78,false,true,282);
  perform public.add_paint_color('Manchester Gray','manchester-gray','#78786E','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Gloss}',false,true,30,false,false,283);
  perform public.add_paint_color('Marseille Gray','marseille-gray','#7B7C73','gray','office-colors','{Bedroom,Bathroom,Office}','{Satin}',true,true,57,false,false,284);
  perform public.add_paint_color('Monument Gray','monument-gray','#66695E','gray','gray-collection','{Living Room,Office,Bedroom}','{Emulsion,Satin,Gloss}',true,true,72,false,true,285);
  perform public.add_paint_color('Nantucket Gray','nantucket-gray','#5D6157','gray','interior-wall-colors','{Exterior,Office}','{Emulsion,Satin,Gloss}',true,false,55,false,false,286);
  perform public.add_paint_color('Oxford Gray','oxford-gray','#A1A69D','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Emulsion,Enamel}',false,true,88,false,false,287);
  perform public.add_paint_color('Passive Gray','passive-gray','#5D625B','gray','office-colors','{Bedroom,Bathroom,Office}','{Emulsion}',true,false,30,true,true,288);
  perform public.add_paint_color('Pebble Gray','pebble-gray','#A5A7A4','gray','gray-collection','{Living Room,Office,Bedroom}','{Emulsion}',true,true,89,false,false,289);
  perform public.add_paint_color('Platinum Gray','platinum-gray','#A2A9A3','gray','interior-wall-colors','{Exterior,Office}','{Emulsion,Satin}',true,false,70,true,true,290);
  perform public.add_paint_color('Portland Gray','portland-gray','#ACB6AE','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Gloss}',false,true,84,true,false,291);
  perform public.add_paint_color('Rock Gray','rock-gray','#9CA39E','gray','office-colors','{Bedroom,Bathroom,Office}','{Emulsion}',true,true,65,false,false,292);
  perform public.add_paint_color('Roman Gray','roman-gray','#979E9A','gray','gray-collection','{Living Room,Office,Bedroom}','{Satin}',true,false,60,false,false,293);
  perform public.add_paint_color('Savannah Gray','savannah-gray','#5C5E5D','gray','interior-wall-colors','{Exterior,Office}','{Emulsion,Satin}',true,false,49,false,false,294);
  perform public.add_paint_color('Seal Gray','seal-gray','#777E7D','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Emulsion,Enamel}',false,true,37,false,false,295);
  perform public.add_paint_color('Seattle Gray','seattle-gray','#9AA7A7','gray','office-colors','{Bedroom,Bathroom,Office}','{Emulsion,Satin}',true,true,78,false,true,296);
  perform public.add_paint_color('Shark Gray','shark-gray','#B4BCBE','gray','gray-collection','{Living Room,Office,Bedroom}','{Emulsion}',true,false,83,false,false,297);
  perform public.add_paint_color('Slate Gray Two','slate-gray-two','#5E6366','gray','interior-wall-colors','{Exterior,Office}','{Emulsion,Satin,Gloss}',true,false,92,false,false,298);
  perform public.add_paint_color('Smoke Gray','smoke-gray','#959CA2','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Gloss}',false,true,89,true,true,299);
  perform public.add_paint_color('Spinnaker Gray','spinnaker-gray','#8F9299','gray','office-colors','{Bedroom,Bathroom,Office}','{Emulsion}',true,false,40,false,false,300);
  perform public.add_paint_color('Starling Gray','starling-gray','#67686B','gray','gray-collection','{Living Room,Office,Bedroom}','{Emulsion,Satin}',true,false,88,false,false,301);
  perform public.add_paint_color('Steel Gray Two','steel-gray-two','#B7B7BA','gray','interior-wall-colors','{Exterior,Office}','{Emulsion}',true,false,83,false,false,302);
  perform public.add_paint_color('Storm Gray','storm-gray','#43424A','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Enamel,Gloss}',false,true,74,false,false,303);
  perform public.add_paint_color('Taupe Gray','taupe-gray','#B6B4BD','gray','office-colors','{Bedroom,Bathroom,Office}','{Emulsion,Satin}',true,true,55,true,false,304);
  perform public.add_paint_color('Tundra Gray','tundra-gray','#86818E','gray','gray-collection','{Living Room,Office,Bedroom}','{Emulsion}',true,false,57,false,false,305);
  perform public.add_paint_color('Volcano Gray','volcano-gray','#8D8B8E','gray','interior-wall-colors','{Exterior,Office}','{Satin}',true,false,44,false,false,306);
  perform public.add_paint_color('Walrus Gray','walrus-gray','#434243','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Emulsion,Enamel}',false,true,69,false,true,307);
  perform public.add_paint_color('Whale Gray','whale-gray','#989798','gray','office-colors','{Bedroom,Bathroom,Office}','{Emulsion,Satin,Gloss}',true,false,61,false,false,308);
  perform public.add_paint_color('Zinc Gray','zinc-gray','#8F808E','gray','gray-collection','{Living Room,Office,Bedroom}','{Emulsion,Satin}',true,true,35,false,false,309);
  perform public.add_paint_color('Argent','argent','#929192','gray','interior-wall-colors','{Exterior,Office}','{Satin}',true,false,31,true,false,310);
  perform public.add_paint_color('Battleship','battleship','#716A6E','gray','exterior-wall-colors','{Living Room,Hallway,Kitchen}','{Enamel,Gloss}',false,true,88,false,false,311);
  perform public.add_paint_color('Cadet Gray','cadet-gray','#B8B1B4','gray','office-colors','{Bedroom,Bathroom,Office}','{Satin}',true,true,91,false,false,312);
  perform public.add_paint_color('Dolphin','dolphin','#AFA3A7','gray','gray-collection','{Living Room,Office,Bedroom}','{Satin}',true,false,41,false,false,313);
  perform public.add_paint_color('Elephant Gray','elephant-gray','#999091','gray','interior-wall-colors','{Exterior,Office}','{Emulsion}',true,false,73,false,true,314);
  perform public.add_paint_color('Biscotti','biscotti','#B8A79A','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Emulsion,Satin,Gloss}',true,false,65,true,false,315);
  perform public.add_paint_color('Buckeye Beige','buckeye-beige','#C8B7AB','beige','interior-wall-colors','{Living Room,Dining,Kitchen}','{Satin}',true,false,54,false,false,316);
  perform public.add_paint_color('Cape Beige','cape-beige','#D0C0B3','beige','neutral-colors','{Bedroom,Office}','{Emulsion,Satin,Gloss}',true,false,92,false,false,317);
  perform public.add_paint_color('Desert Sand Two','desert-sand-two','#C0AA98','beige','earth-tone-collection','{Living Room,Bedroom,Bathroom}','{Emulsion}',true,false,77,false,false,318);
  perform public.add_paint_color('Driftwood','driftwood','#C2B4A9','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Satin}',true,false,69,false,false,319);
  perform public.add_paint_color('Fawn','fawn','#D1C7BF','beige','interior-wall-colors','{Living Room,Dining,Kitchen}','{Emulsion,Satin,Gloss}',true,false,53,false,false,320);
  perform public.add_paint_color('Flax','flax','#DCCDBF','beige','neutral-colors','{Bedroom,Office}','{Satin}',true,false,67,false,false,321);
  perform public.add_paint_color('Golden Beige','golden-beige','#DDD7D0','beige','earth-tone-collection','{Living Room,Bedroom,Bathroom}','{Emulsion,Satin,Gloss}',true,false,67,false,false,322);
  perform public.add_paint_color('Harvest Beige','harvest-beige','#A5998D','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Emulsion}',true,true,66,false,false,323);
  perform public.add_paint_color('Hemp','hemp','#C2A98F','beige','interior-wall-colors','{Living Room,Dining,Kitchen}','{Emulsion,Satin,Gloss}',true,false,91,false,false,324);
  perform public.add_paint_color('Honey Beige','honey-beige','#D3CDC6','beige','neutral-colors','{Bedroom,Office}','{Emulsion,Satin}',true,false,68,false,false,325);
  perform public.add_paint_color('Khaki Two','khaki-two','#D6CCBF','beige','earth-tone-collection','{Living Room,Bedroom,Bathroom}','{Emulsion}',true,false,58,false,false,326);
  perform public.add_paint_color('Maple Beige','maple-beige','#E2D9CD','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Satin}',true,true,69,false,false,327);
  perform public.add_paint_color('Mushroom','mushroom','#BFA98C','beige','interior-wall-colors','{Living Room,Dining,Kitchen}','{Emulsion,Satin}',true,false,57,false,false,328);
  perform public.add_paint_color('Nutmeg Beige','nutmeg-beige','#BDB4A9','beige','neutral-colors','{Bedroom,Office}','{Emulsion,Satin}',true,false,90,false,false,329);
  perform public.add_paint_color('Oatmeal','oatmeal','#B1A99D','beige','earth-tone-collection','{Living Room,Bedroom,Bathroom}','{Emulsion}',true,true,63,false,false,330);
  perform public.add_paint_color('Pecan','pecan','#C8BEAF','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Emulsion,Satin,Gloss}',true,false,49,true,false,331);
  perform public.add_paint_color('Putty','putty','#D1CCC5','beige','interior-wall-colors','{Living Room,Dining,Kitchen}','{Emulsion,Satin}',true,false,66,false,false,332);
  perform public.add_paint_color('Rattan','rattan','#CDBDA4','beige','neutral-colors','{Bedroom,Office}','{Emulsion}',true,false,93,false,false,333);
  perform public.add_paint_color('Sable','sable','#B0A084','beige','earth-tone-collection','{Living Room,Bedroom,Bathroom}','{Satin}',true,true,59,true,false,334);
  perform public.add_paint_color('Savannah Beige','savannah-beige','#D5C8B2','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Emulsion,Satin}',true,false,64,false,false,335);
  perform public.add_paint_color('Sesame','sesame','#CEC6B6','beige','interior-wall-colors','{Living Room,Dining,Kitchen}','{Emulsion,Satin,Gloss}',true,false,65,false,false,336);
  perform public.add_paint_color('Silk Beige','silk-beige','#CCBDA1','beige','neutral-colors','{Bedroom,Office}','{Emulsion}',true,false,82,false,false,337);
  perform public.add_paint_color('Spelt','spelt','#C5BDAB','beige','earth-tone-collection','{Living Room,Bedroom,Bathroom}','{Satin}',true,true,81,true,false,338);
  perform public.add_paint_color('Straw','straw','#AEA592','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Satin}',true,false,81,true,false,339);
  perform public.add_paint_color('Tapioca','tapioca','#CBC1AB','beige','interior-wall-colors','{Living Room,Dining,Kitchen}','{Emulsion,Satin}',true,false,82,false,false,340);
  perform public.add_paint_color('Tuscan Beige','tuscan-beige','#D5CEBD','beige','neutral-colors','{Bedroom,Office}','{Emulsion}',true,false,56,false,false,341);
  perform public.add_paint_color('Wheatfield','wheatfield','#DCD9D2','beige','earth-tone-collection','{Living Room,Bedroom,Bathroom}','{Emulsion}',true,false,60,false,false,342);
  perform public.add_paint_color('Willow Beige','willow-beige','#DCDAD3','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Emulsion}',true,false,44,false,false,343);
  perform public.add_paint_color('Yarn Beige','yarn-beige','#D1CCBB','beige','interior-wall-colors','{Living Room,Dining,Kitchen}','{Emulsion,Satin,Gloss}',true,false,95,false,false,344);
  perform public.add_paint_color('Adriatic Blue','adriatic-blue','#56A7A7','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion}',true,false,79,false,false,345);
  perform public.add_paint_color('Aegean Blue','aegean-blue','#23999B','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,true,83,false,false,346);
  perform public.add_paint_color('Air Force Blue','air-force-blue','#408083','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin}',true,false,92,true,false,347);
  perform public.add_paint_color('Aquamarine','aquamarine','#42B2BA','blue','cool-colors','{Bedroom,Children,Office}','{Satin}',true,false,88,true,true,348);
  perform public.add_paint_color('Atlantic Blue','atlantic-blue','#2E7F86','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion,Satin,Gloss}',true,true,82,false,false,349);
  perform public.add_paint_color('Azure Mist','azure-mist','#5EAFB9','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion}',true,true,49,false,false,350);
  perform public.add_paint_color('Bahama Blue','bahama-blue','#6ACFDD','blue','bathroom-colors','{Bathroom,Kitchen}','{Satin}',true,false,86,false,true,351);
  perform public.add_paint_color('Baltic Blue','baltic-blue','#5BABB9','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion,Satin,Gloss}',true,false,49,false,false,352);
  perform public.add_paint_color('Blue Lagoon','blue-lagoon','#70C1D2','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion}',true,false,78,true,false,353);
  perform public.add_paint_color('Bluebird','bluebird','#185E6F','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion}',true,true,38,false,false,354);
  perform public.add_paint_color('Cambridge Blue','cambridge-blue','#3097B2','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin,Gloss}',true,false,42,false,false,355);
  perform public.add_paint_color('Canal Blue','canal-blue','#77C1D7','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion,Satin,Gloss}',true,false,35,false,false,356);
  perform public.add_paint_color('Caspian Blue','caspian-blue','#5A8D9E','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion}',true,false,53,false,false,357);
  perform public.add_paint_color('Cerulean','cerulean','#4A9BBA','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,true,59,false,false,358);
  perform public.add_paint_color('Cornflower','cornflower','#2994C1','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin}',true,false,66,false,false,359);
  perform public.add_paint_color('Danube','danube','#1E7AA6','blue','cool-colors','{Bedroom,Children,Office}','{Satin}',true,false,84,false,false,360);
  perform public.add_paint_color('Darkest Blue','darkest-blue','#1C5B7B','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion}',true,false,78,false,false,361);
  perform public.add_paint_color('Deep Sea','deep-sea','#8AA4B3','blue','bedroom-colors','{Living Room,Dining,Office}','{Satin}',true,true,80,false,false,362);
  perform public.add_paint_color('Delft','delft','#4FA5DA','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin}',true,false,66,false,false,363);
  perform public.add_paint_color('Eton Blue','eton-blue','#4893C5','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion,Satin,Gloss}',true,true,47,false,true,364);
  perform public.add_paint_color('Glacier Blue','glacier-blue','#1B496B','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Satin}',true,false,76,false,false,365);
  perform public.add_paint_color('Harbor Blue','harbor-blue','#385165','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion}',true,false,76,false,true,366);
  perform public.add_paint_color('Horizon Blue','horizon-blue','#75AFE2','blue','bathroom-colors','{Bathroom,Kitchen}','{Satin}',true,true,67,false,false,367);
  perform public.add_paint_color('Iceberg','iceberg','#98AFC4','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion,Satin}',true,false,80,true,false,368);
  perform public.add_paint_color('Indigo Sea','indigo-sea','#637C97','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion}',true,false,88,false,false,369);
  perform public.add_paint_color('Iris Blue','iris-blue','#78A8DE','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion}',true,false,43,false,false,370);
  perform public.add_paint_color('Klein Blue','klein-blue','#1E5393','blue','bathroom-colors','{Bathroom,Kitchen}','{Satin}',true,false,38,false,false,371);
  perform public.add_paint_color('Lagoon Blue','lagoon-blue','#334256','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion}',true,true,34,false,false,372);
  perform public.add_paint_color('Lapis Blue','lapis-blue','#406294','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion,Satin,Gloss}',true,false,83,false,false,373);
  perform public.add_paint_color('Liberty Blue','liberty-blue','#3C75D0','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion,Satin}',true,true,65,false,false,374);
  perform public.add_paint_color('Mediterranean','mediterranean','#1B3E7A','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin,Gloss}',true,false,77,false,true,375);
  perform public.add_paint_color('Midnight Sea','midnight-sea','#93A6C9','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion}',true,false,88,false,false,376);
  perform public.add_paint_color('Mist Blue','mist-blue','#4F5D7D','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion,Satin}',true,false,46,false,false,377);
  perform public.add_paint_color('Nile Blue','nile-blue','#6C89CD','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,true,59,false,false,378);
  perform public.add_paint_color('North Sea','north-sea','#96A5CB','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin}',true,true,46,false,false,379);
  perform public.add_paint_color('Pacific Depths','pacific-depths','#4C5B84','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion,Satin}',true,false,60,false,false,380);
  perform public.add_paint_color('Peacock','peacock','#3557C2','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion,Satin,Gloss}',true,false,38,false,false,381);
  perform public.add_paint_color('Persian Blue','persian-blue','#33437F','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion,Satin}',true,false,35,false,true,382);
  perform public.add_paint_color('Plume','plume','#8B99D0','blue','bathroom-colors','{Bathroom,Kitchen}','{Satin}',true,false,37,true,false,383);
  perform public.add_paint_color('Portugal Blue','portugal-blue','#818ECE','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion,Satin}',true,false,39,true,false,384);
  perform public.add_paint_color('Prussian Blue','prussian-blue','#606CB0','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion,Satin,Gloss}',true,false,71,false,false,385);
  perform public.add_paint_color('Riviera','riviera','#747BAB','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion}',true,false,57,false,true,386);
  perform public.add_paint_color('Robin Egg','robin-egg','#6872BE','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion}',true,false,70,false,false,387);
  perform public.add_paint_color('Royal Marine','royal-marine','#3541B6','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion,Satin,Gloss}',true,false,41,true,false,388);
  perform public.add_paint_color('Sapphire','sapphire','#323DCC','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Satin}',true,false,72,false,false,389);
  perform public.add_paint_color('Scandinavian Blue','scandinavian-blue','#4D54D7','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion}',true,true,66,false,false,390);
  perform public.add_paint_color('Shallow Sea','shallow-sea','#565798','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin,Gloss}',true,false,43,false,false,391);
  perform public.add_paint_color('Silver Lake Blue','silver-lake-blue','#6C6CCC','blue','cool-colors','{Bedroom,Children,Office}','{Satin}',true,false,33,false,false,392);
  perform public.add_paint_color('Smoke Blue','smoke-blue','#7170B0','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion,Satin}',true,false,69,true,false,393);
  perform public.add_paint_color('Sonic Blue','sonic-blue','#3C38A2','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,false,48,false,true,394);
  perform public.add_paint_color('Stratosphere','stratosphere','#4C46A0','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin,Gloss}',true,false,50,false,false,395);
  perform public.add_paint_color('Sultan Blue','sultan-blue','#251D85','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion,Satin}',true,true,36,false,false,396);
  perform public.add_paint_color('Tangier','tangier','#4237A7','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion}',true,false,57,false,false,397);
  perform public.add_paint_color('Tiffany','tiffany','#5141C6','blue','bedroom-colors','{Living Room,Dining,Office}','{Satin}',true,false,69,false,false,398);
  perform public.add_paint_color('Tropical Blue','tropical-blue','#9A93C5','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin}',true,false,47,false,false,399);
  perform public.add_paint_color('Twilight Blue','twilight-blue','#332384','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion}',true,false,78,false,false,400);
  perform public.add_paint_color('Ultramarine Deep','ultramarine-deep','#948CB8','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Satin}',true,false,35,false,false,401);
  perform public.add_paint_color('Valley Blue','valley-blue','#5D44BE','blue','bedroom-colors','{Living Room,Dining,Office}','{Satin}',true,false,83,false,false,402);
  perform public.add_paint_color('Venice Blue','venice-blue','#5F3ECE','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin,Gloss}',true,true,76,false,false,403);
  perform public.add_paint_color('Wellington Blue','wellington-blue','#533A9F','blue','cool-colors','{Bedroom,Children,Office}','{Emulsion}',true,false,69,false,false,404);
  perform public.add_paint_color('Whisper Blue','whisper-blue','#3C296F','blue','blue-collection','{Bedroom,Bathroom,Living Room}','{Emulsion,Satin}',true,true,95,false,false,405);
  perform public.add_paint_color('Yacht Blue','yacht-blue','#45366A','blue','bedroom-colors','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,false,55,false,false,406);
  perform public.add_paint_color('Zaffre','zaffre','#8D7AB6','blue','bathroom-colors','{Bathroom,Kitchen}','{Emulsion,Satin}',true,true,93,false,false,407);
  perform public.add_paint_color('Absinthe','absinthe','#9DC847','green','green-collection','{Kitchen,Bedroom,Living Room}','{Satin}',true,false,49,false,false,408);
  perform public.add_paint_color('Aloe Vera','aloe-vera','#74933C','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Satin}',true,false,39,false,false,409);
  perform public.add_paint_color('Amazon Green','amazon-green','#A7B391','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Satin}',true,false,41,false,false,410);
  perform public.add_paint_color('Apple Green','apple-green','#A3BF7A','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin}',true,false,54,false,false,411);
  perform public.add_paint_color('Arboreal','arboreal','#A2BF7A','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin}',true,false,73,true,false,412);
  perform public.add_paint_color('Avocado','avocado','#758F54','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion,Satin}',true,false,86,false,false,413);
  perform public.add_paint_color('Bay Leaf','bay-leaf','#9AB977','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Satin}',true,false,36,false,false,414);
  perform public.add_paint_color('Bermuda','bermuda','#6D9740','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin}',true,false,62,false,false,415);
  perform public.add_paint_color('Bottle Green','bottle-green','#82A75D','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin,Gloss}',true,true,48,true,false,416);
  perform public.add_paint_color('Brook Green','brook-green','#8FA77A','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion}',true,false,40,false,false,417);
  perform public.add_paint_color('Cactus','cactus','#9ACA73','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion,Satin,Gloss}',true,true,41,false,false,418);
  perform public.add_paint_color('Caper','caper','#A9C495','green','earth-tone-collection','{Living Room,Dining,Office}','{Satin}',true,false,73,true,false,419);
  perform public.add_paint_color('Chartreuse','chartreuse','#5D774C','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin,Gloss}',true,false,42,false,false,420);
  perform public.add_paint_color('Chelsea Green','chelsea-green','#9ACC7B','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion,Satin}',true,true,46,false,false,421);
  perform public.add_paint_color('Clover','clover','#3B6524','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion,Satin,Gloss}',true,false,76,false,false,422);
  perform public.add_paint_color('Cucumber','cucumber','#89CB68','green','earth-tone-collection','{Living Room,Dining,Office}','{Satin}',true,false,59,false,false,423);
  perform public.add_paint_color('Dill','dill','#448526','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion}',true,true,86,false,false,424);
  perform public.add_paint_color('Emerald Isle','emerald-isle','#86D664','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion}',true,false,47,true,false,425);
  perform public.add_paint_color('Eucalyptus','eucalyptus','#3D692D','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Satin}',true,false,45,false,false,426);
  perform public.add_paint_color('Feldgrau','feldgrau','#367123','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,false,58,true,true,427);
  perform public.add_paint_color('Fir Green','fir-green','#6D8E64','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion}',true,true,60,false,false,428);
  perform public.add_paint_color('Galaxy Green','galaxy-green','#80D66A','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Satin}',true,false,72,false,false,429);
  perform public.add_paint_color('Garden Green','garden-green','#38742A','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion}',true,false,90,false,false,430);
  perform public.add_paint_color('Grasshopper','grasshopper','#43643C','green','earth-tone-collection','{Living Room,Dining,Office}','{Satin}',true,false,84,false,false,431);
  perform public.add_paint_color('Greenhouse','greenhouse','#73A76A','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin}',true,false,88,false,false,432);
  perform public.add_paint_color('Hackney Green','hackney-green','#58B84B','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion,Satin}',true,false,48,false,false,433);
  perform public.add_paint_color('Hedge','hedge','#76A771','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion}',true,false,76,false,false,434);
  perform public.add_paint_color('Holly Green','holly-green','#559C4F','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin}',true,false,79,true,false,435);
  perform public.add_paint_color('Hunter Green','hunter-green','#76B473','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin}',true,false,43,false,false,436);
  perform public.add_paint_color('Iguana','iguana','#498646','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion,Satin}',true,false,52,true,false,437);
  perform public.add_paint_color('Jade Green','jade-green','#73C772','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion}',true,true,38,false,true,438);
  perform public.add_paint_color('Kale','kale','#476548','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,false,35,false,false,439);
  perform public.add_paint_color('Kelly Green','kelly-green','#7AB17C','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion}',true,false,54,false,true,440);
  perform public.add_paint_color('Kelp','kelp','#80B683','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Satin}',true,false,85,true,false,441);
  perform public.add_paint_color('Laurel Green','laurel-green','#3B6E3F','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion}',true,true,93,false,false,442);
  perform public.add_paint_color('Lime Twist','lime-twist','#266B2C','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin}',true,false,53,false,false,443);
  perform public.add_paint_color('Lotus Green','lotus-green','#61A86A','green','green-collection','{Kitchen,Bedroom,Living Room}','{Satin}',true,false,84,false,false,444);
  perform public.add_paint_color('Mantis','mantis','#41A24E','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Satin}',true,false,37,false,false,445);
  perform public.add_paint_color('Meadow','meadow','#217E30','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion,Satin,Gloss}',true,false,86,false,false,446);
  perform public.add_paint_color('Mint Julep','mint-julep','#92C69C','green','earth-tone-collection','{Living Room,Dining,Office}','{Satin}',true,true,34,false,false,447);
  perform public.add_paint_color('Mossy','mossy','#2F6139','green','green-collection','{Kitchen,Bedroom,Living Room}','{Satin}',true,true,47,false,false,448);
  perform public.add_paint_color('Nile Green','nile-green','#1B692D','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion,Satin,Gloss}',true,false,53,false,false,449);
  perform public.add_paint_color('Olive Branch','olive-branch','#59C775','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Satin}',true,false,57,true,false,450);
  perform public.add_paint_color('Palm Green','palm-green','#3C6246','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion}',true,true,39,false,true,451);
  perform public.add_paint_color('Parrot Green','parrot-green','#85D89D','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin}',true,false,70,false,false,452);
  perform public.add_paint_color('Pistachio','pistachio','#6DD58E','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Satin}',true,false,52,false,false,453);
  perform public.add_paint_color('Plantation','plantation','#2C884C','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion,Satin,Gloss}',true,false,93,false,false,454);
  perform public.add_paint_color('Reed Green','reed-green','#2A6840','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,false,69,false,false,455);
  perform public.add_paint_color('Royal Green','royal-green','#6ECE92','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion}',true,false,39,false,false,456);
  perform public.add_paint_color('Sap Green','sap-green','#38965E','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion}',true,false,53,false,false,457);
  perform public.add_paint_color('Seaweed','seaweed','#3ABB71','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion,Satin}',true,false,68,false,false,458);
  perform public.add_paint_color('Shamrock','shamrock','#34C273','green','earth-tone-collection','{Living Room,Dining,Office}','{Satin}',true,true,66,true,false,459);
  perform public.add_paint_color('Spring Meadow','spring-meadow','#4E7661','green','green-collection','{Kitchen,Bedroom,Living Room}','{Satin}',true,false,41,false,false,460);
  perform public.add_paint_color('Spruce','spruce','#6CA286','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Emulsion,Satin,Gloss}',true,true,73,true,false,461);
  perform public.add_paint_color('Tarragon','tarragon','#9DBBAD','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion,Satin}',true,true,63,false,false,462);
  perform public.add_paint_color('Treetop','treetop','#5BB48A','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin}',true,false,67,false,false,463);
  perform public.add_paint_color('Vermont Green','vermont-green','#335C4A','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion}',true,false,37,false,false,464);
  perform public.add_paint_color('Vineyard','vineyard','#398D6A','green','kitchen-colors','{Exterior,Garden,Kitchen}','{Satin}',true,false,70,false,true,465);
  perform public.add_paint_color('Watercress','watercress','#3EB787','green','nature-collection','{Bathroom,Kitchen,Bedroom}','{Emulsion,Satin,Gloss}',true,true,43,false,false,466);
  perform public.add_paint_color('Wildflower Green','wildflower-green','#365449','green','earth-tone-collection','{Living Room,Dining,Office}','{Emulsion,Satin,Gloss}',true,false,79,true,false,467);
  perform public.add_paint_color('Zucchini','zucchini','#7FD6B7','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin,Gloss}',true,true,70,false,false,468);
  perform public.add_paint_color('Acorn','acorn','#663626','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion}',true,true,32,false,false,469);
  perform public.add_paint_color('Bark','bark','#662E1A','brown','door-colors','{Exterior,Doors}','{Emulsion,Enamel}',false,true,75,false,false,470);
  perform public.add_paint_color('Bay Brown','bay-brown','#472A1F','brown','earth-tone-collection','{Living Room,Library,Office}','{Emulsion}',true,false,43,false,true,471);
  perform public.add_paint_color('Bear Brown','bear-brown','#6C3E2D','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Gloss}',false,true,35,false,false,472);
  perform public.add_paint_color('Bistre','bistre','#6D4738','brown','brown-collection','{Doors,Trim,Furniture}','{Satin}',true,false,65,true,false,473);
  perform public.add_paint_color('Bracken','bracken','#97604B','brown','door-colors','{Exterior,Doors}','{Gloss}',false,true,80,false,true,474);
  perform public.add_paint_color('Brazilwood','brazilwood','#61311E','brown','earth-tone-collection','{Living Room,Library,Office}','{Satin}',true,false,95,false,false,475);
  perform public.add_paint_color('Bronze','bronze','#603E2F','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Enamel,Gloss}',false,true,90,false,false,476);
  perform public.add_paint_color('Brunette','brunette','#7D4B36','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion,Satin,Gloss}',true,true,50,false,false,477);
  perform public.add_paint_color('Buckeye','buckeye','#7B442B','brown','door-colors','{Exterior,Doors}','{Emulsion,Enamel}',false,true,95,false,false,478);
  perform public.add_paint_color('Bullhide','bullhide','#844F37','brown','earth-tone-collection','{Living Room,Library,Office}','{Emulsion,Satin}',true,false,83,false,false,479);
  perform public.add_paint_color('Burnt Sienna','burnt-sienna','#8E4927','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Gloss}',false,true,90,false,false,480);
  perform public.add_paint_color('Cedar Brown','cedar-brown','#85482A','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion,Satin,Gloss}',true,true,51,false,false,481);
  perform public.add_paint_color('Chestnut Two','chestnut-two','#7E533D','brown','door-colors','{Exterior,Doors}','{Emulsion,Enamel}',false,true,34,false,false,482);
  perform public.add_paint_color('Cinnamon Two','cinnamon-two','#543524','brown','earth-tone-collection','{Living Room,Library,Office}','{Emulsion}',true,false,56,false,false,483);
  perform public.add_paint_color('Cocoa','cocoa','#98512A','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Emulsion,Enamel}',false,true,37,false,false,484);
  perform public.add_paint_color('Cola','cola','#673D26','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion}',true,false,52,false,false,485);
  perform public.add_paint_color('Colonial Brown','colonial-brown','#8C593B','brown','door-colors','{Exterior,Doors}','{Gloss}',false,true,63,false,false,486);
  perform public.add_paint_color('Copper Brown','copper-brown','#9A6647','brown','earth-tone-collection','{Living Room,Library,Office}','{Satin}',true,false,68,false,false,487);
  perform public.add_paint_color('Crab Brown','crab-brown','#6B3E22','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Gloss}',false,true,74,false,true,488);
  perform public.add_paint_color('Doe','doe','#7D563E','brown','brown-collection','{Doors,Trim,Furniture}','{Satin}',true,true,78,true,false,489);
  perform public.add_paint_color('Driftwood Brown','driftwood-brown','#A2592A','brown','door-colors','{Exterior,Doors}','{Emulsion,Enamel}',false,true,67,false,true,490);
  perform public.add_paint_color('Dunes','dunes','#935831','brown','earth-tone-collection','{Living Room,Library,Office}','{Emulsion}',true,false,57,false,false,491);
  perform public.add_paint_color('Espresso Two','espresso-two','#5A351D','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Gloss}',false,true,60,false,false,492);
  perform public.add_paint_color('Fallow','fallow','#654834','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion,Satin,Gloss}',true,false,90,false,false,493);
  perform public.add_paint_color('Fudge','fudge','#B4662E','brown','door-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,50,false,true,494);
  perform public.add_paint_color('Fur Brown','fur-brown','#945B32','brown','earth-tone-collection','{Living Room,Library,Office}','{Emulsion}',true,true,66,false,false,495);
  perform public.add_paint_color('Gingerbread','gingerbread','#623D21','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Enamel,Gloss}',false,true,34,true,false,496);
  perform public.add_paint_color('Golden Brown','golden-brown','#543116','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion,Satin,Gloss}',true,true,80,false,false,497);
  perform public.add_paint_color('Hazel','hazel','#AE662D','brown','door-colors','{Exterior,Doors}','{Gloss}',false,true,34,false,false,498);
  perform public.add_paint_color('Hickory','hickory','#9E6D46','brown','earth-tone-collection','{Living Room,Library,Office}','{Satin}',true,false,93,true,false,499);
  perform public.add_paint_color('Honey Brown','honey-brown','#5B3C23','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Gloss}',false,true,44,false,false,500);
  perform public.add_paint_color('Mahogany Two','mahogany-two','#5E4632','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion,Satin,Gloss}',true,false,67,false,false,501);
  perform public.add_paint_color('Malt','malt','#88592F','brown','door-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,81,true,false,502);
  perform public.add_paint_color('Mocha','mocha','#513A26','brown','earth-tone-collection','{Living Room,Library,Office}','{Emulsion,Satin}',true,false,71,true,false,503);
  perform public.add_paint_color('Mole','mole','#87613E','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Emulsion,Enamel}',false,true,72,false,false,504);
  perform public.add_paint_color('Nut Brown','nut-brown','#52361B','brown','brown-collection','{Doors,Trim,Furniture}','{Satin}',true,false,45,false,false,505);
  perform public.add_paint_color('Oakwood','oakwood','#9C6B3B','brown','door-colors','{Exterior,Doors}','{Gloss}',false,true,69,false,false,506);
  perform public.add_paint_color('Pecan Brown','pecan-brown','#604121','brown','earth-tone-collection','{Living Room,Library,Office}','{Satin}',true,true,47,false,false,507);
  perform public.add_paint_color('Pine Bark','pine-bark','#876038','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Gloss}',false,true,90,false,false,508);
  perform public.add_paint_color('Praline','praline','#855A2C','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion,Satin,Gloss}',true,true,40,false,false,509);
  perform public.add_paint_color('Raisin','raisin','#73583A','brown','door-colors','{Exterior,Doors}','{Emulsion,Enamel}',false,true,37,true,true,510);
  perform public.add_paint_color('Russet','russet','#8E6B44','brown','earth-tone-collection','{Living Room,Library,Office}','{Emulsion,Satin,Gloss}',true,false,86,false,false,511);
  perform public.add_paint_color('Saddle Brown','saddle-brown','#9C6F3B','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Gloss}',false,true,87,true,false,512);
  perform public.add_paint_color('Seal Brown','seal-brown','#7F5A2D','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion}',true,false,69,false,false,513);
  perform public.add_paint_color('Sepia','sepia','#855C29','brown','door-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,35,false,false,514);
  perform public.add_paint_color('Sorrel','sorrel','#573B17','brown','earth-tone-collection','{Living Room,Library,Office}','{Emulsion,Satin}',true,false,90,false,false,515);
  perform public.add_paint_color('Suede','suede','#AD7835','brown','exterior-wall-colors','{Doors,Trim,Accent}','{Enamel,Gloss}',false,true,83,false,true,516);
  perform public.add_paint_color('Tobacco','tobacco','#856337','brown','brown-collection','{Doors,Trim,Furniture}','{Emulsion}',true,false,47,false,false,517);
  perform public.add_paint_color('Walnut Brown','walnut-brown','#79531E','brown','door-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,46,false,false,518);
  perform public.add_paint_color('Amaranth','amaranth','#921A2E','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion,Satin}',true,false,84,false,false,519);
  perform public.add_paint_color('Apple Red','apple-red','#592931','red','dining-room-colors','{Kitchen,Accent}','{Satin}',true,false,44,false,false,520);
  perform public.add_paint_color('Bay Red','bay-red','#4E2128','red','accent-colors','{Living Room,Library}','{Emulsion,Satin}',true,false,34,false,false,521);
  perform public.add_paint_color('Brick Two','brick-two','#82212E','red','warm-colors','{Exterior,Front Door}','{Emulsion,Satin,Gloss}',true,true,59,false,false,522);
  perform public.add_paint_color('Burgundy Two','burgundy-two','#6D242D','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion,Satin,Gloss}',true,true,70,false,false,523);
  perform public.add_paint_color('Cardinal','cardinal','#582329','red','dining-room-colors','{Kitchen,Accent}','{Emulsion,Satin,Gloss}',true,true,58,false,false,524);
  perform public.add_paint_color('Carnelian','carnelian','#81252F','red','accent-colors','{Living Room,Library}','{Emulsion,Satin,Gloss}',true,false,93,false,false,525);
  perform public.add_paint_color('Cherry Wood','cherry-wood','#791D25','red','warm-colors','{Exterior,Front Door}','{Emulsion}',true,false,83,false,false,526);
  perform public.add_paint_color('Cherry Blossom','cherry-blossom','#5F292D','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion}',true,false,48,true,true,527);
  perform public.add_paint_color('Cinnabar','cinnabar','#5D1D22','red','dining-room-colors','{Kitchen,Accent}','{Emulsion}',true,false,61,false,false,528);
  perform public.add_paint_color('Claret','claret','#5F1419','red','accent-colors','{Living Room,Library}','{Emulsion}',true,false,54,false,false,529);
  perform public.add_paint_color('Coral Red','coral-red','#6B161B','red','warm-colors','{Exterior,Front Door}','{Emulsion,Satin}',true,false,57,false,true,530);
  perform public.add_paint_color('Cranberry','cranberry','#5A282A','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion,Satin}',true,false,45,false,false,531);
  perform public.add_paint_color('Crimson Tide','crimson-tide','#652527','red','dining-room-colors','{Kitchen,Accent}','{Emulsion,Satin,Gloss}',true,true,71,false,false,532);
  perform public.add_paint_color('Damask','damask','#6F2D2E','red','accent-colors','{Living Room,Library}','{Satin}',true,false,93,false,false,533);
  perform public.add_paint_color('Dark Crimson','dark-crimson','#841A1B','red','warm-colors','{Exterior,Front Door}','{Satin}',true,true,82,false,true,534);
  perform public.add_paint_color('Dragon','dragon','#AC4849','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion,Satin}',true,true,83,false,false,535);
  perform public.add_paint_color('Fire Engine','fire-engine','#973332','red','dining-room-colors','{Kitchen,Accent}','{Emulsion,Satin,Gloss}',true,false,73,false,false,536);
  perform public.add_paint_color('Flame Red','flame-red','#9E3837','red','accent-colors','{Living Room,Library}','{Emulsion}',true,true,75,false,false,537);
  perform public.add_paint_color('Garnet','garnet','#AD3B38','red','warm-colors','{Exterior,Front Door}','{Emulsion,Satin}',true,false,39,true,false,538);
  perform public.add_paint_color('Garnet Red','garnet-red','#864240','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion}',true,true,38,false,false,539);
  perform public.add_paint_color('Grenadine','grenadine','#844643','red','dining-room-colors','{Kitchen,Accent}','{Satin}',true,false,91,false,false,540);
  perform public.add_paint_color('Hibiscus','hibiscus','#77423F','red','accent-colors','{Living Room,Library}','{Emulsion}',true,false,65,false,false,541);
  perform public.add_paint_color('Holly Berry','holly-berry','#C3372D','red','warm-colors','{Exterior,Front Door}','{Emulsion}',true,false,43,true,false,542);
  perform public.add_paint_color('Jasper','jasper','#74211A','red','red-collection','{Dining Room,Living Room,Accent}','{Satin}',true,false,80,false,true,543);
  perform public.add_paint_color('Lava','lava','#731D14','red','dining-room-colors','{Kitchen,Accent}','{Emulsion,Satin,Gloss}',true,false,40,false,true,544);
  perform public.add_paint_color('Mahogany Red','mahogany-red','#74322A','red','accent-colors','{Living Room,Library}','{Emulsion,Satin}',true,true,90,false,false,545);
  perform public.add_paint_color('Mars Red','mars-red','#A43224','red','warm-colors','{Exterior,Front Door}','{Emulsion}',true,false,72,false,true,546);
  perform public.add_paint_color('Merlot','merlot','#A65448','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion,Satin}',true,false,90,false,true,547);
  perform public.add_paint_color('Mulberry','mulberry','#9C3020','red','dining-room-colors','{Kitchen,Accent}','{Satin}',true,false,34,false,true,548);
  perform public.add_paint_color('Nutmeg Red','nutmeg-red','#A64232','red','accent-colors','{Living Room,Library}','{Emulsion,Satin,Gloss}',true,false,80,true,false,549);
  perform public.add_paint_color('Persimmon','persimmon','#913727','red','warm-colors','{Exterior,Front Door}','{Emulsion}',true,false,79,false,false,550);
  perform public.add_paint_color('Pomegranate','pomegranate','#BC523E','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion,Satin}',true,true,36,false,false,551);
  perform public.add_paint_color('Poppy Field','poppy-field','#802917','red','dining-room-colors','{Kitchen,Accent}','{Emulsion}',true,false,64,false,false,552);
  perform public.add_paint_color('Port Red','port-red','#974736','red','accent-colors','{Living Room,Library}','{Emulsion}',true,false,78,false,false,553);
  perform public.add_paint_color('Puriri','puriri','#533129','red','warm-colors','{Exterior,Front Door}','{Emulsion,Satin}',true,true,49,false,false,554);
  perform public.add_paint_color('Raspberry','raspberry','#8E321B','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion,Satin}',true,false,64,false,false,555);
  perform public.add_paint_color('Redwood','redwood','#4D2E26','red','dining-room-colors','{Kitchen,Accent}','{Emulsion}',true,false,41,false,false,556);
  perform public.add_paint_color('Rosewood','rosewood','#723D2F','red','accent-colors','{Living Room,Library}','{Emulsion,Satin}',true,true,40,false,false,557);
  perform public.add_paint_color('Ruby','ruby','#612D1E','red','warm-colors','{Exterior,Front Door}','{Emulsion,Satin,Gloss}',true,true,78,false,false,558);
  perform public.add_paint_color('Rust Red','rust-red','#6F4638','red','red-collection','{Dining Room,Living Room,Accent}','{Emulsion,Satin,Gloss}',true,false,83,false,false,559);
  perform public.add_paint_color('Salmon Red','salmon-red','#8D3E24','red','dining-room-colors','{Kitchen,Accent}','{Emulsion,Satin,Gloss}',true,false,55,false,false,560);
  perform public.add_paint_color('Scarlet','scarlet','#8D4E37','red','accent-colors','{Living Room,Library}','{Emulsion}',true,false,72,false,false,561);
  perform public.add_paint_color('Smoked Red','smoked-red','#894E38','red','warm-colors','{Exterior,Front Door}','{Emulsion,Satin,Gloss}',true,true,55,false,false,562);
  perform public.add_paint_color('Tomato','tomato','#93553C','red','red-collection','{Dining Room,Living Room,Accent}','{Satin}',true,false,92,true,false,563);
  perform public.add_paint_color('Tuscan Red','tuscan-red','#833B1E','red','dining-room-colors','{Kitchen,Accent}','{Satin}',true,false,44,true,false,564);
  perform public.add_paint_color('Venetian Red','venetian-red','#924827','red','accent-colors','{Living Room,Library}','{Emulsion,Satin,Gloss}',true,true,89,true,false,565);
  perform public.add_paint_color('Vermilion','vermilion','#B65529','red','warm-colors','{Exterior,Front Door}','{Emulsion,Satin}',true,true,82,false,false,566);
  perform public.add_paint_color('Wine','wine','#A5542E','red','red-collection','{Dining Room,Living Room,Accent}','{Satin}',true,false,78,false,true,567);
  perform public.add_paint_color('Amaranth Yellow','amaranth-yellow','#E3CFA8','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion}',true,false,83,false,false,568);
  perform public.add_paint_color('Ambrosia','ambrosia','#B79F6D','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion,Satin}',true,false,75,false,false,569);
  perform public.add_paint_color('Apricot','apricot','#DFB252','yellow','warm-colors','{Bedroom,Children}','{Emulsion}',true,false,85,false,false,570);
  perform public.add_paint_color('Bumblebee','bumblebee','#CCAF6E','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion,Satin,Gloss}',true,false,94,false,true,571);
  perform public.add_paint_color('Buttercup','buttercup','#E2D3AF','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Satin}',true,false,44,true,false,572);
  perform public.add_paint_color('Canary','canary','#C5A559','yellow','kitchen-colors','{Living Room,Kitchen}','{Satin}',true,false,91,false,false,573);
  perform public.add_paint_color('Cantaloupe','cantaloupe','#C3A969','yellow','warm-colors','{Bedroom,Children}','{Emulsion}',true,true,44,false,false,574);
  perform public.add_paint_color('Champagne','champagne','#E7CD88','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion,Satin,Gloss}',true,false,52,false,false,575);
  perform public.add_paint_color('Citron','citron','#C4B078','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion}',true,false,53,false,false,576);
  perform public.add_paint_color('Daffodil','daffodil','#CDB672','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion,Satin,Gloss}',true,false,30,false,false,577);
  perform public.add_paint_color('Dandelion','dandelion','#DFCE99','yellow','warm-colors','{Bedroom,Children}','{Emulsion,Satin}',true,true,53,false,false,578);
  perform public.add_paint_color('Dijon','dijon','#D8C588','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion}',true,false,79,false,false,579);
  perform public.add_paint_color('Duck Yellow','duck-yellow','#E1D09A','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion}',true,false,68,true,false,580);
  perform public.add_paint_color('Egg Yolk','egg-yolk','#BBAA72','yellow','kitchen-colors','{Living Room,Kitchen}','{Satin}',true,false,53,false,false,581);
  perform public.add_paint_color('Flaxen','flaxen','#D2BC6D','yellow','warm-colors','{Bedroom,Children}','{Emulsion,Satin,Gloss}',true,false,92,false,false,582);
  perform public.add_paint_color('Freesia','freesia','#D3C075','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion,Satin,Gloss}',true,false,47,false,false,583);
  perform public.add_paint_color('Genoa Yellow','genoa-yellow','#E2C967','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Satin}',true,false,54,true,true,584);
  perform public.add_paint_color('Goldenrod','goldenrod','#CEBE7B','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion}',true,false,86,false,false,585);
  perform public.add_paint_color('Goldfinch','goldfinch','#C0B068','yellow','warm-colors','{Bedroom,Children}','{Emulsion,Satin,Gloss}',true,false,66,false,false,586);
  perform public.add_paint_color('Honey','honey','#C5B04A','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion}',true,true,44,false,false,587);
  perform public.add_paint_color('Inca Gold','inca-gold','#D9C768','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion,Satin}',true,true,57,true,false,588);
  perform public.add_paint_color('Jasmine','jasmine','#E1DAB6','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion,Satin,Gloss}',true,true,87,false,true,589);
  perform public.add_paint_color('Lemon Chiffon','lemon-chiffon','#D4C04E','yellow','warm-colors','{Bedroom,Children}','{Emulsion,Satin}',true,false,74,true,false,590);
  perform public.add_paint_color('Lemon Meringue','lemon-meringue','#E5DA95','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion,Satin,Gloss}',true,false,37,false,false,591);
  perform public.add_paint_color('Macaron','macaron','#D4CC95','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion,Satin,Gloss}',true,false,67,false,true,592);
  perform public.add_paint_color('Maize','maize','#D1CBA0','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion,Satin}',true,false,82,true,true,593);
  perform public.add_paint_color('Mango','mango','#CDBD45','yellow','warm-colors','{Bedroom,Children}','{Emulsion,Satin,Gloss}',true,true,48,false,false,594);
  perform public.add_paint_color('Marigold','marigold','#D4CC82','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion}',true,true,64,false,false,595);
  perform public.add_paint_color('Golden Yellow','golden-yellow','#D9D298','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion,Satin}',true,false,77,false,false,596);
  perform public.add_paint_color('Narcissus','narcissus','#D9CF6B','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion,Satin}',true,false,75,true,false,597);
  perform public.add_paint_color('Nugget','nugget','#DDD46C','yellow','warm-colors','{Bedroom,Children}','{Emulsion}',true,false,71,true,false,598);
  perform public.add_paint_color('Ochre','ochre','#E8E29F','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion}',true,false,36,false,false,599);
  perform public.add_paint_color('Papaya','papaya','#D6D3AB','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion,Satin}',true,true,86,false,true,600);
  perform public.add_paint_color('Passion Fruit','passion-fruit','#DAD252','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion,Satin,Gloss}',true,false,65,false,false,601);
  perform public.add_paint_color('Peach Yellow','peach-yellow','#C8C695','yellow','warm-colors','{Bedroom,Children}','{Emulsion,Satin,Gloss}',true,false,59,false,false,602);
  perform public.add_paint_color('Pineapple','pineapple','#C3BE50','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion,Satin,Gloss}',true,false,58,false,false,603);
  perform public.add_paint_color('Primrose','primrose','#EBE9AA','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Satin}',true,false,84,false,false,604);
  perform public.add_paint_color('Rapeseed','rapeseed','#CECA40','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion,Satin}',true,false,70,false,false,605);
  perform public.add_paint_color('Royal Gold','royal-gold','#DDDC89','yellow','warm-colors','{Bedroom,Children}','{Emulsion,Satin,Gloss}',true,false,38,false,false,606);
  perform public.add_paint_color('Saffron','saffron','#C0BF5E','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion}',true,false,49,true,false,607);
  perform public.add_paint_color('Sandstone','sandstone','#AFAF5F','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion,Satin,Gloss}',true,false,45,false,false,608);
  perform public.add_paint_color('School Bus','school-bus','#D4D54F','yellow','kitchen-colors','{Living Room,Kitchen}','{Satin}',true,true,40,false,false,609);
  perform public.add_paint_color('Star Yellow','star-yellow','#E0E186','yellow','warm-colors','{Bedroom,Children}','{Satin}',true,true,68,false,false,610);
  perform public.add_paint_color('Sundance','sundance','#B4B750','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion}',true,false,60,false,false,611);
  perform public.add_paint_color('Sunburst','sunburst','#E3E5AF','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion,Satin}',true,false,76,true,false,612);
  perform public.add_paint_color('Sunflower','sunflower','#D2D592','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion}',true,true,90,true,false,613);
  perform public.add_paint_color('Sunny','sunny','#AEB16E','yellow','warm-colors','{Bedroom,Children}','{Emulsion,Satin}',true,false,37,true,false,614);
  perform public.add_paint_color('Sweet Corn','sweet-corn','#C6CB70','yellow','living-room-colors','{Kitchen,Dining,Hallway}','{Emulsion}',true,false,49,false,false,615);
  perform public.add_paint_color('Tiger Lily','tiger-lily','#D0DB3B','yellow','yellow-collection','{Kitchen,Children,Bathroom}','{Emulsion,Satin,Gloss}',true,false,71,false,false,616);
  perform public.add_paint_color('Topaz','topaz','#C2C879','yellow','kitchen-colors','{Living Room,Kitchen}','{Emulsion,Satin}',true,true,60,false,false,617);
  perform public.add_paint_color('Amber Glow','amber-glow','#90432A','orange','orange-collection','{Accent,Living Room,Dining}','{Emulsion}',true,false,52,false,false,618);
  perform public.add_paint_color('Apricot Blast','apricot-blast','#AD573A','orange','accent-colors','{Exterior,Front Door}','{Emulsion,Satin,Gloss}',true,true,63,false,false,619);
  perform public.add_paint_color('Burnt Orange','burnt-orange','#9C4727','orange','warm-colors','{Living Room,Accent}','{Satin}',true,true,33,false,false,620);
  perform public.add_paint_color('Cantaloupe Glow','cantaloupe-glow','#B37F6B','orange','exterior-wall-colors','{Kitchen,Dining}','{Gloss}',false,true,39,false,false,621);
  perform public.add_paint_color('Carrot','carrot','#9D573C','orange','orange-collection','{Accent,Living Room,Dining}','{Emulsion,Satin,Gloss}',true,false,43,true,false,622);
  perform public.add_paint_color('Citrus Orange','citrus-orange','#BA8E7B','orange','accent-colors','{Exterior,Front Door}','{Emulsion,Satin}',true,false,61,false,false,623);
  perform public.add_paint_color('Clay','clay','#DE8057','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin,Gloss}',true,true,83,false,false,624);
  perform public.add_paint_color('Coral Sunset','coral-sunset','#C4876C','orange','exterior-wall-colors','{Kitchen,Dining}','{Gloss}',false,true,77,false,false,625);
  perform public.add_paint_color('Crushed Orange','crushed-orange','#DC906B','orange','orange-collection','{Accent,Living Room,Dining}','{Emulsion,Satin,Gloss}',true,false,81,false,false,626);
  perform public.add_paint_color('Dahlia Orange','dahlia-orange','#B8714E','orange','accent-colors','{Exterior,Front Door}','{Satin}',true,false,31,false,false,627);
  perform public.add_paint_color('Dawn','dawn','#C1734C','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin,Gloss}',true,true,93,true,false,628);
  perform public.add_paint_color('Dizzy Orange','dizzy-orange','#DA7D4C','orange','exterior-wall-colors','{Kitchen,Dining}','{Gloss}',false,true,61,false,true,629);
  perform public.add_paint_color('Ember','ember','#CC7C4F','orange','orange-collection','{Accent,Living Room,Dining}','{Satin}',true,false,31,true,false,630);
  perform public.add_paint_color('Firecracker','firecracker','#AC7657','orange','accent-colors','{Exterior,Front Door}','{Satin}',true,false,60,false,true,631);
  perform public.add_paint_color('Flame','flame','#985228','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin,Gloss}',true,true,59,true,false,632);
  perform public.add_paint_color('Grapefruit','grapefruit','#CE692A','orange','exterior-wall-colors','{Kitchen,Dining}','{Gloss}',false,true,40,false,false,633);
  perform public.add_paint_color('Halloween Orange','halloween-orange','#AD7B5C','orange','orange-collection','{Accent,Living Room,Dining}','{Emulsion}',true,false,85,false,false,634);
  perform public.add_paint_color('Harvest Orange','harvest-orange','#C76727','orange','accent-colors','{Exterior,Front Door}','{Satin}',true,false,71,false,false,635);
  perform public.add_paint_color('Hibiscus Orange','hibiscus-orange','#BA8D6E','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin,Gloss}',true,false,43,false,false,636);
  perform public.add_paint_color('Jack O Lantern','jack-o-lantern','#8C5B38','orange','exterior-wall-colors','{Kitchen,Dining}','{Emulsion,Enamel}',false,true,75,true,false,637);
  perform public.add_paint_color('Kumquat','kumquat','#9D5722','orange','orange-collection','{Accent,Living Room,Dining}','{Satin}',true,false,68,true,false,638);
  perform public.add_paint_color('Mango Tango','mango-tango','#B78A67','orange','accent-colors','{Exterior,Front Door}','{Satin}',true,false,75,false,false,639);
  perform public.add_paint_color('Marina Orange','marina-orange','#9D7452','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin,Gloss}',true,false,87,false,false,640);
  perform public.add_paint_color('Marmalade','marmalade','#C99264','orange','exterior-wall-colors','{Kitchen,Dining}','{Enamel,Gloss}',false,true,47,false,false,641);
  perform public.add_paint_color('Nasturtium','nasturtium','#BC9574','orange','orange-collection','{Accent,Living Room,Dining}','{Emulsion,Satin,Gloss}',true,true,77,false,true,642);
  perform public.add_paint_color('Nectarine','nectarine','#9E5B1F','orange','accent-colors','{Exterior,Front Door}','{Satin}',true,false,38,false,false,643);
  perform public.add_paint_color('Orange Peel','orange-peel','#DC9654','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin}',true,true,72,false,true,644);
  perform public.add_paint_color('Orangeade','orangeade','#B18458','orange','exterior-wall-colors','{Kitchen,Dining}','{Enamel,Gloss}',false,true,80,false,false,645);
  perform public.add_paint_color('Papaya Whip','papaya-whip','#8F673F','orange','orange-collection','{Accent,Living Room,Dining}','{Satin}',true,false,65,false,false,646);
  perform public.add_paint_color('Peach Cobbler','peach-cobbler','#C68038','orange','accent-colors','{Exterior,Front Door}','{Emulsion,Satin,Gloss}',true,false,91,false,false,647);
  perform public.add_paint_color('Persimmon Orange','persimmon-orange','#D0985B','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin,Gloss}',true,false,61,false,false,648);
  perform public.add_paint_color('Pumpkin','pumpkin','#DE984B','orange','exterior-wall-colors','{Kitchen,Dining}','{Enamel,Gloss}',false,true,75,false,false,649);
  perform public.add_paint_color('Rust','rust','#956A38','orange','orange-collection','{Accent,Living Room,Dining}','{Satin}',true,false,70,false,false,650);
  perform public.add_paint_color('Saffron Orange','saffron-orange','#C2A788','orange','accent-colors','{Exterior,Front Door}','{Satin}',true,true,75,false,true,651);
  perform public.add_paint_color('Salmon','salmon','#967040','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin}',true,true,37,false,true,652);
  perform public.add_paint_color('Sandy Orange','sandy-orange','#D99E53','orange','exterior-wall-colors','{Kitchen,Dining}','{Gloss}',false,true,75,true,true,653);
  perform public.add_paint_color('Sienna','sienna','#CE9E5F','orange','orange-collection','{Accent,Living Room,Dining}','{Emulsion,Satin,Gloss}',true,false,75,true,false,654);
  perform public.add_paint_color('Spiced Orange','spiced-orange','#9E7031','orange','accent-colors','{Exterior,Front Door}','{Emulsion,Satin,Gloss}',true,true,93,false,false,655);
  perform public.add_paint_color('Sunset Coral','sunset-coral','#937140','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin}',true,false,91,false,true,656);
  perform public.add_paint_color('Tangerine','tangerine','#BB812B','orange','exterior-wall-colors','{Kitchen,Dining}','{Enamel,Gloss}',false,true,52,true,false,657);
  perform public.add_paint_color('Terra Cotta','terra-cotta','#B79766','orange','orange-collection','{Accent,Living Room,Dining}','{Emulsion,Satin}',true,false,48,false,false,658);
  perform public.add_paint_color('Tiger Orange','tiger-orange','#CBAA77','orange','accent-colors','{Exterior,Front Door}','{Emulsion,Satin}',true,true,80,false,false,659);
  perform public.add_paint_color('Tangerine Dream','tangerine-dream','#C38C31','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin,Gloss}',true,false,92,false,false,660);
  perform public.add_paint_color('Traffic Orange','traffic-orange','#D6AE69','orange','exterior-wall-colors','{Kitchen,Dining}','{Gloss}',false,true,75,false,false,661);
  perform public.add_paint_color('Vermillion','vermillion','#B2822D','orange','orange-collection','{Accent,Living Room,Dining}','{Satin}',true,false,52,false,true,662);
  perform public.add_paint_color('Volcanic Orange','volcanic-orange','#D8A84F','orange','accent-colors','{Exterior,Front Door}','{Emulsion}',true,true,34,false,false,663);
  perform public.add_paint_color('Warm Amber','warm-amber','#97722B','orange','warm-colors','{Living Room,Accent}','{Emulsion,Satin,Gloss}',true,true,93,false,false,664);
  perform public.add_paint_color('Amethyst Two','amethyst-two','#8470AC','purple','purple-collection','{Bedroom,Living Room,Accent}','{Satin}',true,false,41,true,false,665);
  perform public.add_paint_color('Aubergine','aubergine','#4D3678','purple','bedroom-colors','{Bedroom,Dressing Room}','{Satin}',true,true,61,false,false,666);
  perform public.add_paint_color('Bilberry','bilberry','#61507D','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion,Satin}',true,true,83,true,true,667);
  perform public.add_paint_color('Blue Violet','blue-violet','#5A4082','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion}',true,false,91,false,false,668);
  perform public.add_paint_color('Boysenberry','boysenberry','#433358','purple','purple-collection','{Bedroom,Living Room,Accent}','{Emulsion,Satin,Gloss}',true,true,34,false,false,669);
  perform public.add_paint_color('Byzantine','byzantine','#8A69B4','purple','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin}',true,true,50,false,false,670);
  perform public.add_paint_color('Cerise','cerise','#9475BA','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion,Satin}',true,true,91,false,false,671);
  perform public.add_paint_color('Claret Purple','claret-purple','#48355B','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion}',true,false,56,true,false,672);
  perform public.add_paint_color('Concord','concord','#5A3084','purple','purple-collection','{Bedroom,Living Room,Accent}','{Satin}',true,false,42,false,false,673);
  perform public.add_paint_color('Concord Grape','concord-grape','#40314E','purple','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,true,41,false,false,674);
  perform public.add_paint_color('Dark Violet','dark-violet','#543E65','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion,Satin,Gloss}',true,false,67,true,false,675);
  perform public.add_paint_color('Deep Purple','deep-purple','#9564BA','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion}',true,false,63,false,false,676);
  perform public.add_paint_color('Eggplant','eggplant','#6D438B','purple','purple-collection','{Bedroom,Living Room,Accent}','{Emulsion}',true,false,63,false,false,677);
  perform public.add_paint_color('Electric Purple','electric-purple','#855D9E','purple','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin}',true,true,42,false,false,678);
  perform public.add_paint_color('Fandango','fandango','#9759BB','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion,Satin,Gloss}',true,false,83,true,false,679);
  perform public.add_paint_color('Grape','grape','#4F2B62','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion,Satin,Gloss}',true,true,34,false,true,680);
  perform public.add_paint_color('Grape Soda','grape-soda','#8D64A2','purple','purple-collection','{Bedroom,Living Room,Accent}','{Emulsion,Satin,Gloss}',true,true,52,true,false,681);
  perform public.add_paint_color('Heliotrope','heliotrope','#6F4C7E','purple','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,false,85,false,false,682);
  perform public.add_paint_color('Hyacinth','hyacinth','#9257AA','purple','luxury-colors','{Living Room,Dining,Accent}','{Satin}',true,false,38,false,false,683);
  perform public.add_paint_color('Indigo','indigo','#A664BE','purple','accent-colors','{Bedroom,Bathroom}','{Satin}',true,false,31,false,false,684);
  perform public.add_paint_color('Iris','iris','#563A5F','purple','purple-collection','{Bedroom,Living Room,Accent}','{Emulsion}',true,false,42,true,false,685);
  perform public.add_paint_color('Jam Purple','jam-purple','#B050CB','purple','bedroom-colors','{Bedroom,Dressing Room}','{Satin}',true,false,82,false,false,686);
  perform public.add_paint_color('Lavender Bliss','lavender-bliss','#63456B','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion}',true,false,48,false,false,687);
  perform public.add_paint_color('Lavender Mist','lavender-mist','#7E2991','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion}',true,false,60,false,false,688);
  perform public.add_paint_color('Lilac','lilac','#9970A1','purple','purple-collection','{Bedroom,Living Room,Accent}','{Satin}',true,false,68,false,false,689);
  perform public.add_paint_color('Magenta','magenta','#782285','purple','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin}',true,true,68,true,false,690);
  perform public.add_paint_color('Mauve','mauve','#A23BAF','purple','luxury-colors','{Living Room,Dining,Accent}','{Satin}',true,true,41,false,false,691);
  perform public.add_paint_color('Mauve Taupe','mauve-taupe','#BB53C6','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion}',true,true,37,false,false,692);
  perform public.add_paint_color('Medium Purple','medium-purple','#A46EA9','purple','purple-collection','{Bedroom,Living Room,Accent}','{Emulsion}',true,false,33,false,true,693);
  perform public.add_paint_color('Midnight Purple','midnight-purple','#844987','purple','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin}',true,false,76,false,false,694);
  perform public.add_paint_color('Mulberry Purple','mulberry-purple','#6A286C','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion}',true,true,33,false,false,695);
  perform public.add_paint_color('Orchid','orchid','#873588','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion}',true,false,50,true,false,696);
  perform public.add_paint_color('Passionfruit','passionfruit','#814380','purple','purple-collection','{Bedroom,Living Room,Accent}','{Emulsion,Satin}',true,true,50,true,false,697);
  perform public.add_paint_color('Periwinkle Two','periwinkle-two','#B543B1','purple','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,false,64,false,false,698);
  perform public.add_paint_color('Petunia','petunia','#682E65','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion,Satin}',true,true,52,false,false,699);
  perform public.add_paint_color('Plum Crazy','plum-crazy','#BC41B3','purple','accent-colors','{Bedroom,Bathroom}','{Satin}',true,false,65,false,false,700);
  perform public.add_paint_color('Pomp Purple','pomp-purple','#74406F','purple','purple-collection','{Bedroom,Living Room,Accent}','{Satin}',true,false,80,false,false,701);
  perform public.add_paint_color('Purplish','purplish','#A6439A','purple','bedroom-colors','{Bedroom,Dressing Room}','{Satin}',true,true,66,false,false,702);
  perform public.add_paint_color('Royal Purple','royal-purple','#C058B2','purple','luxury-colors','{Living Room,Dining,Accent}','{Satin}',true,false,63,false,true,703);
  perform public.add_paint_color('Slate Purple','slate-purple','#A46499','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion,Satin,Gloss}',true,false,37,true,false,704);
  perform public.add_paint_color('Soft Mauve','soft-mauve','#BC44A5','purple','purple-collection','{Bedroom,Living Room,Accent}','{Satin}',true,false,93,true,false,705);
  perform public.add_paint_color('Thistle','thistle','#AD3A95','purple','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion}',true,false,54,false,false,706);
  perform public.add_paint_color('Twilight Purple','twilight-purple','#C136A1','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion}',true,false,94,false,false,707);
  perform public.add_paint_color('Velvet Purple','velvet-purple','#8B487A','purple','accent-colors','{Bedroom,Bathroom}','{Emulsion,Satin,Gloss}',true,false,63,false,false,708);
  perform public.add_paint_color('Viola','viola','#7A2C65','purple','purple-collection','{Bedroom,Living Room,Accent}','{Satin}',true,true,58,false,false,709);
  perform public.add_paint_color('Violet','violet','#9C4B84','purple','bedroom-colors','{Bedroom,Dressing Room}','{Satin}',true,true,89,true,false,710);
  perform public.add_paint_color('Wisteria','wisteria','#70315C','purple','luxury-colors','{Living Room,Dining,Accent}','{Emulsion,Satin}',true,true,45,true,false,711);
  perform public.add_paint_color('Antique Pink','antique-pink','#D56FB3','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion,Satin}',true,false,55,false,true,712);
  perform public.add_paint_color('Baby Pink','baby-pink','#DCC3D3','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion}',true,true,53,false,false,713);
  perform public.add_paint_color('Blush','blush','#BC7CA5','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion,Satin,Gloss}',true,false,87,false,false,714);
  perform public.add_paint_color('Bubblegum','bubblegum','#DEB4CE','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion,Satin,Gloss}',true,false,41,false,false,715);
  perform public.add_paint_color('Camellia','camellia','#DE83BB','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion}',true,false,34,false,false,716);
  perform public.add_paint_color('Carnation','carnation','#DD98C1','pink','bedroom-colors','{Bedroom,Dressing Room}','{Satin}',true,true,32,false,false,717);
  perform public.add_paint_color('Champagne Pink','champagne-pink','#BE80A4','pink','bathroom-colors','{Bathroom,Nursery}','{Satin}',true,false,94,false,false,718);
  perform public.add_paint_color('Cherry Blossom Pink','cherry-blossom-pink','#E08BBB','pink','accent-colors','{Bedroom,Living Room,Accent}','{Satin}',true,true,73,false,false,719);
  perform public.add_paint_color('Coral Pink','coral-pink','#C386A8','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion}',true,false,81,false,false,720);
  perform public.add_paint_color('Cotton Candy','cotton-candy','#DE9EC1','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,true,51,false,false,721);
  perform public.add_paint_color('Cranberry Pink','cranberry-pink','#D87AAB','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion}',true,true,36,false,false,722);
  perform public.add_paint_color('Cupcake','cupcake','#B58BA0','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion,Satin}',true,false,86,false,false,723);
  perform public.add_paint_color('Dusty Rose','dusty-rose','#D5B4C4','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion,Satin,Gloss}',true,false,31,false,false,724);
  perform public.add_paint_color('English Rose','english-rose','#DFABC4','pink','bedroom-colors','{Bedroom,Dressing Room}','{Satin}',true,false,83,true,false,725);
  perform public.add_paint_color('Fair Pink','fair-pink','#DBBAC9','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion,Satin}',true,true,93,false,false,726);
  perform public.add_paint_color('Fandango Pink','fandango-pink','#CD99B0','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion,Satin,Gloss}',true,false,50,false,false,727);
  perform public.add_paint_color('Fuchsia','fuchsia','#BB7795','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion}',true,false,41,true,false,728);
  perform public.add_paint_color('Geranium','geranium','#E9ACC6','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,false,39,false,false,729);
  perform public.add_paint_color('Golden Pink','golden-pink','#E6C8D4','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion,Satin,Gloss}',true,false,63,false,false,730);
  perform public.add_paint_color('Hibiscus Pink','hibiscus-pink','#DA85A7','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion,Satin}',true,false,70,false,false,731);
  perform public.add_paint_color('Hot Pink','hot-pink','#B48E9D','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion,Satin}',true,true,51,false,true,732);
  perform public.add_paint_color('Key Lime Pink','key-lime-pink','#D36991','pink','bedroom-colors','{Bedroom,Dressing Room}','{Satin}',true,true,73,false,false,733);
  perform public.add_paint_color('Lavender Pink','lavender-pink','#E3A5BB','pink','bathroom-colors','{Bathroom,Nursery}','{Satin}',true,true,91,false,false,734);
  perform public.add_paint_color('Lemon Pink','lemon-pink','#D5B9C2','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion,Satin}',true,true,50,false,true,735);
  perform public.add_paint_color('Light Pink','light-pink','#C69CA9','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion}',true,false,75,false,true,736);
  perform public.add_paint_color('Lotus Pink','lotus-pink','#D39CAD','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,true,82,false,false,737);
  perform public.add_paint_color('Magenta Pink','magenta-pink','#E0A7B8','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion,Satin}',true,false,58,true,false,738);
  perform public.add_paint_color('Millennial Pink','millennial-pink','#DCB2BE','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion,Satin}',true,false,91,false,false,739);
  perform public.add_paint_color('Misty Rose','misty-rose','#DDCBD0','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion,Satin}',true,false,94,true,true,740);
  perform public.add_paint_color('Mulberry Pink','mulberry-pink','#D68499','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin}',true,true,72,true,false,741);
  perform public.add_paint_color('Old Pink','old-pink','#C78897','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion}',true,false,88,false,false,742);
  perform public.add_paint_color('Pale Pink','pale-pink','#C47C8D','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion}',true,false,93,false,false,743);
  perform public.add_paint_color('Peach Pink','peach-pink','#C46D80','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion,Satin}',true,false,41,false,true,744);
  perform public.add_paint_color('Periwinkle Pink','periwinkle-pink','#D794A1','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,false,73,false,false,745);
  perform public.add_paint_color('Pig Pink','pig-pink','#DBB8BE','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion}',true,false,90,false,false,746);
  perform public.add_paint_color('Pistol Pink','pistol-pink','#D37A89','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion,Satin}',true,false,73,false,false,747);
  perform public.add_paint_color('Plum Pink','plum-pink','#CB6C7B','pink','pink-collection','{Bedroom,Children,Bathroom}','{Satin}',true,true,51,false,false,748);
  perform public.add_paint_color('Powder Pink','powder-pink','#CFB0B4','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion}',true,true,54,false,true,749);
  perform public.add_paint_color('Primrose Pink','primrose-pink','#CE717D','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion,Satin,Gloss}',true,false,83,false,false,750);
  perform public.add_paint_color('Rose Quartz','rose-quartz','#DB9098','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion,Satin}',true,false,94,false,false,751);
  perform public.add_paint_color('Rosy Pink','rosy-pink','#D3959B','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion,Satin}',true,false,91,true,false,752);
  perform public.add_paint_color('Salmon Pink','salmon-pink','#CF737A','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,true,79,false,false,753);
  perform public.add_paint_color('Shell Pink','shell-pink','#D7A8AB','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion}',true,false,61,false,true,754);
  perform public.add_paint_color('Soft Pink','soft-pink','#D27176','pink','accent-colors','{Bedroom,Living Room,Accent}','{Emulsion}',true,true,95,false,false,755);
  perform public.add_paint_color('Strawberry','strawberry','#D2AFB0','pink','pink-collection','{Bedroom,Children,Bathroom}','{Emulsion,Satin,Gloss}',true,true,67,false,true,756);
  perform public.add_paint_color('Sweet Pink','sweet-pink','#DCAEAF','pink','bedroom-colors','{Bedroom,Dressing Room}','{Emulsion,Satin,Gloss}',true,false,71,false,false,757);
  perform public.add_paint_color('Tickle Pink','tickle-pink','#E7BCBD','pink','bathroom-colors','{Bathroom,Nursery}','{Emulsion}',true,false,66,true,false,758);
end $$;