-- =========================================================
-- ARCHIE UNIVERSAL LEXICON ENGINE — SCHEMA (§LEXICON)
--
-- A normalized, database-backed lexical data layer giving
-- ARCHIE structured knowledge of words, meanings, senses,
-- relationships, provenance and contextual meaning.
--
--   lexicon_sources        — provenance: dataset, version,
--                            license, attribution
--   lexicon_words          — word forms (multi-POS), variants,
--                            pronunciation, inflections
--   lexicon_senses         — every distinct meaning separately
--                            (one word → many senses), with
--                            knowledge status + source
--   lexicon_relationships  — synset-level semantic graph
--                            (hypernym/hyponym, meronym/holonym,
--                            similar, entails, causes, domains…)
--   lexicon_sense_relations— sense-level relations (antonym,
--                            derivation, pertainym, also-see…)
--   lexicon_imports        — honest ingestion log: counts,
--                            duplicates, validation errors
--
-- Principles:
--   * VERIFIED data is sourced; UNVERIFIED is never presented
--     as dictionary fact (retrieval filters by status).
--   * Accuracy over volume: provenance is mandatory, counts are
--     reported honestly from real rows, nothing is fabricated.
--   * Domains/registers/regions are metadata, not hard-coded.
--   * Deterministic UUIDs (v5) are generated by the ingestion
--     pipeline so re-imports are idempotent, never duplicated.
-- =========================================================

-- ---------------------------------------------------------
-- 1. Sources & provenance
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lexicon_sources (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  dataset text NOT NULL,
  version text NOT NULL,
  license text NOT NULL,
  attribution text NOT NULL DEFAULT '',
  url text,
  imported_at timestamptz NOT NULL DEFAULT now(),
  notes text,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  UNIQUE (dataset, version)
);

-- ---------------------------------------------------------
-- 2. Words (form layer; one row per lemma × POS)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lexicon_words (
  id uuid PRIMARY KEY,
  canonical text NOT NULL,                 -- lemma as written ("give up")
  normalized text NOT NULL,                -- lowercase lookup form ("give up")
  spelling_variants jsonb NOT NULL DEFAULT '[]',
  language text NOT NULL DEFAULT 'en',    -- multilingual by design
  regional_usage text,                    -- e.g. 'en-NG' (Nigerian English)
  pronunciation text,                     -- IPA where available
  part_of_speech text NOT NULL,           -- noun/verb/adjective/adverb/…
  unit_type text NOT NULL DEFAULT 'WORD'
    CHECK (unit_type IN ('WORD','PHRASAL_VERB','IDIOM','MULTI_WORD_EXPRESSION',
                         'ABBREVIATION','ACRONYM')),
  inflection_metadata jsonb NOT NULL DEFAULT '{}',
  frequency numeric,                       -- only where legitimately sourced
  metadata jsonb NOT NULL DEFAULT '{}',
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  UNIQUE (language, normalized, part_of_speech)
);

CREATE INDEX IF NOT EXISTS lexicon_words_normalized_idx
  ON public.lexicon_words (normalized, language);
CREATE INDEX IF NOT EXISTS lexicon_words_language_pos_idx
  ON public.lexicon_words (language, part_of_speech);
CREATE INDEX IF NOT EXISTS lexicon_words_unit_type_idx
  ON public.lexicon_words (unit_type);

-- ---------------------------------------------------------
-- 3. Senses (meaning layer; NEVER collapse meanings)
--    Example: "run" — move on foot / operate / execute
--    software / flow / manage a business — each its own row.
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lexicon_senses (
  id uuid PRIMARY KEY,
  word_id uuid NOT NULL REFERENCES public.lexicon_words(id) ON DELETE CASCADE,
  source_id uuid REFERENCES public.lexicon_sources(id),
  external_id text NOT NULL UNIQUE,       -- dataset sense key (e.g. run%2:41:01::)
  synset_key text NOT NULL,               -- shared meaning cluster ("00190414-n")
  definition text NOT NULL,
  usage_examples jsonb NOT NULL DEFAULT '[]',
  domain text,                            -- metadata (e.g. "noun.act", "computing")
  register text,                          -- standard / informal / slang / technical / obsolete
  region text,                             -- e.g. "NG", "US", "UK" where sourced
  grammatical jsonb NOT NULL DEFAULT '{}',
  confidence numeric,                      -- 1.0 only when directly sourced; else null
  created_by uuid,                         -- for USER_PROVIDED entries (owner attribution)
  knowledge_status text NOT NULL DEFAULT 'UNVERIFIED'
    CHECK (knowledge_status IN ('VERIFIED','LEARNED','USER_PROVIDED','UNVERIFIED')),
  version integer NOT NULL DEFAULT 1,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS lexicon_senses_word_idx
  ON public.lexicon_senses (word_id, knowledge_status);
CREATE INDEX IF NOT EXISTS lexicon_senses_synset_idx
  ON public.lexicon_senses (synset_key);
CREATE INDEX IF NOT EXISTS lexicon_senses_status_idx
  ON public.lexicon_senses (knowledge_status);
CREATE INDEX IF NOT EXISTS lexicon_senses_domain_idx
  ON public.lexicon_senses (domain);

-- ---------------------------------------------------------
-- 4. Synset-level semantic graph
--    Stored separately from definitions so ARCHIE can
--    traverse the lexical graph.
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lexicon_relationships (
  id uuid PRIMARY KEY,
  relation_type text NOT NULL,             -- HYPERNYM/HYPONYM/MERONYM_PART/…
  from_synset_key text NOT NULL,
  to_synset_key text NOT NULL,
  source_id uuid REFERENCES public.lexicon_sources(id),
  created_date timestamptz NOT NULL DEFAULT now(),
  UNIQUE (relation_type, from_synset_key, to_synset_key)
);

CREATE INDEX IF NOT EXISTS lexicon_relationships_from_idx
  ON public.lexicon_relationships (from_synset_key, relation_type);
CREATE INDEX IF NOT EXISTS lexicon_relationships_to_idx
  ON public.lexicon_relationships (to_synset_key, relation_type);

-- ---------------------------------------------------------
-- 5. Sense-level relations (antonym, derivation, …)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lexicon_sense_relations (
  id uuid PRIMARY KEY,
  relation_type text NOT NULL,             -- ANTONYM/DERIVATION/PERTAINYM/…
  from_sense_external_id text NOT NULL,
  to_sense_external_id text NOT NULL,
  source_id uuid REFERENCES public.lexicon_sources(id),
  created_date timestamptz NOT NULL DEFAULT now(),
  UNIQUE (relation_type, from_sense_external_id, to_sense_external_id)
);

CREATE INDEX IF NOT EXISTS lexicon_sense_relations_from_idx
  ON public.lexicon_sense_relations (from_sense_external_id, relation_type);
CREATE INDEX IF NOT EXISTS lexicon_sense_relations_to_idx
  ON public.lexicon_sense_relations (to_sense_external_id, relation_type);

-- ---------------------------------------------------------
-- 6. Ingestion log — honest, auditable imports
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lexicon_imports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id uuid REFERENCES public.lexicon_sources(id),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'RUNNING'
    CHECK (status IN ('RUNNING','SUCCESS','FAILED','PARTIAL')),
  stats jsonb NOT NULL DEFAULT '{}',
  errors jsonb NOT NULL DEFAULT '[]',
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------
-- 7. RLS — admins manage; users read verified lexical facts
-- ---------------------------------------------------------
ALTER TABLE public.lexicon_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lexicon_words ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lexicon_senses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lexicon_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lexicon_sense_relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lexicon_imports ENABLE ROW LEVEL SECURITY;

-- Sources: public provenance metadata is readable by any
-- authenticated user (license/attribution must travel with
-- the data it licenses).
DROP POLICY IF EXISTS "admins manage lexicon sources" ON public.lexicon_sources;
CREATE POLICY "admins manage lexicon sources"
  ON public.lexicon_sources FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "users read lexicon sources" ON public.lexicon_sources;
CREATE POLICY "users read lexicon sources"
  ON public.lexicon_sources FOR SELECT TO authenticated
  USING (true);

-- Words: form data is public language structure; admins manage.
DROP POLICY IF EXISTS "admins manage lexicon words" ON public.lexicon_words;
CREATE POLICY "admins manage lexicon words"
  ON public.lexicon_words FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "users read lexicon words" ON public.lexicon_words;
CREATE POLICY "users read lexicon words"
  ON public.lexicon_words FOR SELECT TO authenticated
  USING (true);

-- Senses: only VERIFIED (or the user's own USER_PROVIDED data)
-- is readable by non-admins. UNVERIFIED/LEARNED never presented
-- as dictionary fact.
DROP POLICY IF EXISTS "admins manage lexicon senses" ON public.lexicon_senses;
CREATE POLICY "admins manage lexicon senses"
  ON public.lexicon_senses FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "users read verified lexicon senses" ON public.lexicon_senses;
CREATE POLICY "users read verified lexicon senses"
  ON public.lexicon_senses FOR SELECT TO authenticated
  USING (knowledge_status = 'VERIFIED'
         OR (knowledge_status = 'USER_PROVIDED' AND created_by = auth.uid()));

-- Synset relationships: readable (graph traversal); admin-managed.
DROP POLICY IF EXISTS "admins manage lexicon relationships" ON public.lexicon_relationships;
CREATE POLICY "admins manage lexicon relationships"
  ON public.lexicon_relationships FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "users read lexicon relationships" ON public.lexicon_relationships;
CREATE POLICY "users read lexicon relationships"
  ON public.lexicon_relationships FOR SELECT TO authenticated
  USING (true);

-- Sense relations: same pattern.
DROP POLICY IF EXISTS "admins manage lexicon sense relations" ON public.lexicon_sense_relations;
CREATE POLICY "admins manage lexicon sense relations"
  ON public.lexicon_sense_relations FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "users read lexicon sense relations" ON public.lexicon_sense_relations;
CREATE POLICY "users read lexicon sense relations"
  ON public.lexicon_sense_relations FOR SELECT TO authenticated
  USING (true);

-- Imports: admin-only (internal operational detail).
DROP POLICY IF EXISTS "admins manage lexicon imports" ON public.lexicon_imports;
CREATE POLICY "admins manage lexicon imports"
  ON public.lexicon_imports FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());
