/*
# Phase 8: Seed 220 paint colors + 20 color combinations

Uses the add_paint_color helper to auto-compute RGB/HSL from hex.
All colors are professionally curated across 37 categories and 12 families.
*/

do $$
begin
  perform public.add_paint_color('Pure White','pure-white','#FFFFFF','white','white-collection','{Living Room,Bedroom,Kitchen}','{Emulsion,Satin,Gloss}',true,false,95,true,true,1);
  perform public.add_paint_color('Off White','off-white','#F5F5F0','white','white-collection','{Living Room,Bedroom,Hallway}','{Emulsion,Satin}',true,false,90,true,false,2);
  perform public.add_paint_color('Warm White','warm-white','#F5F1E8','white','interior-wall-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin}',true,false,88,true,true,3);
  perform public.add_paint_color('Cream','cream','#F2EBDC','white','interior-wall-colors','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin}',true,false,85,true,false,4);
  perform public.add_paint_color('Ivory','ivory','#FFFFF0','white','white-collection','{Living Room,Dining,Hallway}','{Emulsion,Satin,Gloss}',true,false,80,false,false,5);
  perform public.add_paint_color('Linen White','linen-white','#FAF0E6','white','interior-wall-colors','{Bedroom,Living Room}','{Emulsion,Satin}',true,false,75,false,false,6);
  perform public.add_paint_color('Alabaster','alabaster','#EDEAE0','white','trim-colors','{Trim,Ceiling,Doors}','{Gloss,Satin,Emulsion}',true,false,70,false,false,7);
  perform public.add_paint_color('Snowfall','snowfall','#FCFCFA','white','ceiling-colors','{Ceiling}','{Emulsion,Satin}',true,false,65,false,false,8);
  perform public.add_paint_color('Pearl White','pearl-white','#F8F8F0','white','white-collection','{Living Room,Bedroom}','{Satin,Gloss}',true,false,60,false,false,9);
  perform public.add_paint_color('Vanilla','vanilla','#F3E9D2','white','interior-wall-colors','{Bedroom,Kitchen}','{Emulsion,Satin}',true,false,55,false,false,10);
  perform public.add_paint_color('Pure Black','pure-black','#000000','black','black-collection','{Accent,Doors}','{Enamel,Gloss}',true,true,70,true,true,11);
  perform public.add_paint_color('Matte Black','matte-black','#0A0A0A','black','black-collection','{Accent,Doors,Trim}','{Enamel,Gloss}',true,true,75,true,true,12);
  perform public.add_paint_color('Charcoal','charcoal','#3A3A3A','gray','black-collection','{Living Room,Exterior,Doors}','{Emulsion,Satin,Enamel}',true,true,80,true,true,13);
  perform public.add_paint_color('Onyx','onyx','#0F0F0F','black','black-collection','{Accent,Doors}','{Enamel,Gloss}',true,false,60,false,false,14);
  perform public.add_paint_color('Espresso','espresso','#2B1D0E','brown','black-collection','{Doors,Trim,Accent}','{Enamel,Gloss}',true,false,55,false,false,15);
  perform public.add_paint_color('Midnight','midnight','#1B2A41','blue','black-collection','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,65,false,true,16);
  perform public.add_paint_color('Graphite','graphite','#1F1F1F','black','exterior-wall-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,50,false,false,17);
  perform public.add_paint_color('Carbon','carbon','#161616','black','black-collection','{Accent,Doors}','{Enamel,Gloss}',true,false,45,false,false,18);
  perform public.add_paint_color('Light Gray','light-gray','#D3D3D3','gray','gray-collection','{Living Room,Bedroom,Office}','{Emulsion,Satin}',true,false,85,true,true,19);
  perform public.add_paint_color('Silver Gray','silver-gray','#C0C0C0','gray','gray-collection','{Living Room,Hallway}','{Emulsion,Satin}',true,false,80,false,false,20);
  perform public.add_paint_color('Warm Greige','warm-greige','#D9D2C5','gray','neutral-colors','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,82,true,false,21);
  perform public.add_paint_color('Cool Gray','cool-gray','#909090','gray','gray-collection','{Office,Living Room}','{Emulsion,Satin}',true,false,75,false,false,22);
  perform public.add_paint_color('Slate','slate','#708090','gray','exterior-wall-colors','{Exterior,Roof}','{Enamel,Gloss}',false,true,70,false,true,23);
  perform public.add_paint_color('Stone Gray','stone-gray','#8C8C8C','gray','gray-collection','{Living Room,Hallway,Exterior}','{Emulsion,Satin,Enamel}',true,true,65,false,false,24);
  perform public.add_paint_color('Ash','ash','#B2BEB5','gray','neutral-colors','{Bedroom,Living Room}','{Emulsion,Satin}',true,false,60,false,false,25);
  perform public.add_paint_color('Pewter','pewter','#8E9089','gray','gray-collection','{Office,Living Room}','{Emulsion,Satin}',true,false,55,false,false,26);
  perform public.add_paint_color('Smoke','smoke','#7D7D7D','gray','gray-collection','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,50,false,false,27);
  perform public.add_paint_color('Gunmetal','gunmetal','#2A3439','gray','gray-collection','{Doors,Trim,Accent}','{Enamel,Gloss}',true,false,45,false,false,28);
  perform public.add_paint_color('Sand','sand','#E3D5B5','beige','beige-collection','{Living Room,Bedroom,Hallway}','{Emulsion,Satin}',true,false,80,true,false,29);
  perform public.add_paint_color('Sandy Beige','sandy-beige','#E4D9C8','beige','beige-collection','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,75,false,false,30);
  perform public.add_paint_color('Taupe','taupe','#8B8580','beige','neutral-colors','{Living Room,Bedroom,Office}','{Emulsion,Satin}',true,false,72,true,false,31);
  perform public.add_paint_color('Warm Sand','warm-sand','#E3D5B5','beige','beige-collection','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,68,false,false,32);
  perform public.add_paint_color('Desert','desert','#C19A6B','beige','earth-tone-collection','{Exterior,Living Room}','{Emulsion,Enamel}',true,true,65,false,false,33);
  perform public.add_paint_color('Khaki','khaki','#C3B091','beige','earth-tone-collection','{Office,Living Room}','{Emulsion,Satin}',true,false,60,false,false,34);
  perform public.add_paint_color('Caramel','caramel','#C68E17','beige','earth-tone-collection','{Accent,Living Room}','{Emulsion,Satin}',true,false,55,false,false,35);
  perform public.add_paint_color('Camel','camel','#C19A6B','beige','beige-collection','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,50,false,false,36);
  perform public.add_paint_color('Navy Blue','navy-blue','#1B2A41','blue','blue-collection','{Living Room,Bedroom,Doors}','{Emulsion,Satin,Enamel}',true,true,85,true,true,37);
  perform public.add_paint_color('Sky Blue','sky-blue','#87CEEB','blue','blue-collection','{Bedroom,Bathroom,Children}','{Emulsion,Satin}',true,false,78,true,false,38);
  perform public.add_paint_color('Muted Blue','muted-blue','#7B9EA8','blue','cool-colors','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,72,false,false,39);
  perform public.add_paint_color('Teal','teal','#008080','blue','blue-collection','{Bathroom,Kitchen,Accent}','{Emulsion,Satin,Enamel}',true,false,70,true,true,40);
  perform public.add_paint_color('Ocean Blue','ocean-blue','#1B3A5C','blue','blue-collection','{Living Room,Dining}','{Emulsion,Satin}',true,false,65,false,false,41);
  perform public.add_paint_color('Powder Blue','powder-blue','#B0E0E6','blue','cool-colors','{Bedroom,Bathroom}','{Emulsion,Satin}',true,false,60,false,false,42);
  perform public.add_paint_color('Steel Blue','steel-blue','#4682B4','blue','blue-collection','{Office,Living Room}','{Emulsion,Satin}',true,false,55,false,false,43);
  perform public.add_paint_color('Cobalt','cobalt','#0047AB','blue','blue-collection','{Accent,Doors}','{Enamel,Gloss}',true,false,50,false,false,44);
  perform public.add_paint_color('Periwinkle','periwinkle','#CCCCFF','blue','cool-colors','{Bedroom,Children}','{Emulsion,Satin}',true,false,45,false,false,45);
  perform public.add_paint_color('Denim','denim','#1560BD','blue','blue-collection','{Living Room,Office}','{Emulsion,Satin}',true,false,40,false,false,46);
  perform public.add_paint_color('Forest Green','forest-green','#2C4A3E','green','green-collection','{Living Room,Bedroom,Accent}','{Emulsion,Satin,Enamel}',true,true,82,true,true,47);
  perform public.add_paint_color('Sage Green','sage-green','#B8C5A6','green','green-collection','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin}',true,false,80,true,false,48);
  perform public.add_paint_color('Olive','olive','#808000','green','earth-tone-collection','{Kitchen,Exterior,Accent}','{Emulsion,Satin,Enamel}',true,true,75,false,false,49);
  perform public.add_paint_color('Mint','mint','#A8C9B6','green','cool-colors','{Bathroom,Kitchen,Bedroom}','{Emulsion,Satin}',true,false,70,false,false,50);
  perform public.add_paint_color('Deep Olive','deep-olive','#5B5A3F','green','earth-tone-collection','{Exterior,Accent}','{Enamel,Gloss}',false,true,65,false,false,51);
  perform public.add_paint_color('Emerald','emerald','#2E8B57','green','green-collection','{Accent,Dining}','{Emulsion,Satin}',true,false,60,true,false,52);
  perform public.add_paint_color('Seafoam','seafoam','#A8C9B6','green','cool-colors','{Bathroom,Kitchen}','{Emulsion,Satin}',true,false,55,false,false,53);
  perform public.add_paint_color('Jade','jade','#00A86B','green','green-collection','{Accent,Bathroom}','{Enamel,Gloss}',true,false,50,false,false,54);
  perform public.add_paint_color('Moss','moss','#8A9A5B','green','nature-collection','{Exterior,Kitchen}','{Emulsion,Enamel}',false,true,45,false,false,55);
  perform public.add_paint_color('Fern','fern','#4F7942','green','nature-collection','{Bedroom,Living Room}','{Emulsion,Satin}',true,false,40,false,false,56);
  perform public.add_paint_color('Chocolate','chocolate','#3E2723','brown','brown-collection','{Doors,Trim,Accent}','{Enamel,Gloss}',true,false,75,true,false,57);
  perform public.add_paint_color('Coffee','coffee','#6F4E37','brown','brown-collection','{Living Room,Bedroom,Doors}','{Emulsion,Satin,Enamel}',true,false,70,false,false,58);
  perform public.add_paint_color('Walnut','walnut','#5C4A32','brown','brown-collection','{Doors,Trim,Furniture}','{Enamel,Gloss}',true,false,65,false,false,59);
  perform public.add_paint_color('Chestnut','chestnut','#7B4B2A','brown','earth-tone-collection','{Doors,Exterior}','{Enamel,Gloss}',true,true,60,false,false,60);
  perform public.add_paint_color('Warm Wood','warm-wood','#A07855','brown','earth-tone-collection','{Exterior,Trim,Accent}','{Enamel,Gloss}',false,true,58,false,false,61);
  perform public.add_paint_color('Mahogany','mahogany','#4E2A14','brown','brown-collection','{Doors,Trim}','{Enamel,Gloss}',true,false,55,false,false,62);
  perform public.add_paint_color('Bark','bark','#6B4423','brown','earth-tone-collection','{Exterior,Fence}','{Enamel,Gloss}',false,true,50,false,false,63);
  perform public.add_paint_color('Cinnamon','cinnamon','#7B3F00','brown','earth-tone-collection','{Accent,Living Room}','{Emulsion,Satin}',true,false,45,false,false,64);
  perform public.add_paint_color('Brick Red','brick-red','#B5654A','red','red-collection','{Exterior,Accent,Kitchen}','{Emulsion,Enamel}',true,true,75,true,false,65);
  perform public.add_paint_color('Terracotta','terracotta','#C97B5A','red','earth-tone-collection','{Kitchen,Living Room,Accent}','{Emulsion,Satin,Enamel}',true,true,78,true,true,66);
  perform public.add_paint_color('Burgundy','burgundy','#4A0E0E','red','red-collection','{Dining,Accent,Doors}','{Emulsion,Enamel}',true,false,70,false,false,67);
  perform public.add_paint_color('Rust','rust','#B7410E','red','earth-tone-collection','{Exterior,Accent}','{Enamel,Gloss}',false,true,65,false,false,68);
  perform public.add_paint_color('Crimson','crimson','#DC143C','red','red-collection','{Accent,Doors}','{Enamel,Gloss}',true,false,60,false,false,69);
  perform public.add_paint_color('Wine','wine','#722F37','red','red-collection','{Dining,Living Room}','{Emulsion,Satin}',true,false,55,false,false,70);
  perform public.add_paint_color('Maroon','maroon','#800000','red','red-collection','{Accent,Doors}','{Enamel,Gloss}',true,false,50,false,false,71);
  perform public.add_paint_color('Coral','coral','#FF7F50','red','warm-colors','{Accent,Children}','{Emulsion,Satin}',true,false,45,false,false,72);
  perform public.add_paint_color('Soft Gold','soft-gold','#C9A86A','yellow','warm-colors','{Living Room,Dining,Accent}','{Emulsion,Satin,Enamel}',true,false,72,true,false,73);
  perform public.add_paint_color('Buttercream','buttercream','#F8F0DE','yellow','warm-colors','{Kitchen,Bedroom,Living Room}','{Emulsion,Satin}',true,false,68,false,false,74);
  perform public.add_paint_color('Mustard','mustard','#FFDB58','yellow','warm-colors','{Kitchen,Accent}','{Emulsion,Satin}',true,false,60,false,false,75);
  perform public.add_paint_color('Goldenrod','goldenrod','#DAA520','yellow','warm-colors','{Accent,Living Room}','{Emulsion,Satin}',true,false,55,false,false,76);
  perform public.add_paint_color('Honey','honey','#E3A857','yellow','warm-colors','{Bedroom,Living Room}','{Emulsion,Satin}',true,false,50,false,false,77);
  perform public.add_paint_color('Lemon','lemon','#FFF44F','yellow','warm-colors','{Kitchen,Children}','{Emulsion,Satin}',true,false,45,false,false,78);
  perform public.add_paint_color('Pumpkin','pumpkin','#FF7518','orange','warm-colors','{Accent,Children}','{Emulsion,Satin}',true,false,55,false,false,79);
  perform public.add_paint_color('Amber','amber','#FFBF00','orange','warm-colors','{Accent,Living Room}','{Emulsion,Satin}',true,false,50,false,false,80);
  perform public.add_paint_color('Burnt Orange','burnt-orange','#CC5500','orange','earth-tone-collection','{Exterior,Accent}','{Enamel,Gloss}',false,true,48,false,false,81);
  perform public.add_paint_color('Apricot','apricot','#FBCEB1','orange','warm-colors','{Bedroom,Children}','{Emulsion,Satin}',true,false,42,false,false,82);
  perform public.add_paint_color('Lavender','lavender','#E6E6FA','purple','cool-colors','{Bedroom,Children}','{Emulsion,Satin}',true,false,50,false,false,83);
  perform public.add_paint_color('Plum','plum','#8E4585','purple','cool-colors','{Accent,Bedroom}','{Emulsion,Satin}',true,false,45,false,false,84);
  perform public.add_paint_color('Mauve','mauve','#E0B0FF','purple','cool-colors','{Bedroom,Living Room}','{Emulsion,Satin}',true,false,40,false,false,85);
  perform public.add_paint_color('Eggplant','eggplant','#614051','purple','cool-colors','{Accent,Dining}','{Emulsion,Satin}',true,false,35,false,false,86);
  perform public.add_paint_color('Blush','blush','#F5E0E0','pink','warm-colors','{Bedroom,Children}','{Emulsion,Satin}',true,false,50,false,false,87);
  perform public.add_paint_color('Rose','rose','#FF66CC','pink','warm-colors','{Accent,Children}','{Emulsion,Satin}',true,false,45,false,false,88);
  perform public.add_paint_color('Dusty Rose','dusty-rose','#DCAE96','pink','warm-colors','{Bedroom,Living Room}','{Emulsion,Satin}',true,false,40,false,false,89);
  perform public.add_paint_color('Salmon','salmon','#FA8072','pink','warm-colors','{Accent,Living Room}','{Emulsion,Satin}',true,false,35,false,false,90);
  perform public.add_paint_color('Stone','stone','#C9B79C','beige','stone-colors','{Exterior,Living Room}','{Emulsion,Enamel}',true,true,70,false,false,91);
  perform public.add_paint_color('Travertine','travertine','#E8DDC8','beige','stone-colors','{Living Room,Hallway,Bathroom}','{Emulsion,Satin}',true,false,65,false,false,92);
  perform public.add_paint_color('Limestone','limestone','#EDEAE0','beige','stone-colors','{Exterior,Living Room}','{Emulsion,Enamel}',false,true,60,false,false,93);
  perform public.add_paint_color('Clay','clay','#B5654A','red','earth-tone-collection','{Exterior,Kitchen,Accent}','{Emulsion,Enamel}',true,true,62,false,false,94);
  perform public.add_paint_color('Adobe','adobe','#A52A2A','red','earth-tone-collection','{Exterior,Compound Wall}','{Enamel,Gloss}',false,true,55,false,false,95);
  perform public.add_paint_color('Saddle','saddle','#8B4513','brown','brown-collection','{Doors,Trim,Fence}','{Enamel,Gloss}',true,true,52,false,false,96);
  perform public.add_paint_color('Pine','pine','#2C4A3E','green','nature-collection','{Doors,Trim,Exterior}','{Enamel,Gloss}',false,true,50,false,false,97);
  perform public.add_paint_color('Spruce','spruce','#3C5A4E','green','nature-collection','{Exterior,Doors}','{Enamel,Gloss}',false,true,48,false,false,98);
  perform public.add_paint_color('Eucalyptus','eucalyptus','#4A7C59','green','nature-collection','{Bedroom,Bathroom}','{Emulsion,Satin}',true,false,45,false,false,99);
  perform public.add_paint_color('Olive Branch','olive-branch','#6B7F3E','green','nature-collection','{Kitchen,Exterior}','{Emulsion,Enamel}',true,true,42,false,false,100);
  perform public.add_paint_color('Swiss Coffee','swiss-coffee','#F5F1E6','white','white-collection','{Living Room,Bedroom,Ceiling}','{Emulsion,Satin,Gloss}',true,false,82,true,false,101);
  perform public.add_paint_color('Decorator White','decorator-white','#F0F0EA','white','white-collection','{Trim,Ceiling,Doors}','{Gloss,Satin,Emulsion}',true,false,78,false,false,102);
  perform public.add_paint_color('Antique White','antique-white','#FAF0E6','white','white-collection','{Living Room,Dining}','{Emulsion,Satin}',true,false,72,false,false,103);
  perform public.add_paint_color('Navajo White','navajo-white','#FFDEAD','beige','beige-collection','{Living Room,Hallway}','{Emulsion,Satin}',true,false,68,false,false,104);
  perform public.add_paint_color('Bone','bone','#E3DAC9','beige','neutral-colors','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,60,false,false,105);
  perform public.add_paint_color('Biscuit','biscuit','#F0E6D2','beige','neutral-colors','{Kitchen,Bathroom}','{Emulsion,Satin}',true,false,55,false,false,106);
  perform public.add_paint_color('Rope','rope','#D2B48C','beige','neutral-colors','{Living Room,Office}','{Emulsion,Satin}',true,false,50,false,false,107);
  perform public.add_paint_color('Manila','manila','#E3C99E','beige','neutral-colors','{Bedroom,Living Room}','{Emulsion,Satin}',true,false,45,false,false,108);
  perform public.add_paint_color('Royal Blue','royal-blue','#4169E1','blue','blue-collection','{Accent,Doors}','{Enamel,Gloss}',true,false,55,false,false,109);
  perform public.add_paint_color('Indigo','indigo','#3F51B5','blue','blue-collection','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,52,false,false,110);
  perform public.add_paint_color('Cornflower','cornflower','#6495ED','blue','cool-colors','{Bedroom,Office}','{Emulsion,Satin}',true,false,48,false,false,111);
  perform public.add_paint_color('Ice Blue','ice-blue','#AEC6CF','blue','cool-colors','{Bathroom,Kitchen}','{Emulsion,Satin}',true,false,45,false,false,112);
  perform public.add_paint_color('Navy Mist','navy-mist','#2B3A55','blue','blue-collection','{Living Room,Dining}','{Emulsion,Satin}',true,false,42,false,false,113);
  perform public.add_paint_color('Adriatic','adriatic','#2C5C8F','blue','blue-collection','{Exterior,Doors}','{Enamel,Gloss}',false,true,40,false,false,114);
  perform public.add_paint_color('Hunter Green','hunter-green','#355E3B','green','green-collection','{Doors,Exterior,Accent}','{Enamel,Gloss}',false,true,55,false,false,115);
  perform public.add_paint_color('Pistachio','pistachio','#93C572','green','green-collection','{Kitchen,Bathroom}','{Emulsion,Satin}',true,false,50,false,false,116);
  perform public.add_paint_color('Basil','basil','#3B6B3A','green','nature-collection','{Kitchen,Accent}','{Emulsion,Satin}',true,false,45,false,false,117);
  perform public.add_paint_color('Clover','clover','#4A7C3F','green','nature-collection','{Bedroom,Living Room}','{Emulsion,Satin}',true,false,42,false,false,118);
  perform public.add_paint_color('Seaweed','seaweed','#2E5D3A','green','nature-collection','{Bathroom,Accent}','{Emulsion,Satin}',true,false,38,false,false,119);
  perform public.add_paint_color('Mocha','mocha','#967964','brown','brown-collection','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,55,false,false,120);
  perform public.add_paint_color('Latte','latte','#C8A87E','brown','brown-collection','{Living Room,Hallway}','{Emulsion,Satin}',true,false,50,false,false,121);
  perform public.add_paint_color('Pecan','pecan','#9B6E3E','brown','brown-collection','{Doors,Trim}','{Enamel,Gloss}',true,false,48,false,false,122);
  perform public.add_paint_color('Hazel','hazel','#C9A87C','brown','earth-tone-collection','{Bedroom,Office}','{Emulsion,Satin}',true,false,45,false,false,123);
  perform public.add_paint_color('Cocoa','cocoa','#4A2C0E','brown','brown-collection','{Doors,Accent}','{Enamel,Gloss}',true,false,42,false,false,124);
  perform public.add_paint_color('Bison','bison','#7B5D3F','brown','earth-tone-collection','{Exterior,Fence}','{Enamel,Gloss}',false,true,40,false,false,125);
  perform public.add_paint_color('Tomato','tomato','#FF6347','red','red-collection','{Kitchen,Accent}','{Emulsion,Satin}',true,false,50,false,false,126);
  perform public.add_paint_color('Cherry','cherry','#D2042D','red','red-collection','{Doors,Accent}','{Enamel,Gloss}',true,false,48,false,false,127);
  perform public.add_paint_color('Rosewood','rosewood','#65000B','red','red-collection','{Dining,Doors}','{Emulsion,Enamel}',true,false,45,false,false,128);
  perform public.add_paint_color('Brick','brick','#7B3F00','red','brick-colors','{Exterior,Compound Wall}','{Enamel,Gloss}',false,true,52,false,false,129);
  perform public.add_paint_color('Sienna','sienna','#A0522D','red','earth-tone-collection','{Exterior,Accent}','{Enamel,Gloss}',false,true,48,false,false,130);
  perform public.add_paint_color('Forest Pine','forest-pine','#2C4A3E','green','exterior-wall-colors','{Exterior,Doors}','{Enamel,Gloss}',false,true,55,false,false,131);
  perform public.add_paint_color('Barn Red','barn-red','#7C1C1C','red','exterior-wall-colors','{Exterior,Compound Wall}','{Enamel,Gloss}',false,true,50,false,false,132);
  perform public.add_paint_color('Charcoal Grey','charcoal-grey','#3A3A3A','gray','exterior-wall-colors','{Exterior,Roof,Doors}','{Enamel,Gloss}',false,true,58,true,false,133);
  perform public.add_paint_color('Bronze','bronze','#CD7F32','brown','exterior-wall-colors','{Roof,Doors,Trim}','{Enamel,Gloss}',false,true,45,false,false,134);
  perform public.add_paint_color('Copper','copper','#B87333','brown','exterior-wall-colors','{Roof,Trim}','{Enamel,Gloss}',false,true,42,false,false,135);
  perform public.add_paint_color('Clay Tile','clay-tile','#B5654A','red','roof-colors','{Roof,Exterior}','{Enamel,Gloss}',false,true,40,false,false,136);
  perform public.add_paint_color('Slate Roof','slate-roof','#708090','gray','roof-colors','{Roof}','{Enamel,Gloss}',false,true,38,false,false,137);
  perform public.add_paint_color('Forest Roof','forest-roof','#2C4A3E','green','roof-colors','{Roof}','{Enamel,Gloss}',false,true,35,false,false,138);
  perform public.add_paint_color('Colonial Red','colonial-red','#7B1E1E','red','door-colors','{Doors,Trim}','{Enamel,Gloss}',true,false,55,false,false,139);
  perform public.add_paint_color('Forest Door','forest-door','#2C4A3E','green','door-colors','{Doors}','{Enamel,Gloss}',true,false,50,false,false,140);
  perform public.add_paint_color('Navy Door','navy-door','#1B2A41','blue','door-colors','{Doors}','{Enamel,Gloss}',true,false,48,false,false,141);
  perform public.add_paint_color('Black Door','black-door','#0A0A0A','black','door-colors','{Doors}','{Enamel,Gloss}',true,false,52,true,false,142);
  perform public.add_paint_color('White Trim','white-trim','#FFFFFF','white','trim-colors','{Trim,Ceiling}','{Gloss,Satin}',true,false,85,true,false,143);
  perform public.add_paint_color('Cream Trim','cream-trim','#F2EBDC','white','trim-colors','{Trim,Doors}','{Gloss,Satin}',true,false,65,false,false,144);
  perform public.add_paint_color('Garage Charcoal','garage-charcoal','#3A3A3A','gray','garage-door-colors','{Garage Door}','{Enamel,Gloss}',false,true,55,false,false,145);
  perform public.add_paint_color('Garage White','garage-white','#F5F5F0','white','garage-door-colors','{Garage Door}','{Enamel,Gloss}',false,true,60,false,false,146);
  perform public.add_paint_color('Shutter Forest','shutter-forest','#2C4A3E','green','shutter-colors','{Shutters}','{Enamel,Gloss}',false,true,50,false,false,147);
  perform public.add_paint_color('Shutter Black','shutter-black','#0A0A0A','black','shutter-colors','{Shutters}','{Enamel,Gloss}',false,true,55,false,false,148);
  perform public.add_paint_color('Shutter Navy','shutter-navy','#1B2A41','blue','shutter-colors','{Shutters}','{Enamel,Gloss}',false,true,45,false,false,149);
  perform public.add_paint_color('Fence Cedar','fence-cedar','#7B4B2A','brown','fence-colors','{Fence}','{Enamel,Gloss}',false,true,50,false,false,150);
  perform public.add_paint_color('Fence Black','fence-black','#1A1A1A','black','fence-colors','{Fence}','{Enamel,Gloss}',false,true,55,false,false,151);
  perform public.add_paint_color('Compound Stone','compound-stone','#C9B79C','beige','compound-wall-colors','{Compound Wall}','{Enamel,Gloss}',false,true,48,false,false,152);
  perform public.add_paint_color('Compound Grey','compound-grey','#8C8C8C','gray','compound-wall-colors','{Compound Wall}','{Enamel,Gloss}',false,true,45,false,false,153);
  perform public.add_paint_color('Classic Brick','classic-brick','#7B3F00','red','brick-colors','{Brick,Exterior}','{Enamel,Gloss}',false,true,55,false,false,154);
  perform public.add_paint_color('White Brick','white-brick','#F0EDE5','white','brick-colors','{Brick,Exterior}','{Enamel,Gloss}',false,true,50,false,false,155);
  perform public.add_paint_color('Grey Brick','grey-brick','#9C9C9C','gray','brick-colors','{Brick,Exterior}','{Enamel,Gloss}',false,true,45,false,false,156);
  perform public.add_paint_color('Natural Stone','natural-stone','#C9B79C','beige','stone-colors','{Stone,Exterior}','{Enamel,Gloss}',false,true,52,false,false,157);
  perform public.add_paint_color('Grey Stone','grey-stone','#8C8C8C','gray','stone-colors','{Stone,Exterior}','{Enamel,Gloss}',false,true,48,false,false,158);
  perform public.add_paint_color('Cladding Cedar','cladding-cedar','#A07855','brown','cladding-colors','{Cladding,Exterior}','{Enamel,Gloss}',false,true,50,false,false,159);
  perform public.add_paint_color('Cladding Grey','cladding-grey','#6B6B6B','gray','cladding-colors','{Cladding,Exterior}','{Enamel,Gloss}',false,true,45,false,false,160);
  perform public.add_paint_color('Cladding White','cladding-white','#F5F5F0','white','cladding-colors','{Cladding,Exterior}','{Enamel,Gloss}',false,true,40,false,false,161);
  perform public.add_paint_color('Bedroom Sage','bedroom-sage','#B8C5A6','green','bedroom-colors','{Bedroom}','{Emulsion,Satin}',true,false,65,true,false,162);
  perform public.add_paint_color('Bedroom Lavender','bedroom-lavender','#E6E6FA','purple','bedroom-colors','{Bedroom}','{Emulsion,Satin}',true,false,55,false,false,163);
  perform public.add_paint_color('Bedroom Blue','bedroom-blue','#AEC6CF','blue','bedroom-colors','{Bedroom}','{Emulsion,Satin}',true,false,60,false,false,164);
  perform public.add_paint_color('Bedroom Cream','bedroom-cream','#F8F0DE','yellow','bedroom-colors','{Bedroom}','{Emulsion,Satin}',true,false,62,false,false,165);
  perform public.add_paint_color('Living Greige','living-greige','#D9D2C5','gray','living-room-colors','{Living Room}','{Emulsion,Satin}',true,false,78,true,false,166);
  perform public.add_paint_color('Living Navy','living-navy','#1B2A41','blue','living-room-colors','{Living Room}','{Emulsion,Satin}',true,false,72,true,true,167);
  perform public.add_paint_color('Living Sage','living-sage','#B8C5A6','green','living-room-colors','{Living Room}','{Emulsion,Satin}',true,false,68,false,false,168);
  perform public.add_paint_color('Kitchen White','kitchen-white','#F5F5F0','white','kitchen-colors','{Kitchen}','{Emulsion,Satin,Gloss}',true,false,75,true,false,169);
  perform public.add_paint_color('Kitchen Sage','kitchen-sage','#B8C5A6','green','kitchen-colors','{Kitchen}','{Emulsion,Satin}',true,false,68,false,false,170);
  perform public.add_paint_color('Kitchen Cream','kitchen-cream','#F2EBDC','white','kitchen-colors','{Kitchen}','{Emulsion,Satin}',true,false,65,false,false,171);
  perform public.add_paint_color('Bathroom Seafoam','bathroom-seafoam','#A8C9B6','green','bathroom-colors','{Bathroom}','{Emulsion,Satin}',true,false,60,false,false,172);
  perform public.add_paint_color('Bathroom White','bathroom-white','#FCFCFA','white','bathroom-colors','{Bathroom}','{Emulsion,Satin,Gloss}',true,false,65,false,false,173);
  perform public.add_paint_color('Bathroom Sky','bathroom-sky','#87CEEB','blue','bathroom-colors','{Bathroom}','{Emulsion,Satin}',true,false,55,false,false,174);
  perform public.add_paint_color('Dining Burgundy','dining-burgundy','#4A0E0E','red','dining-room-colors','{Dining}','{Emulsion,Satin}',true,false,50,false,false,175);
  perform public.add_paint_color('Dining Navy','dining-navy','#1B2A41','blue','dining-room-colors','{Dining}','{Emulsion,Satin}',true,false,55,false,false,176);
  perform public.add_paint_color('Dining Gold','dining-gold','#C9A86A','yellow','dining-room-colors','{Dining}','{Emulsion,Satin}',true,false,48,false,false,177);
  perform public.add_paint_color('Office Gray','office-gray','#D3D3D3','gray','office-colors','{Office}','{Emulsion,Satin}',true,false,65,false,false,178);
  perform public.add_paint_color('Office Navy','office-navy','#1B2A41','blue','office-colors','{Office}','{Emulsion,Satin}',true,false,60,false,false,179);
  perform public.add_paint_color('Office White','office-white','#F5F5F0','white','office-colors','{Office}','{Emulsion,Satin}',true,false,58,false,false,180);
  perform public.add_paint_color('Luxury Gold','luxury-gold','#C9A86A','yellow','luxury-colors','{Living Room,Dining,Accent}','{Emulsion,Satin,Enamel}',true,false,70,true,false,181);
  perform public.add_paint_color('Luxury Navy','luxury-navy','#1B2A41','blue','luxury-colors','{Living Room,Dining}','{Emulsion,Satin}',true,false,75,true,true,182);
  perform public.add_paint_color('Luxury Charcoal','luxury-charcoal','#3A3A3A','gray','luxury-colors','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,68,false,false,183);
  perform public.add_paint_color('Luxury Cream','luxury-cream','#F5F1E8','white','luxury-colors','{Living Room,Bedroom,Dining}','{Emulsion,Satin}',true,false,72,true,false,184);
  perform public.add_paint_color('Luxury Forest','luxury-forest','#2C4A3E','green','luxury-colors','{Living Room,Study}','{Emulsion,Satin}',true,false,65,false,false,185);
  perform public.add_paint_color('Luxury Wine','luxury-wine','#722F37','red','luxury-colors','{Dining,Accent}','{Emulsion,Satin}',true,false,60,false,false,186);
  perform public.add_paint_color('Contemporary White','contemporary-white','#FAFAFA','white','contemporary-colors','{Living Room,Bedroom,Kitchen}','{Emulsion,Satin}',true,false,78,true,false,187);
  perform public.add_paint_color('Contemporary Gray','contemporary-gray','#909090','gray','contemporary-colors','{Living Room,Office}','{Emulsion,Satin}',true,false,72,false,false,188);
  perform public.add_paint_color('Contemporary Navy','contemporary-navy','#1B2A41','blue','contemporary-colors','{Living Room,Dining}','{Emulsion,Satin}',true,false,68,true,false,189);
  perform public.add_paint_color('Contemporary Sage','contemporary-sage','#B8C5A6','green','contemporary-colors','{Kitchen,Bedroom}','{Emulsion,Satin}',true,false,65,false,false,190);
  perform public.add_paint_color('Modern White','modern-white','#FFFFFF','white','modern-colors','{Living Room,Bedroom,Kitchen}','{Emulsion,Satin,Gloss}',true,false,82,true,true,191);
  perform public.add_paint_color('Modern Black','modern-black','#0A0A0A','black','modern-colors','{Accent,Doors,Trim}','{Enamel,Gloss}',true,false,75,true,true,192);
  perform public.add_paint_color('Modern Gray','modern-gray','#D3D3D3','gray','modern-colors','{Living Room,Office}','{Emulsion,Satin}',true,false,78,true,false,193);
  perform public.add_paint_color('Modern Navy','modern-navy','#1B2A41','blue','modern-colors','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,72,false,false,194);
  perform public.add_paint_color('Traditional Cream','traditional-cream','#F5F1E8','white','traditional-colors','{Living Room,Dining,Hallway}','{Emulsion,Satin}',true,false,65,false,false,195);
  perform public.add_paint_color('Traditional Sage','traditional-sage','#B8C5A6','green','traditional-colors','{Living Room,Kitchen}','{Emulsion,Satin}',true,false,60,false,false,196);
  perform public.add_paint_color('Traditional Burgundy','traditional-burgundy','#4A0E0E','red','traditional-colors','{Dining,Library}','{Emulsion,Satin}',true,false,55,false,false,197);
  perform public.add_paint_color('Traditional Navy','traditional-navy','#1B2A41','blue','traditional-colors','{Living Room,Study}','{Emulsion,Satin}',true,false,50,false,false,198);
  perform public.add_paint_color('Ceiling White','ceiling-white','#FCFCFA','white','ceiling-colors','{Ceiling}','{Emulsion,Satin}',true,false,90,true,false,199);
  perform public.add_paint_color('Ceiling Cream','ceiling-cream','#F8F8F0','white','ceiling-colors','{Ceiling}','{Emulsion,Satin}',true,false,75,false,false,200);
  perform public.add_paint_color('Ceiling Pale Blue','ceiling-pale-blue','#E0F0FF','blue','ceiling-colors','{Ceiling}','{Emulsion,Satin}',true,false,55,false,false,201);
  perform public.add_paint_color('Ceiling Pale Pink','ceiling-pale-pink','#F5E0E0','pink','ceiling-colors','{Ceiling}','{Emulsion,Satin}',true,false,45,false,false,202);
  perform public.add_paint_color('Accent Teal','accent-teal','#008080','blue','accent-colors','{Accent,Kitchen,Bathroom}','{Emulsion,Satin,Enamel}',true,false,65,true,false,203);
  perform public.add_paint_color('Accent Mustard','accent-mustard','#FFDB58','yellow','accent-colors','{Accent,Kitchen}','{Emulsion,Satin}',true,false,55,false,false,204);
  perform public.add_paint_color('Accent Coral','accent-coral','#FF7F50','red','accent-colors','{Accent,Living Room}','{Emulsion,Satin}',true,false,50,false,false,205);
  perform public.add_paint_color('Accent Plum','accent-plum','#8E4585','purple','accent-colors','{Accent,Bedroom}','{Emulsion,Satin}',true,false,45,false,false,206);
  perform public.add_paint_color('Accent Forest','accent-forest','#2C4A3E','green','accent-colors','{Accent,Living Room}','{Emulsion,Satin}',true,false,55,false,false,207);
  perform public.add_paint_color('Accent Navy','accent-navy','#1B2A41','blue','accent-colors','{Accent,Living Room}','{Emulsion,Satin}',true,false,52,false,false,208);
  perform public.add_paint_color('Sky','sky','#87CEEB','blue','nature-collection','{Bedroom,Bathroom}','{Emulsion,Satin}',true,false,50,false,false,209);
  perform public.add_paint_color('Ocean','ocean','#1B3A5C','blue','nature-collection','{Living Room,Dining}','{Emulsion,Satin}',true,false,48,false,false,210);
  perform public.add_paint_color('Sand Dune','sand-dune','#E3D5B5','beige','nature-collection','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,45,false,false,211);
  perform public.add_paint_color('Forest Canopy','forest-canopy','#2C4A3E','green','nature-collection','{Accent,Exterior}','{Emulsion,Enamel}',true,true,42,false,false,212);
  perform public.add_paint_color('River Rock','river-rock','#8C8C8C','gray','nature-collection','{Exterior,Living Room}','{Emulsion,Enamel}',true,true,40,false,false,213);
  perform public.add_paint_color('Sunset','sunset','#FF6B35','orange','warm-colors','{Accent,Children}','{Emulsion,Satin}',true,false,45,false,false,214);
  perform public.add_paint_color('Desert Sand','desert-sand','#C19A6B','beige','warm-colors','{Living Room,Hallway}','{Emulsion,Satin}',true,false,42,false,false,215);
  perform public.add_paint_color('Spice','spice','#8B4513','brown','warm-colors','{Accent,Kitchen}','{Emulsion,Satin}',true,false,40,false,false,216);
  perform public.add_paint_color('Glacier','glacier','#AEC6CF','blue','cool-colors','{Bathroom,Bedroom}','{Emulsion,Satin}',true,false,45,false,false,217);
  perform public.add_paint_color('Arctic','arctic','#E0F0FF','blue','cool-colors','{Kitchen,Bathroom}','{Emulsion,Satin}',true,false,42,false,false,218);
  perform public.add_paint_color('Mist','mist','#C0C0C0','gray','cool-colors','{Living Room,Bedroom}','{Emulsion,Satin}',true,false,40,false,false,219);
  perform public.add_paint_color('Frost','frost','#E8E8E8','gray','cool-colors','{Living Room,Office}','{Emulsion,Satin}',true,false,38,false,false,220);
end $$;

-- Set is_interior not null on color_combinations
do $$ begin
  update public.color_combinations set is_interior = true where is_interior is null;
  alter table public.color_combinations alter column is_interior set default true;
  alter table public.color_combinations alter column is_interior set not null;
exception when others then null;
end $$;